import {loadState,hasSave,SAVE_KEY} from './state.js';
import {state,setState,startGame,acceptQuest,enterDungeon,returnTown,move,turn,attack,defend,useTonic,collectFind,persist} from './game.js';
import {quests,items} from './data.js';
const app=document.querySelector('#app'), modal=document.querySelector('#modal-root'), qa=new URLSearchParams(location.search).get('qa')==='1';
let screen='title',message='The town has posted new notices. The hole remains open.';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function title(){screen='title';render()}
function header(){return `<header class="topbar"><span class="brand">MIRPWORKS · DELVERS’ OFFICE</span><span class="top-actions">${state.player?`<button data-go="town">Town</button>`:''}<button data-action="help">Help</button></span></header>`}
function stats(){const p=state.player;return `<div class="stats"><span class="pill">${esc(p.name)} · ${p.class}</span><span class="pill">HP ${p.hp}/${p.maxHp}</span><span class="pill">Gold ${state.town.gold}</span><span class="pill">Level ${p.level} · XP ${p.xp}</span></div>`}
function town(){screen='town';render()}
function render(){if(screen==='title'){app.innerHTML=`<section class="title-screen"><div class="title-card"><div class="eyebrow">A Mirpworks game</div><h1 class="game-title">Why Is There a Hole in the Middle of Town?</h1><p class="subtle">The town has a procedure for this. The hole does not.</p><div class="button-stack">${hasSave()?'<button class="primary" data-action="continue">Continue</button>':''}<button class="primary" data-action="new">New Game</button><button data-action="help">About / Help</button></div><p class="footer">A turn-based descent · Best played one careful step at a time</p></div></section>`;return}
 let body='';
 if(screen==='create')body=`${header()}<section class="panel"><p class="eyebrow">Registration is mandatory</p><h1 class="section-title">Who’s going down?</h1><p class="subtle">The town requires a name for the incident report.</p><form id="create-form"><label>Delver name<input name="name" maxlength="24" required placeholder="e.g. Rowan" autocomplete="given-name"></label><label>Starting class<select name="class"><option>Fighter</option><option>Wizard</option><option>Rogue</option><option>Cleric</option></select></label><button class="primary" type="submit">Sign the waiver · Continue</button></form></section>`;
 if(screen==='town')body=`${header()}<p class="eyebrow">Town · Hole District</p><h1 class="section-title">The hole is open for business.</h1><p class="subtle">A hand-painted sign reads: “Please keep the entrance clear during deliveries.”</p><section class="panel">${stats()}</section><section class="hub-grid"><button class="location" data-go="dungeon">The Hole<span>Go down. Keep an eye on the stairs.</span></button><button class="location" data-go="quests">Quest Board<span>${state.quests.active.length} active · ${state.quests.available.length} posted</span></button><button class="location" data-go="store">General Store<span>Basic supplies, cash only.</span></button><button class="location" data-go="inn">The Inn<span>Rest up. The room rate is municipal.</span></button><button class="location" data-go="character">Character / Inventory<span>Review your kit and condition.</span></button></section><p class="notice">Town notice: The hole has been temporarily reclassified as a “persistent infrastructure feature.”</p>`;
 if(screen==='quests'){const list=[...state.quests.available.map(id=>({q:quests[id],active:false})),...state.quests.active.map(a=>({q:quests[a.id],active:true,progress:a.progress}))];body=`${header()}<p class="eyebrow">Town · Notice board</p><h1 class="section-title">Quest Board</h1><section class="panel">${list.length?list.map(({q,active,progress=0})=>`<div class="quest"><div><h3>${esc(q.title)}</h3><p>${esc(q.description)}</p><small class="subtle">${esc(q.giver)} · Reward ${q.reward.gold}g</small>${active?`<p>Progress ${progress}/${q.count}</p>`:''}</div>${active?'<span class="pill">Accepted</span>':`<button data-quest="${q.id}" ${state.quests.active.length>=5?'disabled':''}>Accept</button>`}</div>`).join(''):'<p>No notices remain. The clerk says this is a good sign, statistically speaking.</p>'}</section><button data-go="town">Back to town</button>`}
 if(screen==='store')body=`${header()}<p class="eyebrow">Town · General Store</p><h1 class="section-title">Supplies with receipts</h1><section class="panel"><p>Healing tonic · 8 gold each</p><p class="subtle">${state.town.gold} gold on hand</p><button data-action="buy" ${state.town.gold<8?'disabled':''}>Buy tonic</button></section><button data-go="town">Back to town</button>`;
 if(screen==='inn')body=`${header()}<p class="eyebrow">Town · The Inn</p><h1 class="section-title">The Lantern & Ledger</h1><section class="panel"><p>The room comes with a clean blanket and a form acknowledging that noises from below are not the innkeeper’s responsibility.</p><p>Rest costs 5 gold. Recover all health.</p><button data-action="rest" ${state.town.gold<5?'disabled':''}>Rest · 5 gold</button></section><button data-go="town">Back to town</button>`;
 if(screen==='character'){const inv=state.inventory.filter(i=>i.quantity>0);body=`${header()}<p class="eyebrow">Your paperwork</p><h1 class="section-title">Character & Inventory</h1><section class="panel">${stats()}<p>STR ${state.player.str} · AGI ${state.player.agi} · MND ${state.player.mind} · VIT ${state.player.vit} · ATK ${state.player.attack} · DEF ${state.player.defense} · MP ${state.player.mp}/${state.player.maxMp}</p></section><section class="panel"><h2>Carried items</h2>${inv.map(i=>`<p>${esc(items[i.id]?.name||i.id)} × ${i.quantity} <span class="subtle">${items[i.id]?.category||''}</span></p>`).join('')||'<p>Nothing carried.</p>'}</section><button data-go="town">Back to town</button>`}
 if(screen==='dungeon'){const d=state.dungeon, dirs=['North','East','South','West'],map=Array.from({length:49},(_,n)=>{const x=n%7,y=Math.floor(n/7),k=`${x},${y}`,seen=d.explored.includes(k),player=x===d.x&&y===d.y,stairs=x===d.map.stairs[0]&&y===d.map.stairs[1];return `<i class="cell ${seen?'seen':''} ${player?'player':''} ${stairs&&seen?'stairs':''}" title="${seen?`Cell ${x}, ${y}`:'Unexplored'}"></i>`}).join('');body=`${header()}<p class="eyebrow">Below town · Level ${d.floor}</p><h1 class="section-title">Stone, dust, and a draft</h1><div class="dungeon-layout"><section class="panel"><div class="scene"><p>${d.rat.alive?'Something scrapes out of sight.':'The corridor continues into the dark.'}</p></div><p class="log" id="log">${esc(message)}</p><div class="controls"><button class="up" data-move="forward" aria-label="Move forward">▲ Forward</button><button class="left" data-turn="-1" aria-label="Turn left">↶ Left</button><button class="down" data-move="back" aria-label="Move backward">▼ Back</button><button class="right" data-turn="1" aria-label="Turn right">Right ↷</button></div><p class="subtle">Facing ${dirs[d.facing]}. Each step takes a turn.</p><div class="actions"><button data-action="attack" ${!state.combat?'disabled':''}>Attack</button><button data-action="defend" ${!state.combat?'disabled':''}>Defend</button><button data-action="tonic">Use tonic</button><button data-action="find" ${d.x!==3||d.y!==4||d.lootTaken?'disabled':''}>Pick up</button></div><div class="row" style="margin-top:1rem"><button data-action="stairs" ${d.x!==d.map.stairs[0]||d.y!==d.map.stairs[1]?'disabled':''}>Climb to town</button><button class="quiet" data-action="retreat">Retreat to entrance</button></div></section><aside class="panel"><h2>Automap</h2><div class="map" aria-label="Explored dungeon map">${map}</div><p class="subtle">Gold shows your position. The revealed rust tile is the stair.</p><p>${stats()}</p></aside></div>`}
 if(screen==='combat'){/* kept for future dedicated combat view */}
 const qaPanel=qa?`<section class="panel qa"><p class="eyebrow">QA mode</p><div class="row"><button data-qa="heal">Heal</button><button data-qa="town">Return to town</button><button data-qa="reset">Reset save</button><button data-qa="rat">Test encounter</button><button data-qa="item">Give test items</button></div><details><summary>Inspect game state</summary><pre>${esc(JSON.stringify(state,null,2))}</pre></details></section>`:'';
 app.innerHTML=`<div class="shell">${body}${qaPanel}<p class="footer">MIRPWORKS · The town’s hole management office thanks you for your cooperation.</p></div>`;}
function go(s){if(s==='dungeon'&&!state.dungeon.inDungeon){enterDungeon()}screen=s;render()}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.go){go(b.dataset.go);return}if(b.dataset.quest){acceptQuest(b.dataset.quest);render();return}if(b.dataset.move){message=move(b.dataset.move);if(message.includes('blares')){screen='dungeon'}render();return}if(b.dataset.turn){turn(Number(b.dataset.turn));message='You turn '+(Number(b.dataset.turn)<0?'left':'right')+'.';render();return}const a=b.dataset.action;if(a==='new'){screen='create';render()}else if(a==='continue'){setState(loadState());town()}else if(a==='help'){modal.innerHTML=`<div class="title-screen"><section class="title-card"><p class="eyebrow">About / Help</p><h2>Careful steps. Sensible exits.</h2><p>This is an original turn-based dungeon crawler. In the dungeon, use the large controls or W/A/S/D and arrow keys. Left and right turn; forward and back move. Explore, collect, and return by stairs or retreat.</p><button data-action="close-help">Back</button></section></div>`}else if(a==='close-help'){modal.innerHTML=''}else if(a==='attack'){message=attack();render()}else if(a==='defend'){message=defend();render()}else if(a==='tonic'){message=useTonic();render()}else if(a==='find'){collectFind();message='You collect the lunchbox and a stone chip. Both are logged as recovered property.';render()}else if(a==='retreat'||a==='stairs'){returnTown();town()}else if(a==='buy'&&state.town.gold>=8){state.town.gold-=8;const i=state.inventory.find(i=>i.id==='healing-tonic');if(i)i.quantity++;else state.inventory.push({id:'healing-tonic',quantity:1});persist();render()}else if(a==='rest'&&state.town.gold>=5){state.town.gold-=5;state.player.hp=state.player.maxHp;persist();message='A full night’s rest. The hole is still open.';render()} });
app.addEventListener('submit',e=>{if(e.target.id==='create-form'){e.preventDefault();const f=new FormData(e.target);startGame(f.get('name'),f.get('class'));town()}});
modal.addEventListener('click',e=>{if(e.target.closest('[data-action="close-help"]'))modal.innerHTML=''});
app.addEventListener('click',e=>{const q=e.target.closest('[data-qa]')?.dataset.qa;if(!q)return;if(q==='heal')state.player.hp=state.player.maxHp;if(q==='town'){returnTown();town();return}if(q==='reset'){localStorage.removeItem(SAVE_KEY);setState(awaitFresh());title();return}if(q==='rat'){state.dungeon.inDungeon=true;state.dungeon.rat.alive=true;state.combat={enemy:'Dungeon Rat',hp:8,maxHp:8}}if(q==='item'){state.inventory.push({id:'healing-tonic',quantity:3},{id:'cave-salt',quantity:5})}persist();render()});
function awaitFresh(){return {saveVersion:1,player:null,inventory:[],equipment:{},town:{gold:25},quests:{active:[],completed:[],available:Object.keys(quests)},dungeon:{floor:1,x:1,y:5,facing:0,explored:['1,5'],visited:{'1':['1,5']},map:{width:7,height:7,walls:[],stairs:[5,1]},rat:{x:4,y:3,hp:8,alive:true},lootTaken:false},combat:null,settings:{},meta:{createdAt:Date.now(),updatedAt:Date.now()}}}
document.addEventListener('keydown',e=>{if(screen!=='dungeon'||e.target.matches('input,select,textarea'))return;const k=e.key.toLowerCase();if(['arrowup','w','arrowdown','s','arrowleft','a','arrowright','d'].includes(k)){e.preventDefault();if(k==='arrowleft'||k==='a')turn(-1);else if(k==='arrowright'||k==='d')turn(1);else message=move(k==='arrowdown'||k==='s'?'back':'forward');render()}});
const existing=loadState();if(existing){setState(existing);title()}else title();
