export const rarities={common:{label:'Common',weight:62},uncommon:{label:'Uncommon',weight:25},rare:{label:'Rare',weight:10},strange:{label:'Strange',weight:3}};

export const quests={
  'rat-problem':{id:'rat-problem',title:'Basement-level vermin',description:'Defeat the rat that has been chewing on the municipal depth markers.',giver:'Office of Subterranean Sanitation',type:'kill',target:'rat',count:1,reward:{gold:18,xp:8}},
  'lost-lunchbox':{id:'lost-lunchbox',title:'A lunchbox, technically public property',description:'Find the blue lunchbox left near the old stair.',giver:'Mara, Drainage Clerk',type:'loot',target:'lunchbox',count:1,reward:{gold:12,xp:6}},
  'stone-sample':{id:'stone-sample',title:'One representative rock',description:'Bring back a piece of anything that looks expensive to test.',giver:'Town Works Committee',type:'loot',target:'stone',count:1,reward:{gold:10,xp:5}},
  'goose-feather':{id:'goose-feather',title:'Feather, for the records',description:'Recover one feather from the goose population. Do not ask why.',giver:'Juniper Dunn',type:'loot',target:'goose-feather',count:1,reward:{gold:16,xp:8}},
  'earthworm-ember':{id:'earthworm-ember',title:'Warm sample',description:'Bring back an ember sac from a fire-breathing earthworm.',giver:'Town Works Committee',type:'loot',target:'earthworm-ember',count:1,reward:{gold:22,xp:12}},
  'depth-three':{id:'depth-three',title:'Confirm the lower stair exists',description:'Reach level 3, then make it back with your report.',giver:'Linna Venn, Notice-board clerk',type:'return',target:'3',count:1,reward:{gold:35,xp:20}}
  ,'camp-report':{id:'camp-report',title:'File the old camp report',description:'Bring the survey notes from the abandoned camp back to Linna.',giver:'Linna Venn, Notice-board clerk',type:'loot',target:'survey-notes',count:1,reward:{gold:18,xp:12}}
  ,'warm-wall-survey':{id:'warm-wall-survey',title:'Document the warm wall',description:'Record the warm wall’s location for the Works Committee.',giver:'Town Works Committee',type:'discover',target:'warm-wall',count:1,reward:{gold:14,xp:10}}
  ,'landmark-report':{id:'landmark-report',title:'File the stone-face report',description:'Confirm the giant stone face is on the lower survey map.',giver:'Linna Venn, Notice-board clerk',type:'discover',target:'giant-stone-face',count:1,reward:{gold:12,xp:8}}
};

export const monsters={
  rat:{id:'rat',name:'Dungeon Rat',minDepth:1,hp:8,attack:4,defense:0,speed:2,xp:4,gold:[2,4],rarity:'common',lootTable:'rat-drops',encounterText:'A municipal depth marker has fresh tooth marks.',behavior:{type:'plain',description:'Bites once.'}},
  kobold:{id:'kobold',name:'Kobold Toll-Taker',minDepth:1,hp:12,attack:4,defense:1,speed:2,xp:7,gold:[2,7],rarity:'common',lootTable:'kobold-drops',encounterText:'It has set up a toll booth with no road attached.',behavior:{type:'guard',description:'Ordinary attack; carries trade goods.'}},
  killerRabbit:{id:'killer-rabbit',name:'Killer Rabbit',minDepth:1,hp:11,attack:6,defense:1,speed:4,xp:8,gold:[1,4],rarity:'uncommon',lootTable:'rabbit-drops',encounterText:'It looks harmless. It is not waiting for you to decide.',behavior:{type:'critical',criticalChance:.22,description:'Sometimes lands a hard bite.'}},
  kungFuGoose:{id:'kung-fu-goose',name:'Kung Fu Goose',minDepth:1,hp:10,attack:3,defense:1,speed:5,xp:9,gold:[0,3],rarity:'uncommon',lootTable:'goose-drops',encounterText:'The goose bows. The bow appears tactical.',behavior:{type:'quick',multiStrike:2,evadeChance:.12,description:'Two light strikes; may evade.'}},
  pocketSlime:{id:'pocket-slime',name:'Pocket Slime',minDepth:1,hp:13,attack:3,defense:1,speed:1,xp:7,gold:[0,2],rarity:'common',lootTable:'slime-drops',encounterText:'A blob attempts to fit inside your boot.',behavior:{type:'plain',description:'Slow, steady attacks.'}},
  fireWorm:{id:'fire-worm',name:'Fire-Breathing Earthworm',minDepth:2,hp:18,attack:5,defense:2,speed:1,xp:15,gold:[4,9],rarity:'uncommon',lootTable:'worm-drops',encounterText:'A length of earthworm inhales. The earth glows.',behavior:{type:'burn',burnChance:.35,burnTurns:2,description:'May leave a brief burn.'}},
  skeleton:{id:'skeleton',name:'Skeleton on Break',minDepth:2,hp:18,attack:6,defense:2,speed:2,xp:16,gold:[4,10],rarity:'common',lootTable:'skeleton-drops',encounterText:'A skeleton checks a pocket watch. It has no pockets.',behavior:{type:'plain',description:'A sturdy, ordinary fighter.'}},
  paperMimic:{id:'paper-mimic',name:'Permit-Office Mimic',minDepth:3,hp:25,attack:7,defense:3,speed:2,xp:26,gold:[8,16],rarity:'rare',lootTable:'mimic-drops',encounterText:'The filing cabinet has too many teeth.',behavior:{type:'critical',criticalChance:.15,description:'Heavy strikes from a convincing cabinet.'}}
};

const attackSets={
  rat:[['nibble','Nibble',2,4,.68,'A suspiciously confident nibble.'],['lunge','Lunge',3,5,.32,'The rat lunges with municipal purpose.']],
  kobold:[['toll-club','Tolling bonk',2,5,.72,'The kobold demands payment in bruises.'],['pocket-sand','Pocket sand',3,6,.28,'A handful of grit arrives with surprising force.']],
  killerRabbit:[['scratch','Scratch',3,6,.76,'The rabbit scratches with alarming focus.'],['leap','Throatward leap',5,7,.24,'The rabbit launches itself at your neck.']],
  kungFuGoose:[['wing-slap','Wing slap',1,3,.7,'A wing catches you on the shoulder.'],['flying-kick','Flying kick',3,5,.3,'The goose delivers a perfectly committed kick.']],
  pocketSlime:[['ooze','Ooze bump',1,4,.8,'The slime bumps you with damp determination.'],['splorch','Splorch',2,5,.2,'The slime splorches directly into your boots.']],
  fireWorm:[['bite','Bite',3,6,.7,'The earthworm bites down.'],['flame-belch','Flame belch',4,7,.3,'The earthworm exhales a tiny, furious flame.']],
  skeleton:[['rattle','Rattling swipe',3,6,.72,'The skeleton swipes with a loose bone.'],['clipboard','Clipboard smack',4,7,.28,'A clipboard appears from nowhere.']],
  paperMimic:[['snap','Cabinet snap',4,7,.76,'The filing cabinet snaps shut on you.'],['forms','Paperwork avalanche',5,8,.24,'A stack of forms hits like a brick.']]
};
for(const [id,m] of Object.entries(monsters)){m.attacks=attackSets[id].map(([attackId,name,minDamage,maxDamage,weight,flavor])=>({id:attackId,name,minDamage,maxDamage,accuracy:.94,weight,flavor,...(id==='fireWorm'&&attackId==='flame-belch'?{effect:'burn',effectChance:.45,effectTurns:2}:{})}));m.sprite={src:`assets/monsters/${m.id}.svg`,scale:1,offsetY:0}}
// These two user-drawn designs keep their stable IDs for existing saves and quest references.
monsters.kungFuGoose.name='Kung Fungoose';
monsters.kungFuGoose.sprite={src:'assets/images/enemies/kung-fungoose.png',scale:1.12,offsetY:-1};
monsters.rat.name='Deadly Rat';
monsters.rat.sprite={src:'assets/images/enemies/deadly-rat.png',scale:1.08,offsetY:1};

export const items={
  'rusty-sword':{id:'rusty-sword',name:'Rusty Sword',category:'equipment',slot:'mainHand',rarity:'common',buyValue:12,sellValue:5,modifiers:{attack:2},flavor:'The rust is mostly decorative. Probably.',stackable:false},
  'patched-coat':{id:'patched-coat',name:'Patched Coat',category:'equipment',slot:'body',rarity:'common',buyValue:10,sellValue:4,modifiers:{defense:1,hp:2},flavor:'One patch is an official town map.',stackable:false},
  'wooden-shield':{id:'wooden-shield',name:'Wooden Shield',category:'equipment',slot:'offHand',rarity:'common',buyValue:18,sellValue:8,modifiers:{defense:2},flavor:'It has been tested against doors.',stackable:false},
  'leather-armor':{id:'leather-armor',name:'Leather Armor',category:'equipment',slot:'body',rarity:'common',buyValue:28,sellValue:12,modifiers:{defense:2,hp:3},flavor:'Practical, if a little damp.',stackable:false},
  'reinforced-boots':{id:'reinforced-boots',name:'Reinforced Boots',category:'equipment',slot:'feet',rarity:'common',buyValue:20,sellValue:8,modifiers:{defense:1,agility:1},flavor:'The stairs have opinions about footwear.',stackable:false},
  'apprentice-staff':{id:'apprentice-staff',name:'Apprentice Staff',category:'equipment',slot:'mainHand',rarity:'uncommon',buyValue:38,sellValue:16,modifiers:{attack:1,mind:1,mp:3},classes:['Wizard','Cleric'],flavor:'It knows three spells and one of them is a knock.',stackable:false},
  'goose-proof-helmet':{id:'goose-proof-helmet',name:'Goose-Proof Helmet',category:'equipment',slot:'head',rarity:'uncommon',buyValue:32,sellValue:14,modifiers:{defense:1,agility:1},effects:{vsGoose:2},flavor:'The warranty is very specific.',stackable:false},
  'questionable-luck':{id:'questionable-luck',name:'Ring of Questionable Luck',category:'equipment',slot:'accessory',rarity:'strange',buyValue:48,sellValue:20,modifiers:{agility:1},effects:{lootBonus:.08},flavor:'The ring insists that the odds are excellent.',stackable:false},
  'heavy-spoon':{id:'heavy-spoon',name:'Extremely Heavy Spoon',category:'equipment',slot:'mainHand',rarity:'common',buyValue:14,sellValue:5,modifiers:{attack:3,agility:-1},flavor:'Designed for soup of unusual density.',stackable:false},
  'fireproof-trousers':{id:'fireproof-trousers',name:'Pants of Minor Fire Resistance',category:'equipment',slot:'body',rarity:'uncommon',buyValue:36,sellValue:15,modifiers:{defense:1},effects:{fireResistance:2},flavor:'Minor resistance. Major tailoring.',stackable:false},
  'kobold-buckler':{id:'kobold-buckler',name:'Kobold-Chewed Buckler',category:'equipment',slot:'offHand',rarity:'uncommon',buyValue:30,sellValue:13,modifiers:{defense:1},effects:{retreatBonus:10},flavor:'The bite marks are now considered reinforcement.',stackable:false},
  'squeaky-boots':{id:'squeaky-boots',name:'Boots That Squeak Near Treasure',category:'equipment',slot:'feet',rarity:'strange',buyValue:42,sellValue:17,modifiers:{agility:1},effects:{lootBonus:.12},flavor:'They squeak only when you would prefer they did not.',stackable:false},
  'healing-tonic':{id:'healing-tonic',name:'Healing Tonic',category:'consumable',rarity:'common',buyValue:8,sellValue:3,effect:{type:'heal',amount:8},flavor:'Tastes faintly of mint and paperwork.',stackable:true},
  'cave-salt':{id:'cave-salt',name:'Cave Salt',category:'trade-good',rarity:'common',buyValue:4,sellValue:2,flavor:'Useful to someone, apparently.',stackable:true},
  'suspicious-mushroom':{id:'suspicious-mushroom',name:'Suspicious Mushroom',category:'trade-good',rarity:'common',buyValue:5,sellValue:2,flavor:'The mushroom is being cagey.',stackable:true},
  'goose-feather':{id:'goose-feather',name:'Goose Feather',category:'trade-good',rarity:'uncommon',buyValue:7,sellValue:3,flavor:'It has a remarkably stern quill.',stackable:true},
  'earthworm-ember':{id:'earthworm-ember',name:'Earthworm Ember Sac',category:'trade-good',rarity:'uncommon',buyValue:10,sellValue:4,flavor:'Warm. Do not squeeze.',stackable:true},
  'kobold-trinket':{id:'kobold-trinket',name:'Kobold Trinket',category:'trade-good',rarity:'common',buyValue:6,sellValue:3,flavor:'The exchange rate is known only to kobolds.',stackable:true},
  'blue-lunchbox':{id:'blue-lunchbox',name:'Blue Lunchbox',category:'quest',rarity:'common',buyValue:0,sellValue:0,questItem:true,stackable:false,flavor:'Name scratched underneath: “Mara.”'},
  'stone-chip':{id:'stone-chip',name:'Unremarkable Stone Chip',category:'quest',rarity:'common',buyValue:0,sellValue:0,questItem:true,stackable:false,flavor:'The committee will be thrilled.'},
  'bent-spoon':{id:'bent-spoon',name:'Bent Spoon',category:'junk',rarity:'common',buyValue:2,sellValue:1,flavor:'No longer suitable for formal soup.',stackable:true}
  ,'kobold-pie':{id:'kobold-pie',name:'Kobold Bake-Sale Pie',category:'consumable',rarity:'uncommon',buyValue:6,sellValue:2,effect:{type:'buff',name:'defense',value:1,encounters:2},flavor:'Warm, flaky, and lightly defensive.',stackable:true}
  ,'survey-notes':{id:'survey-notes',name:'Survey Notes',category:'quest',rarity:'common',buyValue:0,sellValue:0,questItem:true,stackable:false,flavor:'Careful handwriting. The margins mention a duck.'}
};

export const lootTables={
  'rat-drops':[{item:'cave-salt',weight:4},{item:'suspicious-mushroom',weight:2},{item:'bent-spoon',weight:1}],
  'kobold-drops':[{item:'kobold-trinket',weight:4},{item:'cave-salt',weight:2},{item:'wooden-shield',weight:1}],
  'rabbit-drops':[{item:'suspicious-mushroom',weight:3},{item:'reinforced-boots',weight:1},{item:'goose-proof-helmet',weight:1}],
  'goose-drops':[{item:'goose-feather',weight:5},{item:'goose-proof-helmet',weight:1},{item:'questionable-luck',weight:1}],
  'slime-drops':[{item:'cave-salt',weight:3},{item:'suspicious-mushroom',weight:3},{item:'healing-tonic',weight:1}],
  'worm-drops':[{item:'earthworm-ember',weight:5},{item:'fireproof-trousers',weight:1},{item:'heavy-spoon',weight:1}],
  'skeleton-drops':[{item:'kobold-trinket',weight:2},{item:'wooden-shield',weight:2},{item:'leather-armor',weight:1}],
  'mimic-drops':[{item:'heavy-spoon',weight:2},{item:'squeaky-boots',weight:2},{item:'apprentice-staff',weight:1}]
};

export const townNpcs={
  clerk:{name:'Linna Venn',role:'Notice-board clerk',line:'I file the quests by depth. The hole files nothing.'},
  shopkeeper:{name:'Juniper Dunn',role:'General-store keeper',line:'If it came up from below, I can probably price it.'},
  innkeeper:{name:'Sal Morrow',role:'Innkeeper',line:'Rooms are quiet. The ground floor is quietest.'}
};

export const dungeonNpcs={
  'kobold-trader':{id:'kobold-trader',name:'Pip Underledger',role:'Wandering kobold merchant',line:'Gold is fine. Odd things are better. I have a ledger for both.',tradeIds:['salt-for-buckler','mushroom-goose-deal']},
  'lost-surveyor':{id:'lost-surveyor',name:'Nell from Municipal Survey',role:'Lost adventurer',line:'I came to measure the stairs. I have been measuring for three days.',stock:['healing-tonic'],priceMultiplier:2}
};

export const trades={
  'salt-for-buckler':{id:'salt-for-buckler',npcId:'kobold-trader',title:'Trade cave salt for a buckler',gives:[{item:'kobold-buckler',quantity:1}],requires:[{item:'cave-salt',quantity:2}],gold:4},
  'mushroom-goose-deal':{id:'mushroom-goose-deal',npcId:'kobold-trader',title:'Three mushrooms and one goose feather for a heavy spoon',gives:[{item:'heavy-spoon',quantity:1}],requires:[{item:'suspicious-mushroom',quantity:3},{item:'goose-feather',quantity:1}],gold:20}
};

export const shopStock=['healing-tonic','rusty-sword','wooden-shield','leather-armor','reinforced-boots','apprentice-staff','goose-proof-helmet','fireproof-trousers'];
export const npcEncounterIds=['kobold-trader','lost-surveyor'];
export const floorEncounterTable={
  1:[{id:'rat',weight:3},{id:'kobold',weight:2},{id:'killerRabbit',weight:2},{id:'kungFuGoose',weight:2},{id:'pocketSlime',weight:3}],
  2:[{id:'rat',weight:1},{id:'kobold',weight:2},{id:'killerRabbit',weight:2},{id:'kungFuGoose',weight:2},{id:'pocketSlime',weight:2},{id:'fireWorm',weight:3},{id:'skeleton',weight:3}],
  3:[{id:'killerRabbit',weight:2},{id:'kungFuGoose',weight:2},{id:'fireWorm',weight:3},{id:'skeleton',weight:3},{id:'paperMimic',weight:2}]
};

export const roomTypes={
  'mushroom-room':{id:'mushroom-room',name:'Mushroom Room',weight:14,description:'Pale mushrooms have claimed the damp corners.'},
  'flooded-chamber':{id:'flooded-chamber',name:'Flooded Chamber',weight:8,description:'A shallow sheet of water covers the stone.'},
  shrine:{id:'shrine',name:'Shrine',weight:8,description:'Someone left a candle stub and a receipt.'},
  storage:{id:'storage',name:'Storage Room',weight:13,description:'Crates are stacked with municipal confidence.'},
  camp:{id:'camp',name:'Abandoned Camp',weight:8,description:'A cold fire ring sits under a dry patch of ceiling.'},
  market:{id:'market',name:'Kobold Market',weight:5,minDepth:2,description:'A chalk price list is nailed to the wall.'},
  library:{id:'library',name:'Library',weight:7,minDepth:2,description:'The shelves contain books and one labeled stone.'},
  records:{id:'records',name:'Municipal Records Room',weight:5,minDepth:2,description:'The forms are sorted by year, then by dampness.'},
  spoons:{id:'spoons',name:'Room Full of Spoons',weight:2,description:'The floor is covered in spoons.'},
  ordinary:{id:'ordinary',name:'Stone Passage',weight:30,description:'A plain stone passage continues.'}
};

// Choices and consequences stay in content data. game.js resolves only these small outcome primitives.
export const dungeonEvents={
  'vending-machine':{id:'vending-machine',weirdness:.55,title:'The Vending Machine',type:'Strange Object',minDepth:1,weight:7,rooms:['storage','records'],description:'A clean, ordinary vending machine is fitted into the stone wall. Its display reads: PLEASE MAKE A SELECTION.',repeatable:true,cooldown:7,choices:[{id:'buy',label:'Buy a tonic · 8 gold',requiresGold:8,outcomes:[{type:'gold',amount:-8},{type:'item',item:'healing-tonic',quantity:1},{type:'message',text:'The machine dispenses a tonic and prints a receipt dated tomorrow.'},{type:'townReaction',text:'Linna asks what a vending machine is. Then she files the receipt.'}]},{id:'shake',label:'Shake it',outcomes:[{type:'random',outcomes:[{weight:3,outcomes:[{type:'damage',amount:2},{type:'message',text:'A can falls out. It is dented but unopened.'}]},{weight:2,outcomes:[{type:'item',item:'bent-spoon',quantity:1},{type:'message',text:'A bent spoon drops into the coin return.'}]},{weight:1,outcomes:[{type:'damage',amount:3},{type:'message',text:'The machine shakes back.'}]}]}]},{id:'inspect',label:'Inspect the label',outcomes:[{type:'flag',flag:'vending-inspected'},{type:'message',text:'The manufacturer field reads: MUNICIPAL PROPERTY. The serial number is a date.'}]},{id:'leave',label:'Leave it alone',outcomes:[{type:'message',text:'The machine hums at a polite volume.'}]}]},
  'comfortable-chair':{id:'comfortable-chair',title:'The Extremely Comfortable Chair',type:'Rest Opportunity',minDepth:1,weight:6,rooms:['storage','shrine'],description:'A velvet chair sits alone in a stone chamber. It looks recently dusted.',repeatable:false,choices:[{id:'sit',label:'Sit down',outcomes:[{type:'random',outcomes:[{weight:3,outcomes:[{type:'heal',amount:6},{type:'message',text:'You rest. The chair supports you without asking questions.'}]},{weight:2,outcomes:[{type:'effect',name:'defense',value:2,encounters:2},{type:'message',text:'The chair’s excellent posture stays with you for two encounters.'}]},{weight:1,outcomes:[{type:'message',text:'You sit for a moment. Nothing happens. It is still a very good chair.'}]}]}]},{id:'inspect',label:'Inspect the upholstery',outcomes:[{type:'item',item:'cave-salt',quantity:1},{type:'message',text:'There is cave salt in one cushion. This may be a maintenance issue.'}]},{id:'leave',label:'Leave it alone',outcomes:[{type:'message',text:'The chair remains comfortable-looking.'}]}]},
  'suspicious-chest':{id:'suspicious-chest',title:'The Suspicious Chest',type:'Treasure',minDepth:1,weight:7,rooms:['storage'],description:'A chest sits directly in the middle of the room. The ceiling above it has a fresh crack.',repeatable:false,choices:[{id:'open',label:'Open it carefully',warning:'The cracked ceiling may shift.',outcomes:[{type:'random',outcomes:[{weight:3,outcomes:[{type:'gold',amount:9},{type:'item',item:'kobold-trinket',quantity:1},{type:'message',text:'The chest contains coins and a very small ledger.'}]},{weight:2,outcomes:[{type:'damage',amount:3},{type:'message',text:'A stone chip clips your shoulder as the lid opens.'}]},{weight:1,outcomes:[{type:'encounter',monster:'paper-mimic'},{type:'message',text:'The chest unfolds several filing-cabinet teeth.'}]}]}]},{id:'inspect',label:'Inspect the supports',outcomes:[{type:'flag',flag:'chest-inspected'},{type:'message',text:'The crack is old and the chest has no hinges on the inside. You leave it for now.'}]},{id:'leave',label:'Leave it',outcomes:[{type:'message',text:'The chest stays in the middle of the room, where it can be seen.'}]}]},
  'kobold-bake-sale':{id:'kobold-bake-sale',title:'Kobold Bake Sale',type:'Merchant',minDepth:1,weight:5,rooms:['market'],description:'Two kobolds have arranged pastries on a folding table. A handwritten sign says FUNDS FOR TUNNEL LIGHTING.',repeatable:true,cooldown:8,choices:[{id:'buy-pie',label:'Buy a pie · 6 gold',requiresGold:6,outcomes:[{type:'gold',amount:-6},{type:'item',item:'kobold-pie',quantity:1},{type:'message',text:'The pie is warm and grants a little extra defense for two fights.'}]},{id:'barter',label:'Trade one cave salt for a pie',requiresItem:{item:'cave-salt',quantity:1},outcomes:[{type:'removeItem',item:'cave-salt',quantity:1},{type:'item',item:'kobold-pie',quantity:1},{type:'message',text:'The kobolds inspect the salt, nod, and wrap a pie.'}]},{id:'ask',label:'Ask about the lighting fund',outcomes:[{type:'townReaction',text:'Juniper says the kobolds have been submitting receipts for tunnel lighting.'},{type:'message',text:'“The lighting is a separate budget,” says the smaller kobold.'}]},{id:'leave',label:'Leave the sale',outcomes:[{type:'message',text:'They resume arranging the pastries by diameter.'}]}]},
  'room-of-spoons':{id:'room-of-spoons',weirdness:.25,title:'The Room Full of Spoons',type:'Discovery',minDepth:1,weight:4,rooms:['spoons'],description:'Hundreds of spoons cover the floor. They are all facing the same direction.',repeatable:false,choices:[{id:'take',label:'Take one spoon',outcomes:[{type:'item',item:'bent-spoon',quantity:1},{type:'message',text:'You take a bent spoon. The others remain aligned.'}]},{id:'count',label:'Count them',outcomes:[{type:'flag',flag:'spoons-counted'},{type:'message',text:'You lose count at 214. The next spoon is labeled 216.'}]},{id:'leave',label:'Leave',outcomes:[{type:'message',text:'The spoons remain where they are.'}]}]},
  'lost-adventurer':{id:'lost-adventurer',title:'Lost Adventurer',type:'NPC',minDepth:1,weight:4,rooms:['camp','records'],description:'A tired delver insists they have been underground for twenty minutes. Their beard has a small bird nesting in it.',repeatable:false,choices:[{id:'offer-tonic',label:'Offer a healing tonic',requiresItem:{item:'healing-tonic',quantity:1},outcomes:[{type:'removeItem',item:'healing-tonic',quantity:1},{type:'gold',amount:5},{type:'townReaction',text:'Sal says someone returned from the hole with a bird in their beard. He does not ask follow-up questions.'},{type:'message',text:'They accept the tonic and give you five gold. “I will find the entrance soon.”'}]},{id:'ask',label:'Ask for directions',outcomes:[{type:'unlockQuest',quest:'warm-wall-survey'},{type:'message',text:'They point toward the warm wall and say it was not there yesterday.'}]},{id:'leave',label:'Leave them be',outcomes:[{type:'message',text:'They wave at a corridor that leads back the way you came.'}]}]},
  'very-small-door':{id:'very-small-door',weirdness:.7,title:'A Very Small Door',type:'Mystery',minDepth:1,weight:5,rooms:['library','records'],description:'A painted door, about as tall as a loaf of bread, is set into the wall.',repeatable:false,choices:[{id:'knock',label:'Knock twice',outcomes:[{type:'flag',flag:'small-door-knocked'},{type:'message',text:'Something on the other side knocks once, then moves a chair.'}]},{id:'listen',label:'Listen',outcomes:[{type:'message',text:'You hear a kettle being set down. No one opens the door.'}]},{id:'leave-item',label:'Leave a mushroom',requiresItem:{item:'suspicious-mushroom',quantity:1},outcomes:[{type:'removeItem',item:'suspicious-mushroom',quantity:1},{type:'message',text:'When you look again, the mushroom is gone. A tiny paper receipt remains.'}]},{id:'leave',label:'Leave',outcomes:[{type:'message',text:'The small door remains closed.'}]}]},
  'snack-stand':{id:'snack-stand',weirdness:.45,title:'Underground Snack Stand',type:'Merchant',minDepth:2,weight:5,rooms:['market','storage'],description:'A snack stand is open under a hand-painted sign: HOT FOOD · EXACT CHANGE PREFERRED.',repeatable:true,cooldown:6,choices:[{id:'buy',label:'Buy a tonic · 15 gold',requiresGold:15,outcomes:[{type:'gold',amount:-15},{type:'item',item:'healing-tonic',quantity:1},{type:'message',text:'The tonic is chilled. The stand owner says this is the premium service.'}]},{id:'look',label:'Read the menu',outcomes:[{type:'message',text:'Today’s special is “food”. The price is listed as market conditions.'}]},{id:'leave',label:'Leave',outcomes:[{type:'message',text:'The cook wipes a clean counter.'}]}]},
  'warm-wall':{id:'warm-wall',title:'The Warm Wall',type:'Hazard',minDepth:1,weight:6,rooms:['flooded-chamber','storage','ordinary'],description:'A section of stone is warm to the touch. A thin orange line glows between two blocks.',repeatable:false,choices:[{id:'investigate',label:'Investigate the seam',warning:'Heat is escaping through the stone.',outcomes:[{type:'random',outcomes:[{weight:3,outcomes:[{type:'item',item:'earthworm-ember',quantity:1},{type:'discover',landmark:'warm-wall',label:'Warm Wall',icon:'≈'},{type:'questProgress',questType:'discover',target:'warm-wall'},{type:'unlockQuest',quest:'warm-wall-survey'},{type:'townReaction',text:'Linna has added “warm wall” to the inspection form. She has added a checkbox for “still warm”.'},{type:'message',text:'The seam opens onto a warm pocket in the rock. Something left an ember sac behind.'}]},{weight:2,outcomes:[{type:'damage',amount:3},{type:'discover',landmark:'warm-wall',label:'Warm Wall',icon:'≈'},{type:'message',text:'A puff of hot air singes you. The wall cools again.'}]},{weight:1,outcomes:[{type:'encounter',monster:'fireWorm'},{type:'message',text:'The wall exhales, then a fire-breathing earthworm follows.'}]}]}]},{id:'feel',label:'Feel the stone carefully',outcomes:[{type:'effect',name:'fireResistance',value:1,encounters:2},{type:'message',text:'The heat is mild. You learn where to put your hand for two encounters.'}]},{id:'leave',label:'Leave it',outcomes:[{type:'message',text:'The orange line remains visible as you go.'}]}]},
  'inspection-notice':{id:'inspection-notice',title:'Municipal Inspection Notice',type:'Environmental',minDepth:1,weight:5,rooms:['records','library'],description:'An official notice is pinned to the stone: “Please report stair irregularities to the nearest office.”',repeatable:false,choices:[{id:'read',label:'Read the fine print',outcomes:[{type:'item',item:'survey-notes',quantity:1},{type:'townReaction',text:'Linna says the notice was filed correctly, though no one remembers posting it.'},{type:'message',text:'The notice refers to an inspection scheduled for three years ago.'}]},{id:'remove',label:'Take the notice down',outcomes:[{type:'item',item:'survey-notes',quantity:1},{type:'flag',flag:'notice-removed'},{type:'message',text:'The back is a map of stairs that do not appear on your map.'}]},{id:'leave',label:'Leave it posted',outcomes:[{type:'message',text:'The notice remains posted in accordance with policy.'}]}]},
  'abandoned-camp':{id:'abandoned-camp',title:'Abandoned Camp',type:'Discovery',minDepth:1,weight:6,rooms:['camp'],description:'A small camp is tucked behind a fallen screen. The kettle is cold; a set of careful survey notes is dry.',repeatable:false,choices:[{id:'search',label:'Search the supplies',outcomes:[{type:'item',item:'healing-tonic',quantity:1},{type:'item',item:'survey-notes',quantity:1},{type:'unlockQuest',quest:'camp-report'},{type:'townReaction',text:'Linna recognizes the survey notes and adds a report to the notice board.'},{type:'message',text:'You recover a tonic and survey notes. Someone packed in a hurry, but neatly.'}]},{id:'read',label:'Read the notes here',outcomes:[{type:'flag',flag:'camp-notes-read'},{type:'unlockQuest',quest:'camp-report'},{type:'message',text:'The notes mention a stair inspection and a duck seen near the records room.'}]},{id:'leave',label:'Leave camp undisturbed',outcomes:[{type:'message',text:'The camp remains dry and undisturbed.'}]}]},
  'talking-statue':{id:'talking-statue',weirdness:.5,title:'Talking Statue',type:'Mystery',minDepth:2,weight:3,rooms:['shrine'],description:'A stone face asks, “Do you have a little salt?” Its expression does not change.',repeatable:false,choices:[{id:'give-salt',label:'Give one cave salt',requiresItem:{item:'cave-salt',quantity:1},outcomes:[{type:'removeItem',item:'cave-salt',quantity:1},{type:'heal',amount:4},{type:'message',text:'“Thank you,” says the statue. It sounds relieved.'}]},{id:'ask',label:'Ask why',outcomes:[{type:'message',text:'“Soup,” it says. The statue has no mouth movement.'}]},{id:'leave',label:'Leave',outcomes:[{type:'message',text:'The statue returns to not speaking.'}]}]},
  'wishing-well':{id:'wishing-well',weirdness:.4,title:'Underground Wishing Well',type:'Choice',minDepth:1,weight:4,rooms:['flooded-chamber','shrine'],description:'A stone well is set into the floor. The water reflects a sky you cannot see.',repeatable:false,choices:[{id:'wish',label:'Throw in 3 gold',requiresGold:3,outcomes:[{type:'gold',amount:-3},{type:'random',outcomes:[{weight:3,outcomes:[{type:'gold',amount:7},{type:'message',text:'A coin lands back in your palm. It is from a town that no longer exists.'}]},{weight:2,outcomes:[{type:'effect',name:'attack',value:1,encounters:2},{type:'message',text:'The water ripples. You feel unusually certain for two encounters.'}]},{weight:2,outcomes:[{type:'message',text:'The well accepts the coin and offers no comment.'}]}]}]},{id:'retrieve',label:'Retrieve a visible coin',outcomes:[{type:'gold',amount:1},{type:'flag',flag:'well-retrieved'},{type:'message',text:'You retrieve one coin. The reflection looks briefly disappointed.'}]},{id:'leave',label:'Leave it',outcomes:[{type:'message',text:'The water remains still.'}]}]},
  'the-duck':{id:'the-duck',weirdness:.35,title:'The Duck',type:'Discovery',minDepth:1,weight:6,rooms:['flooded-chamber','ordinary'],description:'There is a duck standing in the corridor. It seems to have been expecting you.',repeatable:false,choices:[{id:'greet',label:'Greet the duck',outcomes:[{type:'flag',flag:'duck-greeted'},{type:'message',text:'The duck nods once and walks through a wall.'}]},{id:'offer',label:'Offer it a mushroom',requiresItem:{item:'suspicious-mushroom',quantity:1},outcomes:[{type:'removeItem',item:'suspicious-mushroom',quantity:1},{type:'effect',name:'retreatBonus',value:8,encounters:2},{type:'message',text:'The duck accepts the mushroom. You feel lighter on your feet for two encounters.'}]},{id:'leave',label:'Leave it alone',outcomes:[{type:'message',text:'The duck stays where it is, watching the corridor.'}]}]},
  'collapsed-passage':{id:'collapsed-passage',title:'Collapsed Passage',type:'Hazard',minDepth:2,weight:4,rooms:['storage','flooded-chamber'],description:'Loose stones block a side passage. The ceiling above them looks stable, but only just.',repeatable:false,choices:[{id:'clear',label:'Try to clear it',warning:'You may scrape yourself on the stone.',outcomes:[{type:'skillCheck',stat:'str',threshold:5,success:[{type:'item',item:'kobold-trinket',quantity:1},{type:'flag',flag:'passage-cleared'},{type:'message',text:'You clear a narrow gap and find a kobold trinket.'}],failure:[{type:'damage',amount:2},{type:'message',text:'The stones shift. You stop before the ceiling follows.'}]}]},{id:'shield',label:'Brace the stones with a shield',requiresItem:{item:'wooden-shield',quantity:1},outcomes:[{type:'item',item:'kobold-trinket',quantity:1},{type:'flag',flag:'passage-cleared'},{type:'message',text:'Your shield props up the loose slab. A small gap opens onto a kobold trinket.'}]},{id:'leave',label:'Leave the passage',outcomes:[{type:'message',text:'The main corridor remains open.'}]}]},
  'giant-stone-face':{id:'giant-stone-face',title:'A Giant Stone Face',type:'Landmark',minDepth:1,weight:2,weirdness:.75,rooms:['ordinary','library'],description:'A giant face is carved into the far wall. Its eyes are looking at an adjacent wall.',repeatable:false,choices:[{id:'record',label:'Record the landmark',outcomes:[{type:'discover',landmark:'giant-stone-face',label:'Stone Face',icon:'◉'},{type:'questProgress',questType:'discover',target:'giant-stone-face'},{type:'unlockQuest',quest:'landmark-report'},{type:'townReaction',text:'Linna asks whether the stone face has a permit. She makes a note to check.'},{type:'message',text:'The face is recorded on your map. The other wall remains its focus.'}]},{id:'ask',label:'Ask it a question',outcomes:[{type:'message',text:'The face does not answer. It continues looking at the wall.'}]},{id:'leave',label:'Leave',outcomes:[{type:'message',text:'The face stays carved into the wall.'}]}]},
  'sleeping-slime':{id:'sleeping-slime',title:'A Sleeping Pocket Slime',type:'Creature',minDepth:1,weight:5,rooms:['mushroom-room','storage'],description:'A pocket slime is asleep beside a dry boot. It does not seem hostile.',repeatable:false,choices:[{id:'sneak',label:'Sneak past',outcomes:[{type:'message',text:'You step quietly around it. The slime snores once.'}]},{id:'inspect',label:'Inspect the boot',outcomes:[{type:'item',item:'cave-salt',quantity:1},{type:'message',text:'There is cave salt in the boot. The slime remains asleep.'}]},{id:'attack',label:'Attack the slime',warning:'It will wake up angry.',outcomes:[{type:'encounter',monster:'pocketSlime'},{type:'message',text:'The slime wakes and bounces toward you.'}]}]}
};
