export const rarities={common:{label:'Common',weight:62},uncommon:{label:'Uncommon',weight:25},rare:{label:'Rare',weight:10},strange:{label:'Strange',weight:3}};

export const quests={
  'rat-problem':{id:'rat-problem',chain:'Municipal Depth Markers',step:1,title:'Basement-level vermin',description:'Defeat the rat that has been chewing on the municipal depth markers.',giver:'Office of Subterranean Sanitation',type:'kill',target:'rat',count:1,reward:{gold:18,xp:8},next:'marker-followup'},
  'lost-lunchbox':{id:'lost-lunchbox',title:'A lunchbox, technically public property',description:'Find the blue lunchbox left near the old stair.',giver:'Mara, Drainage Clerk',type:'loot',target:'lunchbox',count:1,turnInItems:[{id:'blue-lunchbox',quantity:1,consume:true}],reward:{gold:12,xp:6}},
  'stone-sample':{id:'stone-sample',title:'One representative rock',description:'Bring back a piece of anything that looks expensive to test.',giver:'Town Works Committee',type:'loot',target:'stone',count:1,turnInItems:[{id:'stone-chip',quantity:1,consume:true}],reward:{gold:10,xp:5}},
  'goose-feather':{id:'goose-feather',title:'Feather, for the records',description:'Recover one feather from the goose population. Do not ask why.',giver:'Juniper Dunn',type:'loot',target:'goose-feather',count:1,turnInItems:[{id:'goose-feather',quantity:1,consume:true}],reward:{gold:16,xp:8}},
  'earthworm-ember':{id:'earthworm-ember',title:'Warm sample',description:'Bring back an ember sac from a fire-breathing earthworm.',giver:'Town Works Committee',type:'loot',target:'earthworm-ember',count:1,turnInItems:[{id:'earthworm-ember',quantity:1,consume:true}],reward:{gold:22,xp:12}},
  'depth-three':{id:'depth-three',title:'Confirm the lower stair exists',description:'Reach level 3, then make it back with your report.',giver:'Linna Venn, Notice-board clerk',type:'return',target:'3',count:1,reward:{gold:35,xp:20}}
  ,'camp-report':{id:'camp-report',chain:'Missing Survey Crew',step:1,title:'File the old camp report',description:'Bring the survey notes from the abandoned camp back to Linna.',giver:'Linna Venn, Notice-board clerk',type:'loot',target:'survey-notes',count:1,turnInItems:[{id:'survey-notes',quantity:1,consume:true}],reward:{gold:18,xp:12},next:'crew-followup'}
  ,'warm-wall-survey':{id:'warm-wall-survey',chain:'The Warm Wall',step:1,title:'Document the warm wall',description:'Record the warm wall’s location for the Works Committee.',giver:'Town Works Committee',type:'discover',target:'warm-wall',count:1,reward:{gold:14,xp:10},next:'warm-wall-sample'}
  ,'landmark-report':{id:'landmark-report',title:'File the stone-face report',description:'Confirm the giant stone face is on the lower survey map.',giver:'Linna Venn, Notice-board clerk',type:'discover',target:'giant-stone-face',count:1,reward:{gold:12,xp:8}}
  ,'marker-followup':{id:'marker-followup',chain:'Municipal Depth Markers',step:2,title:'Submit the marker incident report',description:'Return after finding out what has been chewing on the markers.',giver:'Office of Subterranean Sanitation',type:'flag',target:'rat-marker-report',count:1,reward:{gold:15,xp:10}}
  ,'door-survey':{id:'door-survey',chain:'The Very Small Door',step:1,title:'Document the small door',description:'Knock on the tiny door and report its reply.',giver:'Linna Venn, Notice-board clerk',type:'flag',target:'small-door-knocked',count:1,reward:{gold:7,xp:8},next:'door-followup'}
  ,'door-followup':{id:'door-followup',chain:'The Very Small Door',step:2,title:'Leave a properly sized offering',description:'The small door has accepted a mushroom. The receipt is a response of sorts.',giver:'A notice written in very small handwriting',type:'flag',target:'small-door-receipt',count:1,reward:{gold:8,xp:12},next:'door-second-response'}
  ,'warm-wall-sample':{id:'warm-wall-sample',chain:'The Warm Wall',step:2,title:'Submit a warm sample',description:'Bring the Works Committee an ember sac from the warm wall.',giver:'Town Works Committee',type:'loot',target:'earthworm-ember',count:1,turnInItems:[{id:'earthworm-ember',quantity:1,consume:true}],reward:{gold:16,xp:12},next:'warm-wall-depth'}
  ,'warm-wall-depth':{id:'warm-wall-depth',chain:'The Warm Wall',step:3,title:'Inspect the deeper seam',description:'Find a warm-wall occurrence on level 3 and return with your notes.',giver:'Town Works Committee',type:'flag',target:'deep-warm-wall-return',count:1,reward:{gold:28,xp:20}}
  ,'crew-followup':{id:'crew-followup',chain:'Missing Survey Crew',step:2,title:'Find Nell below the camp',description:'Speak with Nell on a deeper floor, then report back in town.',giver:'Linna Venn, Notice-board clerk',type:'flag',target:'met-nell-deeper',count:1,reward:{gold:20,xp:14},next:'crew-report'}
  ,'crew-report':{id:'crew-report',chain:'Missing Survey Crew',step:3,title:'Close the survey file',description:'Return to town after meeting Nell and file her report.',giver:'Municipal Survey',type:'return',target:'any',count:1,reward:{gold:18,xp:15}}
  ,'duck-notice':{id:'duck-notice',chain:'The Duck',step:1,title:'Record the duck sighting',description:'Return to town after greeting the duck in the Hole.',giver:'Linna Venn, Notice-board clerk',type:'flag',target:'duck-returned',count:1,reward:{gold:5,xp:8},next:'duck-followup'}
  ,'duck-followup':{id:'duck-followup',chain:'The Duck',step:2,title:'File the second duck report',description:'Bring back the receipt left by the duck’s associate.',giver:'Office of Unexplained Waterfowl',type:'flag',target:'duck-receipt-returned',count:1,reward:{gold:13,xp:18}}
  ,'spoon-confirmation':{id:'spoon-confirmation',chain:'Too Many Spoons',step:1,title:'Confirm the spoon accumulation',description:'Count the spoons in the room. Do not attempt to establish a cause.',giver:'Linna Venn',type:'flag',target:'spoons-counted',count:1,reward:{gold:8,xp:6},next:'spoon-sample'}
  ,'spoon-sample':{id:'spoon-sample',chain:'Too Many Spoons',step:2,title:'Submit one representative spoon',description:'Bring back a bent spoon for municipal comparison.',giver:'Linna Venn',type:'loot',target:'bent-spoon',count:1,turnInItems:[{id:'bent-spoon',quantity:1,consume:true}],reward:{gold:12,xp:10},next:'spoon-certification'}
  ,'spoon-certification':{id:'spoon-certification',chain:'Too Many Spoons',step:3,title:'Submit a second sample',description:'The first spoon was filed. Bring one more bent spoon for the archive.',giver:'Town Works Committee',type:'loot',target:'bent-spoon',count:1,turnInItems:[{id:'bent-spoon',quantity:1,consume:true}],reward:{gold:10,xp:12,item:'official-spoon'}}
  ,'air-quality-sample':{id:'air-quality-sample',chain:'Air Quality Report',step:1,title:'Collect an air-quality sample',description:'Return a sealed sample from the odor survey.',giver:'Linna Venn',type:'loot',target:'condensed-stink',count:1,turnInItems:[{id:'condensed-stink',quantity:1,consume:true}],reward:{gold:14,xp:10},next:'air-quality-followup'}
  ,'air-quality-followup':{id:'air-quality-followup',chain:'Air Quality Report',step:2,title:'Confirm the source',description:'Defeat a Poo Gas and bring the finding back to town.',giver:'Town Works Committee',type:'kill',target:'poo-gas',count:1,reward:{gold:24,xp:20,item:'air-freshener'}}
  ,'apple-problem':{id:'apple-problem',chain:'The Apple Problem',step:1,title:'Investigate the apple reports',description:'Defeat a Rotten Apple. Please do not bring the whole fruit to the clerk.',giver:'Juniper Dunn',type:'kill',target:'rotten-apple',count:1,reward:{gold:12,xp:10},next:'apple-seeds'}
  ,'apple-seeds':{id:'apple-seeds',chain:'The Apple Problem',step:2,title:'Collect the seeds',description:'Bring back two Bad Seeds for comparison.',giver:'Juniper Dunn',type:'loot',target:'bad-seed',count:1,turnInItems:[{id:'bad-seed',quantity:2,consume:true}],reward:{gold:16,xp:12},next:'apple-core'}
  ,'apple-core':{id:'apple-core',chain:'The Apple Problem',step:3,title:'Inspect the core',description:'Use an apple corer on the next Rotten Apple anomaly.',giver:'Juniper Dunn',type:'flag',target:'apple-core-inspected',count:1,reward:{gold:18,xp:15}}
  ,'heart-condition':{id:'heart-condition',chain:'Heart Condition',step:1,title:'Confirm the winged heart',description:'Survive an encounter with Heart-Attack and report the finding.',giver:'Sal Morrow',type:'kill',target:'heart-attack',count:1,reward:{gold:14,xp:12},next:'heart-membrane-report'}
  ,'heart-membrane-report':{id:'heart-membrane-report',chain:'Heart Condition',step:2,title:'Submit the membrane sample',description:'Bring Juniper a Winged Heart Membrane.',giver:'Juniper Dunn',type:'loot',target:'heart-membrane',count:1,turnInItems:[{id:'heart-membrane',quantity:1,consume:true}],reward:{gold:22,xp:18,item:'emergency-poncho'}}
  ,'pip-inventory':{id:'pip-inventory',chain:'Pip’s Inventory Problem',step:1,title:'Complete Pip’s mushroom deal',description:'Trade with Pip Underledger for the agreed heavy spoon.',giver:'Pip Underledger',type:'trade',target:'mushroom-goose-deal',count:1,reward:{gold:10,xp:10},next:'pip-tail'}
  ,'pip-tail':{id:'pip-tail',chain:'Pip’s Inventory Problem',step:2,title:'Find a spiral byproduct',description:'Bring Pip a Curly Tail for his revised inventory plan.',giver:'Pip Underledger',type:'loot',target:'curly-tail',count:1,turnInItems:[{id:'curly-tail',quantity:1,consume:true}],reward:{gold:15,xp:14,item:'pork-unspiraler'}}
  ,'door-second-response':{id:'door-second-response',chain:'The Very Small Door',step:3,title:'Return the municipally labeled spoon',description:'Bring the Officially Sanctioned Spoon to the door and see whether it responds.',giver:'Linna Venn',type:'flag',target:'small-door-second-response',count:1,reward:{gold:11,xp:15}}
};

export const monsters={
  rat:{id:'rat',name:'Dungeon Rat',baseTier:1,depthEvolution:{damagePerLevel:.2,attackWeightPerLevel:.06},minDepth:1,hp:8,attack:4,defense:0,speed:2,xp:4,gold:[2,4],rarity:'common',lootTable:'rat-drops',encounterText:'A municipal depth marker has fresh tooth marks.',behavior:{type:'plain',description:'Bites once.'}},
  kobold:{id:'kobold',name:'Kobold Toll-Taker',baseTier:2,depthEvolution:{damagePerLevel:.2,attackWeightPerLevel:.045},minDepth:1,hp:12,attack:4,defense:1,speed:2,xp:7,gold:[2,7],rarity:'common',lootTable:'kobold-drops',encounterText:'It has set up a toll booth with no road attached.',behavior:{type:'guard',description:'Ordinary attack; carries trade goods.'}},
  killerRabbit:{id:'killer-rabbit',name:'Killer Rabbit',baseTier:2,depthEvolution:{damagePerLevel:.25,attackWeightPerLevel:.07},minDepth:1,hp:11,attack:6,defense:1,speed:4,xp:8,gold:[1,4],rarity:'uncommon',lootTable:'rabbit-drops',encounterText:'It looks harmless. It is not waiting for you to decide.',behavior:{type:'critical',criticalChance:.22,description:'Sometimes lands a hard bite.'}},
  kungFuGoose:{id:'kung-fu-goose',name:'Kung Fu Goose',baseTier:2,depthEvolution:{damagePerLevel:.18,attackWeightPerLevel:.09},minDepth:1,hp:10,attack:3,defense:1,speed:5,xp:9,gold:[0,3],rarity:'uncommon',lootTable:'goose-drops',encounterText:'The goose bows. The bow appears tactical.',behavior:{type:'quick',multiStrike:2,evadeChance:.12,description:'Two light strikes; may evade.'}},
  pocketSlime:{id:'pocket-slime',name:'Pocket Slime',baseTier:1,depthEvolution:{damagePerLevel:.2,attackWeightPerLevel:.035},minDepth:1,hp:13,attack:3,defense:1,speed:1,xp:7,gold:[0,2],rarity:'common',lootTable:'slime-drops',encounterText:'A blob attempts to fit inside your boot.',behavior:{type:'plain',description:'Slow, steady attacks.'}},
  fireWorm:{id:'fire-worm',name:'Fire-Breathing Earthworm',baseTier:3,depthEvolution:{damagePerLevel:.22,attackWeightPerLevel:.075,effectChancePerLevel:.012},minDepth:2,hp:18,attack:5,defense:2,speed:1,xp:15,gold:[4,9],rarity:'uncommon',lootTable:'worm-drops',encounterText:'A length of earthworm inhales. The earth glows.',behavior:{type:'burn',burnChance:.35,burnTurns:2,description:'May leave a brief burn.'}},
  skeleton:{id:'skeleton',name:'Skeleton on Break',baseTier:3,depthEvolution:{damagePerLevel:.2,attackWeightPerLevel:.05},minDepth:2,hp:18,attack:6,defense:2,speed:2,xp:16,gold:[4,10],rarity:'common',lootTable:'skeleton-drops',encounterText:'A skeleton checks a pocket watch. It has no pockets.',behavior:{type:'plain',description:'A sturdy, ordinary fighter.'}},
  paperMimic:{id:'paper-mimic',name:'Permit-Office Mimic',baseTier:4,depthEvolution:{damagePerLevel:.22,attackWeightPerLevel:.045},minDepth:3,hp:25,attack:7,defense:3,speed:2,xp:26,gold:[8,16],rarity:'rare',lootTable:'mimic-drops',encounterText:'The filing cabinet has too many teeth.',behavior:{type:'critical',criticalChance:.15,description:'Heavy strikes from a convincing cabinet.'}},
  heartAttack:{id:'heart-attack',name:'Heart-Attack',baseTier:3,minDepth:2,depthEvolution:{damagePerLevel:.18,attackWeightPerLevel:.055,effectChancePerLevel:.01},hp:13,attack:4,defense:0,speed:5,xp:14,gold:[3,7],rarity:'rare',lootTable:'heart-drops',aiProfile:'evasive',tags:['flying','flesh','strange','cardiac'],encounterText:'An anatomical heart flutters into view on small wings.',behavior:{type:'quick',evadeChance:.18,description:'Fast, evasive bursts.'}},
  porkscrew:{id:'porkscrew',name:'Porkscrew',baseTier:2,minDepth:2,depthEvolution:{damagePerLevel:.25,attackWeightPerLevel:.05},hp:17,attack:5,defense:2,speed:2,xp:12,gold:[3,8],rarity:'uncommon',lootTable:'porkscrew-drops',aiProfile:'aggressive',tags:['beast','pig','physical','strange'],encounterText:'A pig rotates into the corridor in a shape the corridor did not approve.',behavior:{type:'plain',description:'Sturdy, momentum-based attacks.'}},
  rottenApple:{id:'rotten-apple',name:'Rotten Apple',baseTier:2,minDepth:2,depthEvolution:{damagePerLevel:.16,attackWeightPerLevel:.04,effectChancePerLevel:.012},hp:12,attack:4,defense:0,speed:1,xp:10,gold:[1,4],rarity:'uncommon',lootTable:'rotten-apple-drops',aiProfile:'opportunistic',tags:['plant','food','rotten','poison','strange'],encounterText:'A rotten apple has become hostile without explanation.',behavior:{type:'plain',description:'Fragile; increasingly unpleasant effects.'}},
  pooGas:{id:'poo-gas',name:'Poo Gas',baseTier:4,minDepth:3,depthEvolution:{damagePerLevel:.18,attackWeightPerLevel:.04,effectChancePerLevel:.01},hp:15,attack:5,defense:0,physicalResistance:.6,speed:4,xp:23,gold:[4,9],rarity:'rare',lootTable:'poo-gas-drops',aiProfile:'opportunistic',tags:['gas','poison','airborne','strange'],encounterText:'A foul-smelling cloud takes a shape best not investigated.',behavior:{type:'plain',description:'Physical attacks pass through most of the cloud.'}}
};
const monsterMetadata={rat:{tags:['beast'],aiProfile:'aggressive'},kobold:{tags:['kobold','humanoid'],aiProfile:'cautious'},killerRabbit:{tags:['beast','rabbit'],aiProfile:'aggressive'},kungFuGoose:{tags:['beast','goose'],aiProfile:'evasive'},pocketSlime:{tags:['slime'],aiProfile:'simple'},fireWorm:{tags:['worm','fire'],aiProfile:'aggressive'},skeleton:{tags:['undead','humanoid'],aiProfile:'simple'},paperMimic:{tags:['construct','mimic','bureaucratic-horror'],aiProfile:'opportunistic'}};
for(const [key,metadata] of Object.entries(monsterMetadata)){monsters[key].tags=metadata.tags;monsters[key].aiProfile=metadata.aiProfile}

export const enemyVariants=[{id:'large',name:'Large',levelBonus:1,hpMultiplier:1.24,attackBonus:0,defenseBonus:1,attackWeightMultiplier:1.08,xpMultiplier:1.18,goldMultiplier:1.15,lootBonus:.04,spawnChance:.027},{id:'veteran',name:'Veteran',levelBonus:1,hpMultiplier:1.12,attackBonus:1,defenseBonus:0,attackWeightMultiplier:1.15,xpMultiplier:1.2,goldMultiplier:1.2,lootBonus:.05,spawnChance:.025},{id:'very-angry',name:'Very Angry',levelBonus:2,hpMultiplier:1.08,attackBonus:1,defenseBonus:0,attackWeightMultiplier:1.3,xpMultiplier:1.25,goldMultiplier:1.18,lootBonus:.04,spawnChance:.013}];

const attackSets={
  rat:[['nibble','Nibble',2,4,.68,'A suspiciously confident nibble.'],['lunge','Lunge',3,5,.32,'The rat lunges with municipal purpose.'],{id:'cornered-bite',name:'Cornered Bite',minDamage:4,maxDamage:6,weight:.18,unlockLevel:4,weightPerLevel:.04,flavor:'The rat commits to an unnecessarily personal bite.'},{id:'frenzy',name:'Rat Frenzy',minDamage:2,maxDamage:4,weight:.12,unlockLevel:8,weightPerLevel:.035,flavor:'The rat becomes a brief blur of teeth.',multiStrike:2}],
  kobold:[['toll-club','Tolling bonk',2,5,.72,'The kobold demands payment in bruises.'],['pocket-sand','Pocket sand',3,6,.28,'A handful of grit arrives with surprising force.'],{id:'late-fee',name:'Late Fee',minDamage:4,maxDamage:6,weight:.18,unlockLevel:4,effect:'weakened',effectChance:.22,effectTurns:2,effectMagnitude:1,flavor:'A late fee is applied directly to your confidence.'},{id:'express-toll',name:'Express Toll',minDamage:5,maxDamage:8,weight:.12,unlockLevel:8,weightPerLevel:.035,flavor:'The kobold opens the express lane into your shoulder.'}],
  killerRabbit:[['scratch','Scratch',3,6,.76,'The rabbit scratches with alarming focus.'],['leap','Throatward leap',5,7,.24,'The rabbit launches itself at your neck.'],{id:'burrow-feint',name:'Burrow Feint',minDamage:3,maxDamage:6,weight:.2,unlockLevel:5,flavor:'The rabbit feints from a direction that should not fit.'},{id:'velvet-burst',name:'Velvet Burst',minDamage:6,maxDamage:9,weight:.12,unlockLevel:8,weightPerLevel:.04,flavor:'A blur of ears and teeth arrives all at once.',multiStrike:2}],
  kungFuGoose:[['wing-slap','Wing slap',1,3,.7,'A wing catches you on the shoulder.'],['flying-kick','Flying kick',3,5,.3,'The goose delivers a perfectly committed kick.'],{id:'terrifying-honk',name:'Terrifying Honk',minDamage:2,maxDamage:4,weight:.16,unlockLevel:5,effect:'weakened',effectChance:.2,effectTurns:1,effectMagnitude:1,flavor:'The goose honks with disciplined menace.'}],
  pocketSlime:[['ooze','Ooze bump',1,4,.8,'The slime bumps you with damp determination.'],['splorch','Splorch',2,5,.2,'The slime splorches directly into your boots.'],{id:'pocket-guard',name:'Pocket Guard',minDamage:1,maxDamage:3,weight:.2,unlockLevel:4,effect:'guarded',effectChance:.18,effectTurns:1,effectMagnitude:2,flavor:'The slime raises a gelatinous pocket-sized shield.'}],
  fireWorm:[['bite','Bite',3,6,.7,'The earthworm bites down.'],['flame-belch','Flame belch',4,7,.3,'The earthworm exhales a tiny, furious flame.'],{id:'superheated-belch',name:'Superheated Belch',minDamage:5,maxDamage:8,weight:.16,unlockLevel:6,weightPerLevel:.04,effect:'burn',effectChance:.5,effectTurns:2,effectMagnitude:2,effectChancePerLevel:.012,tags:['fire'],flavor:'The worm inhales until its cheeks glow, then belches flame.'}],
  skeleton:[['rattle','Rattling swipe',3,6,.72,'The skeleton swipes with a loose bone.'],['clipboard','Clipboard smack',4,7,.28,'A clipboard appears from nowhere.'],{id:'brace-for-break',name:'Brace for Break',minDamage:2,maxDamage:4,weight:.2,unlockLevel:5,effect:'weakened',effectChance:.16,effectTurns:1,effectMagnitude:1,flavor:'The skeleton braces behind its clipboard.'}],
  paperMimic:[['snap','Cabinet snap',4,7,.76,'The filing cabinet snaps shut on you.'],['forms','Paperwork avalanche',5,8,.24,'A stack of forms hits like a brick.'],{id:'compliance-hold',name:'Compliance Hold',minDamage:4,maxDamage:6,weight:.2,unlockLevel:6,effect:'weakened',effectChance:.28,effectTurns:2,effectMagnitude:1,flavor:'The mimic places you under an immediate administrative hold.'}],
  heartAttack:[{id:'flutter',name:'Flutter',minDamage:2,maxDamage:4,weight:.65,flavor:'Heart-Attack flutters past and clips you with a wing.'},{id:'chest-thump',name:'Chest Thump',minDamage:4,maxDamage:6,weight:.35,flavor:'Heart-Attack lands a heavy chest thump.'},{id:'palpitation',name:'Palpitation',minDamage:4,maxDamage:6,weight:.22,unlockLevel:5,effect:'weakened',effectChance:.25,effectTurns:2,effectMagnitude:1,weightPerLevel:.035,flavor:'Heart-Attack begins beating violently. A palpitation leaves you shaken.'},{id:'cardiac-arrest',name:'Cardiac Arrest',minDamage:6,maxDamage:9,weight:.1,unlockLevel:8,effect:'weakened',effectChance:.35,effectTurns:2,effectMagnitude:1,flavor:'Heart-Attack beats once with alarming authority. Cardiac Arrest follows.'}],
  porkscrew:[{id:'squeal',name:'Squeal',minDamage:1,maxDamage:3,weight:.25,effect:'weakened',effectChance:.12,effectTurns:1,effectMagnitude:1,flavor:'Porkscrew squeals directly into your concentration.'},{id:'spiral-charge',name:'Spiral Charge',minDamage:4,maxDamage:6,weight:.58,weightPerLevel:.025,flavor:'Porkscrew corkscrews forward with alarming momentum.'},{id:'ham-drill',name:'Ham Drill',minDamage:6,maxDamage:8,weight:.17,unlockLevel:5,weightPerLevel:.025,flavor:'Porkscrew spins into a compact and unpleasant drill.'},{id:'unwind',name:'Unwind',minDamage:4,maxDamage:7,weight:.12,unlockLevel:8,effect:'slowed',effectChance:.2,effectTurns:1,effectMagnitude:1,flavor:'Porkscrew unwinds just enough to catch you off balance.'}],
  rottenApple:[{id:'bad-seed',name:'Bad Seed',minDamage:1,maxDamage:3,weight:.55,flavor:'A bad seed bounces off your boot.'},{id:'rotten-bite',name:'Rotten Bite',minDamage:3,maxDamage:5,weight:.35,flavor:'The apple bites with one very soft spot.'},{id:'bruise-burst',name:'Bruise Burst',minDamage:2,maxDamage:5,weight:.2,unlockLevel:4,effect:'poison',effectChance:.28,effectTurns:2,effectMagnitude:1,flavor:'A bruise bursts into a faintly toxic mist.'},{id:'core-rot',name:'Core Rot',minDamage:3,maxDamage:6,weight:.12,unlockLevel:8,weightPerLevel:.035,effect:'poison',effectChance:.38,effectChancePerLevel:.012,effectTurns:3,effectMagnitude:1,flavor:'The apple opens its core. This is worse than expected.'}],
  pooGas:[{id:'waft',name:'Waft',minDamage:1,maxDamage:3,weight:.58,effect:'poison',effectChance:.12,effectTurns:1,effectMagnitude:1,flavor:'A small waft causes immediate regret.'},{id:'silent-but-deadly',name:'Silent But Deadly',minDamage:3,maxDamage:5,weight:.42,flavor:'The cloud silently becomes more concentrated.'},{id:'eye-watering-cloud',name:'Eye-Watering Cloud',minDamage:2,maxDamage:5,weight:.2,unlockLevel:6,effect:'weakened',effectChance:.28,effectTurns:2,effectMagnitude:1,flavor:'An eye-watering cloud clouds your judgment.'},{id:'room-clearer',name:'Room Clearer',minDamage:5,maxDamage:8,weight:.12,unlockLevel:8,weightPerLevel:.03,effect:'poison',effectChance:.35,effectChancePerLevel:.01,effectTurns:2,effectMagnitude:1,flavor:'The Room Clearer arrives. The room is not cleared.'}]
};
for(const [id,m] of Object.entries(monsters)){m.attacks=attackSets[id].map(attack=>{let normalized;if(Array.isArray(attack)){const [attackId,name,minDamage,maxDamage,weight,flavor]=attack;normalized={id:attackId,name,minDamage,maxDamage,accuracy:.94,weight,flavor,tags:id==='fireWorm'&&attackId==='flame-belch'?['fire']:['physical'],...(id==='fireWorm'&&attackId==='flame-belch'?{effect:'burn',effectChance:.45,effectTurns:2,effectMagnitude:2}:{})}}else normalized={accuracy:.94,tags:['physical'],...attack};normalized.tags=[...new Set([...(normalized.tags||['physical']),...(normalized.effect?['status',normalized.effect]:[])])];return normalized});m.sprite={src:`assets/monsters/${m.id}.svg`,scale:1,offsetY:0}}
const attackNarration={rat:{nibble:['The rat snaps at your ankle.','The rat attempts a deeply personal bite.','The rat lunges teeth-first.'],lunge:['The rat lunges with municipal purpose.','The rat comes in low and fast.','The rat has found your shoe policy inadequate.'],'cornered-bite':['The rat commits to an unnecessarily personal bite.','The rat bites as if filing a complaint.'],frenzy:['The rat becomes a brief blur of teeth.','The rat makes several poor decisions at speed.']},kungFuGoose:{'wing-slap':['A wing catches your shoulder.','The goose slaps with one wing and a clear plan.','Feathers and force arrive together.'],'flying-kick':['The goose delivers a perfectly committed kick.','The goose launches a compact flying kick.','The goose demonstrates a troubling amount of training.']},fireWorm:{bite:['The earthworm bites down.','A determined bite finds your boot.','The worm applies its mouth to the problem.'],'flame-belch':['The worm exhales a tiny, furious flame.','A short burst of flame passes over you.','The earthworm belches heat with professional focus.']},porkscrew:{'spiral-charge':['Porkscrew corkscrews forward with alarming momentum.','A spiral charge scrapes across the stone.','Porkscrew commits to a rotating approach.']},rottenApple:{'rotten-bite':['The apple bites with one very soft spot.','A brown patch snaps at you.','The apple rolls in close and bites.']},pooGas:{waft:['A small waft causes immediate regret.','The cloud drifts over you.','The air becomes briefly worse.']}};
for(const [monsterId,attacks] of Object.entries(attackNarration))for(const attack of monsters[monsterId]?.attacks||[])if(attacks[attack.id])attack.flavors=attacks[attack.id]
for(const monster of Object.values(monsters))for(const attack of monster.attacks)if(!attack.flavors)attack.flavors=[attack.flavor||`${monster.name} uses ${attack.name}.`,`${monster.name} makes a quick ${attack.name.toLowerCase()} attempt.`,`${attack.name} arrives with little further explanation.`]
// These two user-drawn designs keep their stable IDs for existing saves and quest references.
monsters.kungFuGoose.name='Kung Fungoose';
monsters.kungFuGoose.sprite={ink:'assets/images/enemies/kung-fungoose-ink.png',colored:'assets/images/enemies/kung-fungoose-colored.png',scale:1.12,offsetY:-1};
monsters.rat.name='Deadly Rat';
monsters.rat.sprite={ink:'assets/images/enemies/deadly-rat-ink.png',colored:'assets/images/enemies/deadly-rat-colored.png',scale:1.08,offsetY:1};
monsters.fireWorm.sprite={ink:'assets/images/enemies/fire-breathing-earthworm-ink.png',colored:'assets/images/enemies/fire-breathing-earthworm-colored.png',scale:1.08,offsetY:0};
monsters.killerRabbit.sprite={ink:'assets/images/enemies/killer-rabbit-ink.png',colored:'assets/images/enemies/killer-rabbit-colored.png',scale:1.08,offsetY:0};
monsters.pocketSlime.sprite={ink:'assets/images/enemies/pocket-slime-ink.png',colored:'assets/images/enemies/pocket-slime-colored.png',scale:1.12,offsetY:-2};
for(const key of ['heartAttack','porkscrew','rottenApple','pooGas'])monsters[key].sprite.src='assets/monsters/fallback.svg';
monsters.pooGas.sprite={src:'assets/monsters/fallback.svg',ink:'assets/images/enemies/poo-gas-ink.png',colored:'assets/images/enemies/poo-gas-colored.png',scale:1.08,offsetY:0};
monsters.porkscrew.sprite={src:'assets/monsters/fallback.svg',ink:'assets/images/enemies/porkscrew-ink.png',colored:'assets/images/enemies/porkscrew-colored.png',scale:1.08,offsetY:0};
monsters.heartAttack.sprite={src:'assets/monsters/fallback.svg',ink:'assets/images/enemies/heart-attack-ink.png',colored:'assets/images/enemies/heart-attack-colored.png',scale:1.08,offsetY:0};
monsters.rottenApple.sprite={src:'assets/monsters/fallback.svg',ink:'assets/images/enemies/rotten-apple-ink.png',colored:'assets/images/enemies/rotten-apple-colored.png',scale:1.08,offsetY:0};

export const items={
  'rusty-sword':{id:'rusty-sword',name:'Rusty Sword',category:'equipment',slot:'mainHand',rarity:'common',buyValue:12,sellValue:5,modifiers:{attack:2},flavor:'The rust is mostly decorative. Probably.',stackable:false},
  'patched-coat':{id:'patched-coat',name:'Patched Coat',category:'equipment',slot:'body',rarity:'common',buyValue:10,sellValue:4,modifiers:{defense:1,hp:2},flavor:'One patch is an official town map.',stackable:false},
  'wooden-shield':{id:'wooden-shield',name:'Wooden Shield',category:'equipment',slot:'offHand',rarity:'common',buyValue:18,sellValue:8,modifiers:{defense:2},flavor:'It has been tested against doors.',stackable:false},
  'leather-armor':{id:'leather-armor',name:'Leather Armor',category:'equipment',slot:'body',rarity:'common',buyValue:28,sellValue:12,modifiers:{defense:2,hp:3},flavor:'Practical, if a little damp.',stackable:false},
  'reinforced-boots':{id:'reinforced-boots',name:'Reinforced Boots',category:'equipment',slot:'feet',rarity:'common',buyValue:20,sellValue:8,modifiers:{defense:1,agility:1},flavor:'The stairs have opinions about footwear.',stackable:false},
  'apprentice-staff':{id:'apprentice-staff',name:'Apprentice Staff',category:'equipment',slot:'mainHand',rarity:'uncommon',buyValue:38,sellValue:16,modifiers:{attack:1,mind:1,mp:3},classes:['Wizard','Cleric'],flavor:'It knows three spells and one of them is a knock.',stackable:false},
  'goose-proof-helmet':{id:'goose-proof-helmet',name:'Goose-Proof Helmet',category:'equipment',slot:'head',rarity:'uncommon',buyValue:32,sellValue:14,modifiers:{defense:1,agility:1},effects:{vsGoose:2},flavor:'The warranty is very specific.',stackable:false},
  'questionable-luck':{id:'questionable-luck',name:'Ring of Questionable Luck',category:'equipment',slot:'accessory',rarity:'strange',buyValue:48,sellValue:20,modifiers:{agility:1},effects:{lootBonus:.08},flavor:'The ring insists that the odds are excellent.',stackable:false},
  'heavy-spoon':{id:'heavy-spoon',name:'Extremely Heavy Spoon',category:'equipment',slot:'mainHand',rarity:'common',buyValue:14,sellValue:5,modifiers:{attack:3,agility:-1},flavor:'Designed for soup of unusual density.',stackable:false},
  'fireproof-trousers':{id:'fireproof-trousers',name:'Pants of Minor Fire Resistance',category:'equipment',slot:'body',rarity:'uncommon',buyValue:36,sellValue:15,modifiers:{defense:1},effects:{fireResistance:2},flavor:'Minor resistance. Major tailoring.',stackable:false},
  'kobold-buckler':{id:'kobold-buckler',name:'Kobold-Chewed Buckler',category:'equipment',slot:'offHand',rarity:'uncommon',buyValue:30,sellValue:13,modifiers:{defense:1},effects:{retreatBonus:10},flavor:'The bite marks are now considered reinforcement.',stackable:false},
  'squeaky-boots':{id:'squeaky-boots',name:'Boots That Squeak Near Treasure',category:'equipment',slot:'feet',rarity:'strange',buyValue:42,sellValue:17,modifiers:{agility:1},effects:{lootBonus:.12},flavor:'They squeak only when you would prefer they did not.',stackable:false},
  'healing-tonic':{id:'healing-tonic',name:'Healing Tonic',category:'consumable',rarity:'common',buyValue:8,sellValue:3,effect:{type:'heal',amount:8},flavor:'Tastes faintly of mint and paperwork.',stackable:true},
  'cave-salt':{id:'cave-salt',name:'Cave Salt',category:'trade-good',rarity:'common',buyValue:4,sellValue:2,flavor:'Useful to someone, apparently.',stackable:true},
  'suspicious-mushroom':{id:'suspicious-mushroom',name:'Suspicious Mushroom',category:'trade-good',rarity:'common',buyValue:5,sellValue:2,flavor:'The mushroom is being cagey.',stackable:true},
  'goose-feather':{id:'goose-feather',name:'Goose Feather',category:'trade-good',rarity:'uncommon',buyValue:7,sellValue:3,flavor:'It has a remarkably stern quill.',stackable:true},
  'earthworm-ember':{id:'earthworm-ember',name:'Earthworm Ember Sac',category:'trade-good',rarity:'uncommon',buyValue:10,sellValue:4,flavor:'Warm. Do not squeeze.',stackable:true},
  'kobold-trinket':{id:'kobold-trinket',name:'Kobold Trinket',category:'trade-good',rarity:'common',buyValue:6,sellValue:3,flavor:'The exchange rate is known only to kobolds.',stackable:true},
  'blue-lunchbox':{id:'blue-lunchbox',name:'Blue Lunchbox',category:'quest',rarity:'common',buyValue:0,sellValue:0,questItem:true,stackable:false,flavor:'Name scratched underneath: “Mara.”'},
  'stone-chip':{id:'stone-chip',name:'Unremarkable Stone Chip',category:'quest',rarity:'common',buyValue:0,sellValue:0,questItem:true,stackable:false,flavor:'The committee will be thrilled.'},
  'bent-spoon':{id:'bent-spoon',name:'Bent Spoon',category:'junk',rarity:'common',buyValue:2,sellValue:1,flavor:'No longer suitable for formal soup.',stackable:true}
  ,'kobold-pie':{id:'kobold-pie',name:'Kobold Bake-Sale Pie',category:'consumable',rarity:'uncommon',buyValue:6,sellValue:2,effect:{type:'buff',name:'defense',value:1,encounters:2},flavor:'Warm, flaky, and lightly defensive.',stackable:true}
  ,'survey-notes':{id:'survey-notes',name:'Survey Notes',category:'quest',rarity:'common',buyValue:0,sellValue:0,questItem:true,stackable:false,flavor:'Careful handwriting. The margins mention a duck.'}
  ,'helmet-mild-confidence':{id:'helmet-mild-confidence',name:'Helmet of Mild Confidence',category:'equipment',slot:'head',rarity:'strange',buyValue:44,sellValue:15,modifiers:{defense:1},effects:{retreatBonus:-5},flavor:'You feel prepared to address a meeting. Leaving it is harder.'}
  ,'emergency-snack-belt':{id:'emergency-snack-belt',name:'Belt of Emergency Snacks',category:'equipment',slot:'accessory',rarity:'uncommon',buyValue:38,sellValue:14,modifiers:{hp:2},effects:{postCombatHeal:.2},flavor:'After a difficult fight, one crumb may become medically relevant.'}
  ,'unnecessary-grip-gloves':{id:'unnecessary-grip-gloves',name:'Gloves of Unnecessary Grip',category:'equipment',slot:'offHand',rarity:'uncommon',buyValue:36,sellValue:13,modifiers:{attack:1},flavor:'Designed for holding a sword and the conversation.'}
  ,'administrative-cape':{id:'administrative-cape',name:'Cape of Administrative Authority',category:'equipment',slot:'body',rarity:'strange',buyValue:58,sellValue:20,modifiers:{defense:1},effects:{sellBonus:.2,buyDiscount:.08},flavor:'Monsters are unmoved. Several clerks are not.'}
  ,'warm-duck-ring':{id:'warm-duck-ring',name:'Ring That Feels Warm Near Ducks',category:'equipment',slot:'accessory',rarity:'strange',buyValue:52,sellValue:18,modifiers:{mind:1},effects:{duckSense:1},flavor:'Warmth is not a reliable identification method.'}
  ,'receipt-boots':{id:'receipt-boots',name:'Receipt-Lined Boots',category:'equipment',slot:'feet',rarity:'rare',buyValue:46,sellValue:18,modifiers:{agility:1,defense:-1},effects:{retreatBonus:7},flavor:'A tidy record of every step you would rather not repeat.'}
  ,'spoon-splint':{id:'spoon-splint',name:'Spoon-Splint Bracer',category:'equipment',slot:'offHand',rarity:'uncommon',buyValue:32,sellValue:12,modifiers:{defense:2,attack:-1},flavor:'The spoon is structurally important.'}
  ,'surveyor-lens':{id:'surveyor-lens',name:'Municipal Surveyor’s Lens',category:'equipment',slot:'head',rarity:'rare',buyValue:54,sellValue:21,modifiers:{mind:1,mp:1},effects:{lootBonus:.04},flavor:'Makes distant walls look like someone else’s responsibility.'}
  ,'damp-reading-gloves':{id:'damp-reading-gloves',name:'Gloves of Damp Reading',category:'equipment',slot:'offHand',rarity:'strange',buyValue:40,sellValue:15,modifiers:{mind:1},effects:{fireResistance:1},flavor:'Useful for reading signs that have become inexplicably wet.'}
  ,'air-freshener':{id:'air-freshener',name:'Dungeon-Grade Air Freshener',category:'consumable',rarity:'uncommon',buyValue:14,sellValue:5,effect:{type:'combat-tool',targetTags:['gas'],damage:11,resistanceReductionTurns:1},eventHooks:['odor','gas'],flavor:'Approved for enclosed spaces, questionable basements, and whatever this is.',stackable:true}
  ,'heart-membrane':{id:'heart-membrane',name:'Winged Heart Membrane',category:'trade-good',rarity:'uncommon',buyValue:8,sellValue:3,flavor:'Medical staff have requested that it remain labeled.',stackable:true}
  ,'curly-tail':{id:'curly-tail',name:'Curly Tail',category:'trade-good',rarity:'common',buyValue:6,sellValue:2,flavor:'It keeps trying to point north.',stackable:true}
  ,'bad-seed':{id:'bad-seed',name:'Bad Seed',category:'trade-good',rarity:'common',buyValue:4,sellValue:2,flavor:'It has already disappointed its family.',stackable:true}
  ,'condensed-stink':{id:'condensed-stink',name:'Condensed Stink',category:'trade-good',rarity:'rare',buyValue:9,sellValue:3,flavor:'The jar is sealed. The jar is also sweating.',stackable:true}
  ,'municipal-knee-pads':{id:'municipal-knee-pads',name:'Municipal Knee Pads',category:'equipment',slot:'body',rarity:'uncommon',buyValue:34,sellValue:13,modifiers:{defense:1},effects:{hazardReduction:1},flavor:'Issued for crawling under desks and occasionally through tunnels.',stackable:false}
  ,'questionable-aerodynamics':{id:'questionable-aerodynamics',name:'Helmet of Questionable Aerodynamics',category:'equipment',slot:'head',rarity:'strange',buyValue:48,sellValue:17,modifiers:{defense:2,agility:-1},flavor:'Air passes over it in a way that raises further questions.',stackable:false}
  ,'unearned-confidence-socks':{id:'unearned-confidence-socks',name:'Socks of Unearned Confidence',category:'equipment',slot:'feet',rarity:'strange',buyValue:39,sellValue:14,modifiers:{defense:-1},effects:{retreatBonus:8},flavor:'They make every exit seem personally achievable.',stackable:false}
  ,'official-spoon':{id:'official-spoon',name:'Officially Sanctioned Spoon',category:'equipment',slot:'mainHand',rarity:'strange',buyValue:42,sellValue:15,modifiers:{attack:2},eventHooks:['spoons'],flavor:'Stamped, numbered, and not approved for soup.',stackable:false}
  ,'emergency-poncho':{id:'emergency-poncho',name:'Emergency Poncho',category:'equipment',slot:'body',rarity:'uncommon',buyValue:36,sellValue:14,modifiers:{defense:1},effects:{statusResistance:.15},flavor:'Thin, loud, and unexpectedly reassuring.',stackable:false}
  ,'boots-know-better':{id:'boots-know-better',name:'Boots That Know Better',category:'equipment',slot:'feet',rarity:'rare',buyValue:50,sellValue:19,modifiers:{agility:1},effects:{retreatBonus:6},flavor:'They have seen this route before and would like to leave.',stackable:false}
  ,'pocket-receipt-printer':{id:'pocket-receipt-printer',name:'Pocket Receipt Printer',category:'equipment',slot:'accessory',rarity:'strange',buyValue:46,sellValue:16,modifiers:{mind:1},effects:{sellBonus:.08},flavor:'It prints receipts for transactions no one remembers making.',stackable:false}
  ,'half-shield':{id:'half-shield',name:'Half a Shield',category:'equipment',slot:'offHand',rarity:'uncommon',buyValue:25,sellValue:9,modifiers:{defense:1,agility:1},flavor:'The other half is not included in this listing.',stackable:false}
  ,'suspicious-apple-corer':{id:'suspicious-apple-corer',name:'Extremely Suspicious Apple Corer',category:'equipment',slot:'mainHand',rarity:'rare',buyValue:45,sellValue:17,modifiers:{attack:1},effects:{vsTags:{rotten:3,plant:1}},flavor:'A kitchen tool with a surprisingly specific warranty.',stackable:false}
  ,'anti-goose-whistle':{id:'anti-goose-whistle',name:'Anti-Goose Whistle',category:'equipment',slot:'accessory',rarity:'uncommon',buyValue:32,sellValue:12,modifiers:{agility:1},effects:{vsGoose:2},flavor:'Geese hear it. Other people hear nothing and remain concerned.',stackable:false}
  ,'pork-unspiraler':{id:'pork-unspiraler',name:'Pork Unspiraler',category:'equipment',slot:'mainHand',rarity:'strange',buyValue:47,sellValue:18,modifiers:{attack:2},effects:{vsTags:{pig:3}},flavor:'The instructions are optimistic about geometry.',stackable:false}
};
export function monsterForId(id){return monsters[id]||Object.values(monsters).find(monster=>monster.id===id)||null}

export const lootTables={
  'rat-drops':[{item:'cave-salt',weight:4},{item:'suspicious-mushroom',weight:2},{item:'bent-spoon',weight:1},{item:'spoon-splint',weight:.18},{item:'municipal-knee-pads',weight:.06}],
  'kobold-drops':[{item:'kobold-trinket',weight:4},{item:'cave-salt',weight:2},{item:'wooden-shield',weight:1},{item:'administrative-cape',weight:.12}],
  'rabbit-drops':[{item:'suspicious-mushroom',weight:3},{item:'reinforced-boots',weight:1},{item:'goose-proof-helmet',weight:1},{item:'receipt-boots',weight:.18}],
  'goose-drops':[{item:'goose-feather',weight:5},{item:'goose-proof-helmet',weight:1},{item:'questionable-luck',weight:1},{item:'helmet-mild-confidence',weight:.16}],
  'slime-drops':[{item:'cave-salt',weight:3},{item:'suspicious-mushroom',weight:3},{item:'healing-tonic',weight:1},{item:'emergency-snack-belt',weight:.18}],
  'worm-drops':[{item:'earthworm-ember',weight:5},{item:'fireproof-trousers',weight:1},{item:'heavy-spoon',weight:1},{item:'damp-reading-gloves',weight:.18}],
  'skeleton-drops':[{item:'kobold-trinket',weight:2},{item:'wooden-shield',weight:2},{item:'leather-armor',weight:1},{item:'unnecessary-grip-gloves',weight:.18}],
  'mimic-drops':[{item:'heavy-spoon',weight:2},{item:'squeaky-boots',weight:2},{item:'apprentice-staff',weight:1},{item:'surveyor-lens',weight:.22},{item:'warm-duck-ring',weight:.16}],
  'heart-drops':[{item:'heart-membrane',weight:4},{item:'goose-feather',weight:1},{item:'healing-tonic',weight:.35},{item:'emergency-poncho',weight:.08}],
  'porkscrew-drops':[{item:'curly-tail',weight:4},{item:'cave-salt',weight:2},{item:'heavy-spoon',weight:.25}],
  'rotten-apple-drops':[{item:'bad-seed',weight:4},{item:'suspicious-mushroom',weight:2},{item:'air-freshener',weight:.55},{item:'suspicious-apple-corer',weight:.08}],
  'poo-gas-drops':[{item:'condensed-stink',weight:4},{item:'air-freshener',weight:.35}],
  'spoon-drops':[{item:'bent-spoon',weight:5},{item:'official-spoon',weight:.08}],
  'porkscrew-drops':[{item:'curly-tail',weight:4},{item:'cave-salt',weight:2},{item:'heavy-spoon',weight:.25},{item:'pork-unspiraler',weight:.08}]
};

export const townNpcs={
  clerk:{name:'Linna Venn',role:'Notice-board clerk',line:'I file the quests by depth. The hole files nothing.'},
  shopkeeper:{name:'Juniper Dunn',role:'General-store keeper',line:'If it came up from below, I can probably price it.'},
  innkeeper:{name:'Sal Morrow',role:'Innkeeper',line:'Rooms are quiet. The ground floor is quietest.'}
};

export const dungeonNpcs={
  'kobold-trader':{id:'kobold-trader',name:'Pip Underledger',role:'Wandering kobold merchant',line:'Gold is fine. Odd things are better. I have a ledger for both.',tradeIds:['salt-for-buckler','mushroom-goose-deal']},
  'lost-surveyor':{id:'lost-surveyor',name:'Nell from Municipal Survey',role:'Lost adventurer',line:'I came to measure the stairs. I have been measuring for three days.',stock:['healing-tonic'],priceMultiplier:2}
};

export const trades={
  'salt-for-buckler':{id:'salt-for-buckler',npcId:'kobold-trader',title:'Trade cave salt for a buckler',gives:[{item:'kobold-buckler',quantity:1}],requires:[{item:'cave-salt',quantity:2}],gold:4},
  'mushroom-goose-deal':{id:'mushroom-goose-deal',npcId:'kobold-trader',title:'Three mushrooms and one goose feather for a heavy spoon',gives:[{item:'heavy-spoon',quantity:1}],requires:[{item:'suspicious-mushroom',quantity:3},{item:'goose-feather',quantity:1}],gold:20},
  'deep-ledger-lens':{id:'deep-ledger-lens',npcId:'kobold-trader',title:'Pip’s deeper-floor special',gives:[{item:'surveyor-lens',quantity:1}],requires:[{item:'cave-salt',quantity:3},{item:'kobold-trinket',quantity:2}],gold:18}
};

export const shopStock=['healing-tonic','rusty-sword','wooden-shield','leather-armor','reinforced-boots','apprentice-staff','goose-proof-helmet','fireproof-trousers','unnecessary-grip-gloves','surveyor-lens','air-freshener','municipal-knee-pads','questionable-aerodynamics','unearned-confidence-socks','emergency-poncho','boots-know-better','half-shield','suspicious-apple-corer','anti-goose-whistle'];
export const merchantProfiles={juniper:{id:'juniper',buyMultiplier:1,likes:['ordinary-goods'],tradeBonus:0},'kobold-trader':{id:'kobold-trader',buyMultiplier:1,likes:['trade-good','strange'],tradeBonus:.05},'lost-surveyor':{id:'lost-surveyor',buyMultiplier:2,likes:['emergency-supplies'],tradeBonus:0}};
export const npcEncounterIds=['kobold-trader','lost-surveyor'];
export const floorEncounterTable={
  1:[{id:'rat',weight:3},{id:'kobold',weight:2},{id:'killerRabbit',weight:2},{id:'kungFuGoose',weight:2},{id:'pocketSlime',weight:3}],
  2:[{id:'rat',weight:1},{id:'kobold',weight:2},{id:'killerRabbit',weight:2},{id:'kungFuGoose',weight:2},{id:'pocketSlime',weight:2},{id:'fireWorm',weight:3},{id:'skeleton',weight:3},{id:'porkscrew',weight:1.35},{id:'rottenApple',weight:1.45},{id:'heartAttack',weight:.32}],
  3:[{id:'killerRabbit',weight:2},{id:'kungFuGoose',weight:2},{id:'fireWorm',weight:3},{id:'skeleton',weight:3},{id:'paperMimic',weight:2},{id:'porkscrew',weight:1.35},{id:'rottenApple',weight:1.35},{id:'heartAttack',weight:.75},{id:'pooGas',weight:.65}]
};

export const roomTypes={
  'mushroom-room':{id:'mushroom-room',name:'Mushroom Room',weight:14,description:'Pale mushrooms cluster along the damp stone edges.',visual:{theme:'damp-organic',propPool:['mushroom-cluster','tall-mushrooms'],floorTreatment:'damp',wallTreatment:'mossy',atmosphere:'green-lantern',density:3,placementRules:['far-left','far-right','mid-left','mid-right','far-center']}},
  'flooded-chamber':{id:'flooded-chamber',name:'Flooded Chamber',weight:8,description:'A shallow sheet of water covers the stone.',visual:{theme:'shallow-water',propPool:['water-debris','floating-plank'],floorTreatment:'flooded',wallTreatment:'wet-stone',atmosphere:'cool-reflection',density:2,placementRules:['floor-center','foreground-left','foreground-right']}},
  shrine:{id:'shrine',name:'Shrine',weight:8,description:'A small stone altar holds a candle stub and a receipt.',visual:{theme:'quiet-ritual',propPool:['small-altar','candle'],floorTreatment:'set-stone',wallTreatment:'carved-stone',atmosphere:'warm-candle',density:2,placementRules:['far-center','wall-center','floor-center']}},
  storage:{id:'storage',name:'Storage Room',weight:13,description:'Crates and barrels are stacked with municipal confidence.',visual:{theme:'municipal-storage',propPool:['wooden-crate','barrel','labeled-box'],floorTreatment:'scuffed',wallTreatment:'stacked-clutter',atmosphere:'dusty',density:4,placementRules:['far-left','far-right','mid-left','mid-right']}},
    camp:{id:'camp',name:'Abandoned Camp',weight:8,description:'A fire burns beside a bedroll and abandoned pack.',visual:{theme:'abandoned-camp',propPool:['campfire','bedroll','small-pack'],floorTreatment:'ash-marked',wallTreatment:'sheltered-stone',atmosphere:'cold-embers',density:3,placementRules:['floor-center','far-left','mid-right']}},
  market:{id:'market',name:'Kobold Market',weight:5,minDepth:2,description:'An improvised stall, baskets, and a hand-lettered sign fill the chamber.',visual:{theme:'improvised-market',propPool:['market-stall','market-basket','market-sign'],floorTreatment:'busy-stone',wallTreatment:'hung-signs',atmosphere:'lantern-warm',density:4,placementRules:['far-left','far-center','far-right','mid-left','mid-right']}},
  library:{id:'library',name:'Library',weight:7,minDepth:2,description:'Bookshelves line parts of the chamber; a labeled stone sits among the books.',visual:{theme:'stone-library',propPool:['bookshelf','book-stack','labeled-stone'],floorTreatment:'quiet-stone',wallTreatment:'shelved',atmosphere:'still',density:3,placementRules:['far-left','far-right','wall-center','floor-center']}},
  records:{id:'records',name:'Municipal Records Room',weight:5,minDepth:2,description:'Filing cabinets, archive boxes, and paper stacks are sorted by dampness.',visual:{theme:'municipal-records',propPool:['filing-cabinet','archive-box','paper-stack'],floorTreatment:'ordered-stone',wallTreatment:'cabinet-wall',atmosphere:'office-quiet',density:4,placementRules:['far-left','far-right','mid-left','mid-right','wall-center']}},
  spoons:{id:'spoons',name:'Room Full of Spoons',weight:2,description:'Spoons cover the floor in several neatly aligned piles.',visual:{theme:'spoon-room',propPool:['spoon-pile','single-spoon'],floorTreatment:'spoon-covered',wallTreatment:'bare-stone',atmosphere:'metallic-glint',density:4,placementRules:['floor-center','foreground-left','foreground-right','mid-left','mid-right']}},
  ordinary:{id:'ordinary',name:'Stone Passage',weight:30,description:'A plain stone passage continues, with a little rubble at its edge.',visual:{theme:'ordinary-stone',propPool:['stone-debris'],floorTreatment:'plain',wallTreatment:'plain-stone',atmosphere:'neutral',density:1,placementRules:['far-left','far-right']}}
};

// Choices and consequences stay in content data. game.js resolves only these small outcome primitives.
export const dungeonEvents={
  'vending-machine':{id:'vending-machine',weirdness:.55,title:'The Vending Machine',type:'Strange Object',minDepth:1,weight:7,rooms:['storage','records'],description:'A clean, ordinary vending machine is fitted into the stone wall. Its display reads: PLEASE MAKE A SELECTION.',repeatable:true,cooldown:7,choices:[{id:'buy',label:'Buy a tonic · 8 gold',requiresGold:8,outcomes:[{type:'gold',amount:-8},{type:'item',item:'healing-tonic',quantity:1},{type:'message',text:'The machine dispenses a tonic and prints a receipt dated tomorrow.'},{type:'townReaction',text:'Linna asks what a vending machine is. Then she files the receipt.'}]},{id:'shake',label:'Shake it',outcomes:[{type:'random',outcomes:[{weight:3,outcomes:[{type:'damage',amount:2},{type:'message',text:'A can falls out. It is dented but unopened.'}]},{weight:2,outcomes:[{type:'item',item:'bent-spoon',quantity:1},{type:'message',text:'A bent spoon drops into the coin return.'}]},{weight:1,outcomes:[{type:'damage',amount:3},{type:'message',text:'The machine shakes back.'}]}]}]},{id:'inspect',label:'Inspect the label',outcomes:[{type:'flag',flag:'vending-inspected'},{type:'message',text:'The manufacturer field reads: MUNICIPAL PROPERTY. The serial number is a date.'}]},{id:'leave',label:'Leave it alone',outcomes:[{type:'message',text:'The machine hums at a polite volume.'}]}]},
  'comfortable-chair':{id:'comfortable-chair',title:'The Extremely Comfortable Chair',type:'Rest Opportunity',minDepth:1,weight:6,rooms:['storage','shrine'],description:'A velvet chair sits alone in a stone chamber. It looks recently dusted.',repeatable:false,choices:[{id:'sit',label:'Sit down',outcomes:[{type:'random',outcomes:[{weight:3,outcomes:[{type:'heal',amount:6},{type:'message',text:'You rest. The chair supports you without asking questions.'}]},{weight:2,outcomes:[{type:'effect',name:'defense',value:2,encounters:2},{type:'message',text:'The chair’s excellent posture stays with you for two encounters.'}]},{weight:1,outcomes:[{type:'message',text:'You sit for a moment. Nothing happens. It is still a very good chair.'}]}]}]},{id:'inspect',label:'Inspect the upholstery',outcomes:[{type:'item',item:'cave-salt',quantity:1},{type:'message',text:'There is cave salt in one cushion. This may be a maintenance issue.'}]},{id:'leave',label:'Leave it alone',outcomes:[{type:'message',text:'The chair remains comfortable-looking.'}]}]},
  'suspicious-chest':{id:'suspicious-chest',title:'The Suspicious Chest',type:'Treasure',minDepth:1,weight:7,rooms:['storage'],description:'A chest sits directly in the middle of the room. The ceiling above it has a fresh crack.',repeatable:false,choices:[{id:'open',label:'Open it carefully',warning:'The cracked ceiling may shift.',outcomes:[{type:'random',outcomes:[{weight:3,outcomes:[{type:'gold',amount:9},{type:'item',item:'kobold-trinket',quantity:1},{type:'message',text:'The chest contains coins and a very small ledger.'}]},{weight:2,outcomes:[{type:'damage',amount:3},{type:'message',text:'A stone chip clips your shoulder as the lid opens.'}]},{weight:1,outcomes:[{type:'encounter',monster:'paper-mimic'},{type:'message',text:'The chest unfolds several filing-cabinet teeth.'}]}]}]},{id:'inspect',label:'Inspect the supports',outcomes:[{type:'flag',flag:'chest-inspected'},{type:'message',text:'The crack is old and the chest has no hinges on the inside. You leave it for now.'}]},{id:'leave',label:'Leave it',outcomes:[{type:'message',text:'The chest stays in the middle of the room, where it can be seen.'}]}]},
  'kobold-bake-sale':{id:'kobold-bake-sale',title:'Kobold Bake Sale',type:'Merchant',minDepth:1,weight:5,rooms:['market'],description:'Two kobolds have arranged pastries on a folding table. A handwritten sign says FUNDS FOR TUNNEL LIGHTING.',repeatable:true,cooldown:8,choices:[{id:'buy-pie',label:'Buy a pie · 6 gold',requiresGold:6,outcomes:[{type:'gold',amount:-6},{type:'item',item:'kobold-pie',quantity:1},{type:'message',text:'The pie is warm and grants a little extra defense for two fights.'}]},{id:'barter',label:'Trade one cave salt for a pie',requiresItem:{item:'cave-salt',quantity:1},outcomes:[{type:'removeItem',item:'cave-salt',quantity:1},{type:'item',item:'kobold-pie',quantity:1},{type:'message',text:'The kobolds inspect the salt, nod, and wrap a pie.'}]},{id:'ask',label:'Ask about the lighting fund',outcomes:[{type:'townReaction',text:'Juniper says the kobolds have been submitting receipts for tunnel lighting.'},{type:'message',text:'“The lighting is a separate budget,” says the smaller kobold.'}]},{id:'leave',label:'Leave the sale',outcomes:[{type:'message',text:'They resume arranging the pastries by diameter.'}]}]},
  'room-of-spoons':{id:'room-of-spoons',weirdness:.25,title:'The Room Full of Spoons',type:'Discovery',minDepth:1,weight:4,rooms:['spoons'],description:'Hundreds of spoons cover the floor. They are all facing the same direction.',repeatable:false,choices:[{id:'take',label:'Take one spoon',outcomes:[{type:'item',item:'bent-spoon',quantity:1},{type:'flag',flag:'spoons-counted'},{type:'unlockQuest',quest:'spoon-confirmation'},{type:'message',text:'You take a bent spoon. The others remain aligned.'}]},{id:'count',label:'Count them',outcomes:[{type:'flag',flag:'spoons-counted'},{type:'unlockQuest',quest:'spoon-confirmation'},{type:'message',text:'You lose count at 214. The next spoon is labeled 216.'}]},{id:'inspect-certified',label:'Show the Officially Sanctioned Spoon',requiresItem:{item:'official-spoon',quantity:1},outcomes:[{type:'flag',flag:'municipal-spoon-seen'},{type:'message',text:'The nearest spoon turns over. It has the same stamp, but an earlier date.'}]},{id:'leave',label:'Leave',outcomes:[{type:'message',text:'The spoons remain where they are.'}]}]},
  'lost-adventurer':{id:'lost-adventurer',title:'Lost Adventurer',type:'NPC',minDepth:1,weight:4,rooms:['camp','records'],description:'A tired delver insists they have been underground for twenty minutes. Their beard has a small bird nesting in it.',repeatable:false,choices:[{id:'offer-tonic',label:'Offer a healing tonic',requiresItem:{item:'healing-tonic',quantity:1},outcomes:[{type:'removeItem',item:'healing-tonic',quantity:1},{type:'gold',amount:5},{type:'townReaction',text:'Sal says someone returned from the hole with a bird in their beard. He does not ask follow-up questions.'},{type:'message',text:'They accept the tonic and give you five gold. “I will find the entrance soon.”'}]},{id:'ask',label:'Ask for directions',outcomes:[{type:'unlockQuest',quest:'warm-wall-survey'},{type:'message',text:'They point toward the warm wall and say it was not there yesterday.'}]},{id:'leave',label:'Leave them be',outcomes:[{type:'message',text:'They wave at a corridor that leads back the way you came.'}]}]},
  'very-small-door':{id:'very-small-door',weirdness:.7,title:'A Very Small Door',type:'Mystery',minDepth:1,weight:5,rooms:['library','records'],description:'A painted door, about as tall as a loaf of bread, is set into the wall.',repeatable:true,cooldown:8,choices:[{id:'knock',label:'Knock twice',outcomes:[{type:'flag',flag:'small-door-knocked'},{type:'unlockQuest',quest:'door-survey'},{type:'message',text:'Something on the other side knocks once, then moves a chair.'}]},{id:'listen',label:'Listen',outcomes:[{type:'flag',flag:'small-door-knocked'},{type:'unlockQuest',quest:'door-survey'},{type:'message',text:'You hear a kettle being set down. No one opens the door.'}]},{id:'leave-item',label:'Leave a mushroom',requiresFlag:'small-door-knocked',requiresItem:{item:'suspicious-mushroom',quantity:1},outcomes:[{type:'removeItem',item:'suspicious-mushroom',quantity:1},{type:'flag',flag:'small-door-receipt'},{type:'unlockQuest',quest:'door-followup'},{type:'message',text:'When you look again, the mushroom is gone. A tiny paper receipt remains.'}]},{id:'sanctioned-spoon',label:'Present the Officially Sanctioned Spoon',requiresItem:{item:'official-spoon',quantity:1},outcomes:[{type:'flag',flag:'small-door-second-response'},{type:'unlockQuest',quest:'door-second-response'},{type:'message',text:'A slot opens. The spoon is returned with a smaller receipt attached. It is dated tomorrow.'}]},{id:'leave',label:'Leave',outcomes:[{type:'message',text:'The small door remains closed.'}]}]},
  'snack-stand':{id:'snack-stand',weirdness:.45,title:'Underground Snack Stand',type:'Merchant',minDepth:2,weight:5,rooms:['market','storage'],description:'A snack stand is open under a hand-painted sign: HOT FOOD · EXACT CHANGE PREFERRED.',repeatable:true,cooldown:6,choices:[{id:'buy',label:'Buy a tonic · 15 gold',requiresGold:15,outcomes:[{type:'gold',amount:-15},{type:'item',item:'healing-tonic',quantity:1},{type:'message',text:'The tonic is chilled. The stand owner says this is the premium service.'}]},{id:'look',label:'Read the menu',outcomes:[{type:'message',text:'Today’s special is “food”. The price is listed as market conditions.'}]},{id:'leave',label:'Leave',outcomes:[{type:'message',text:'The cook wipes a clean counter.'}]}]},
  'warm-wall':{id:'warm-wall',title:'The Warm Wall',type:'Hazard',minDepth:1,weight:6,rooms:['flooded-chamber','storage','ordinary'],description:'A section of stone is warm to the touch. A thin orange line glows between two blocks.',repeatable:false,choices:[{id:'investigate',label:'Investigate the seam',warning:'Heat is escaping through the stone.',outcomes:[{type:'random',outcomes:[{weight:3,outcomes:[{type:'item',item:'earthworm-ember',quantity:1},{type:'discover',landmark:'warm-wall',label:'Warm Wall',icon:'≈'},{type:'questProgress',questType:'discover',target:'warm-wall'},{type:'unlockQuest',quest:'warm-wall-survey'},{type:'townReaction',text:'Linna has added “warm wall” to the inspection form. She has added a checkbox for “still warm”.'},{type:'message',text:'The seam opens onto a warm pocket in the rock. Something left an ember sac behind.'}]},{weight:2,outcomes:[{type:'damage',amount:3},{type:'discover',landmark:'warm-wall',label:'Warm Wall',icon:'≈'},{type:'message',text:'A puff of hot air singes you. The wall cools again.'}]},{weight:1,outcomes:[{type:'encounter',monster:'fireWorm'},{type:'message',text:'The wall exhales, then a fire-breathing earthworm follows.'}]}]}]},{id:'feel',label:'Feel the stone carefully',outcomes:[{type:'effect',name:'fireResistance',value:1,encounters:2},{type:'message',text:'The heat is mild. You learn where to put your hand for two encounters.'}]},{id:'leave',label:'Leave it',outcomes:[{type:'message',text:'The orange line remains visible as you go.'}]}]},
  'inspection-notice':{id:'inspection-notice',title:'Municipal Inspection Notice',type:'Environmental',minDepth:1,weight:5,rooms:['records','library'],description:'An official notice is pinned to the stone: “Please report stair irregularities to the nearest office.”',repeatable:false,choices:[{id:'read',label:'Read the fine print',outcomes:[{type:'item',item:'survey-notes',quantity:1},{type:'townReaction',text:'Linna says the notice was filed correctly, though no one remembers posting it.'},{type:'message',text:'The notice refers to an inspection scheduled for three years ago.'}]},{id:'print-copy',label:'Print an official copy',requiresItem:{item:'pocket-receipt-printer',quantity:1},outcomes:[{type:'item',item:'survey-notes',quantity:1},{type:'flag',flag:'notice-copy-printed'},{type:'message',text:'The printer produces a copy and a receipt for the copy. The copy is warmer.'}]},{id:'remove',label:'Take the notice down',outcomes:[{type:'item',item:'survey-notes',quantity:1},{type:'flag',flag:'notice-removed'},{type:'message',text:'The back is a map of stairs that do not appear on your map.'}]},{id:'leave',label:'Leave it posted',outcomes:[{type:'message',text:'The notice remains posted in accordance with policy.'}]}]},
  'abandoned-camp':{id:'abandoned-camp',title:'Abandoned Camp',type:'Discovery',minDepth:1,weight:6,rooms:['camp'],description:'A small camp is tucked behind a fallen screen. The kettle is cold; a set of careful survey notes is dry.',repeatable:false,choices:[{id:'search',label:'Search the supplies',outcomes:[{type:'item',item:'healing-tonic',quantity:1},{type:'item',item:'survey-notes',quantity:1},{type:'unlockQuest',quest:'camp-report'},{type:'townReaction',text:'Linna recognizes the survey notes and adds a report to the notice board.'},{type:'message',text:'You recover a tonic and survey notes. Someone packed in a hurry, but neatly.'}]},{id:'read',label:'Read the notes here',outcomes:[{type:'flag',flag:'camp-notes-read'},{type:'item',item:'survey-notes',quantity:1},{type:'unlockQuest',quest:'camp-report'},{type:'message',text:'The notes mention a stair inspection and a duck seen near the records room.'}]},{id:'leave',label:'Leave camp undisturbed',outcomes:[{type:'message',text:'The camp remains dry and undisturbed.'}]}]},
  'talking-statue':{id:'talking-statue',weirdness:.5,title:'Talking Statue',type:'Mystery',minDepth:2,weight:3,rooms:['shrine'],description:'A stone face asks, “Do you have a little salt?” Its expression does not change.',repeatable:false,choices:[{id:'give-salt',label:'Give one cave salt',requiresItem:{item:'cave-salt',quantity:1},outcomes:[{type:'removeItem',item:'cave-salt',quantity:1},{type:'heal',amount:4},{type:'message',text:'“Thank you,” says the statue. It sounds relieved.'}]},{id:'ask',label:'Ask why',outcomes:[{type:'message',text:'“Soup,” it says. The statue has no mouth movement.'}]},{id:'leave',label:'Leave',outcomes:[{type:'message',text:'The statue returns to not speaking.'}]}]},
  'wishing-well':{id:'wishing-well',weirdness:.4,title:'Underground Wishing Well',type:'Choice',minDepth:1,weight:4,rooms:['flooded-chamber','shrine'],description:'A stone well is set into the floor. The water reflects a sky you cannot see.',repeatable:false,choices:[{id:'wish',label:'Throw in 3 gold',requiresGold:3,outcomes:[{type:'gold',amount:-3},{type:'random',outcomes:[{weight:3,outcomes:[{type:'gold',amount:7},{type:'message',text:'A coin lands back in your palm. It is from a town that no longer exists.'}]},{weight:2,outcomes:[{type:'effect',name:'attack',value:1,encounters:2},{type:'message',text:'The water ripples. You feel unusually certain for two encounters.'}]},{weight:2,outcomes:[{type:'message',text:'The well accepts the coin and offers no comment.'}]}]}]},{id:'retrieve',label:'Retrieve a visible coin',outcomes:[{type:'gold',amount:1},{type:'flag',flag:'well-retrieved'},{type:'message',text:'You retrieve one coin. The reflection looks briefly disappointed.'}]},{id:'leave',label:'Leave it',outcomes:[{type:'message',text:'The water remains still.'}]}]},
  'the-duck':{id:'the-duck',weirdness:.35,title:'The Duck',type:'Discovery',minDepth:1,weight:6,rooms:['flooded-chamber','ordinary'],description:'There is a duck standing in the corridor. It seems to have been expecting you.',repeatable:false,choices:[{id:'greet',label:'Greet the duck',outcomes:[{type:'flag',flag:'duck-greeted'},{type:'unlockQuest',quest:'duck-notice'},{type:'message',text:'The duck nods once and walks through a wall.'}]},{id:'whistle',label:'Blow the Anti-Goose Whistle',requiresItem:{item:'anti-goose-whistle',quantity:1},outcomes:[{type:'flag',flag:'goose-whistle-heard'},{type:'message',text:'The duck looks toward a distant corridor. Something there honks in disagreement.'}]},{id:'offer',label:'Offer it a mushroom',requiresItem:{item:'suspicious-mushroom',quantity:1},outcomes:[{type:'removeItem',item:'suspicious-mushroom',quantity:1},{type:'flag',flag:'duck-greeted'},{type:'flag',flag:'duck-receipt'},{type:'unlockQuest',quest:'duck-notice'},{type:'effect',name:'retreatBonus',value:8,encounters:2},{type:'message',text:'The duck accepts the mushroom. A wet receipt is left on the floor.'}]},{id:'ring',label:'Ask what the ring is warm about',requiresEffect:'duckSense',outcomes:[{type:'flag',flag:'duck-ring-clue'},{type:'message',text:'The ring warms. The duck looks toward a wall and declines to clarify.'}]},{id:'leave',label:'Leave it alone',outcomes:[{type:'message',text:'The duck stays where it is, watching the corridor.'}]}]},
  'collapsed-passage':{id:'collapsed-passage',title:'Collapsed Passage',type:'Hazard',minDepth:2,weight:4,rooms:['storage','flooded-chamber'],description:'Loose stones block a side passage. The ceiling above them looks stable, but only just.',repeatable:false,choices:[{id:'clear',label:'Try to clear it',warning:'You may scrape yourself on the stone.',outcomes:[{type:'skillCheck',stat:'str',threshold:5,success:[{type:'item',item:'kobold-trinket',quantity:1},{type:'flag',flag:'passage-cleared'},{type:'message',text:'You clear a narrow gap and find a kobold trinket.'}],failure:[{type:'damage',amount:2},{type:'message',text:'The stones shift. You stop before the ceiling follows.'}]}]},{id:'shield',label:'Brace the stones with a shield',requiresItem:{item:'wooden-shield',quantity:1},outcomes:[{type:'item',item:'kobold-trinket',quantity:1},{type:'flag',flag:'passage-cleared'},{type:'message',text:'Your shield props up the loose slab. A small gap opens onto a kobold trinket.'}]},{id:'leave',label:'Leave the passage',outcomes:[{type:'message',text:'The main corridor remains open.'}]}]},
  'giant-stone-face':{id:'giant-stone-face',title:'A Giant Stone Face',type:'Landmark',minDepth:1,weight:2,weirdness:.75,rooms:['ordinary','library'],description:'A giant face is carved into the far wall. Its eyes are looking at an adjacent wall.',repeatable:false,choices:[{id:'record',label:'Record the landmark',outcomes:[{type:'discover',landmark:'giant-stone-face',label:'Stone Face',icon:'◉'},{type:'questProgress',questType:'discover',target:'giant-stone-face'},{type:'unlockQuest',quest:'landmark-report'},{type:'townReaction',text:'Linna asks whether the stone face has a permit. She makes a note to check.'},{type:'message',text:'The face is recorded on your map. The other wall remains its focus.'}]},{id:'ask',label:'Ask it a question',outcomes:[{type:'message',text:'The face does not answer. It continues looking at the wall.'}]},{id:'leave',label:'Leave',outcomes:[{type:'message',text:'The face stays carved into the wall.'}]}]},
  'sleeping-slime':{id:'sleeping-slime',title:'A Sleeping Pocket Slime',type:'Creature',minDepth:1,weight:5,rooms:['mushroom-room','storage'],description:'A pocket slime is asleep beside a dry boot. It does not seem hostile.',repeatable:false,choices:[{id:'sneak',label:'Sneak past',outcomes:[{type:'message',text:'You step quietly around it. The slime snores once.'}]},{id:'inspect',label:'Inspect the boot',outcomes:[{type:'item',item:'cave-salt',quantity:1},{type:'message',text:'There is cave salt in the boot. The slime remains asleep.'}]},{id:'attack',label:'Attack the slime',warning:'It will wake up angry.',outcomes:[{type:'encounter',monster:'pocketSlime'},{type:'message',text:'The slime wakes and bounces toward you.'}]}]},
  'odor-survey':{id:'odor-survey',title:'Air Quality Sampling Point',type:'Discovery',minDepth:2,weight:3,weirdness:.65,rooms:['storage','flooded-chamber'],description:'A municipal sample jar sits beside a handwritten note: “Do not open indoors.”',repeatable:true,cooldown:12,choices:[{id:'collect',label:'Seal a sample',outcomes:[{type:'item',item:'condensed-stink',quantity:1},{type:'unlockQuest',quest:'air-quality-sample'},{type:'flag',flag:'odor-sample-collected'},{type:'message',text:'The jar seals with a small, apologetic click.'}]},{id:'freshen',label:'Use Air Freshener',requiresItem:{item:'air-freshener',quantity:1},outcomes:[{type:'removeItem',item:'air-freshener',quantity:1},{type:'townReaction',text:'Linna records that the sample point was briefly tolerable.'},{type:'message',text:'The odor recedes. The note now says “use outdoors if possible.”'}]},{id:'leave',label:'Leave it sealed',outcomes:[{type:'message',text:'The jar remains sealed, and the note remains stern.'}]}]},
  'apple-anomaly':{id:'apple-anomaly',title:'Unusually Large Apple Core',type:'Discovery',minDepth:2,weight:3,weirdness:.55,rooms:['storage','mushroom-room'],description:'A large apple core is tucked behind a crate. It has been cored from the outside.',repeatable:true,cooldown:10,choices:[{id:'inspect',label:'Inspect the core',outcomes:[{type:'flag',flag:'apple-core-inspected'},{type:'unlockQuest',quest:'apple-problem'},{type:'item',item:'bad-seed',quantity:1},{type:'message',text:'The core contains a seed and no reasonable explanation.'}]},{id:'use-corer',label:'Use the Suspicious Apple Corer',requiresItem:{item:'suspicious-apple-corer',quantity:1},outcomes:[{type:'flag',flag:'apple-core-inspected'},{type:'unlockQuest',quest:'apple-problem'},{type:'item',item:'bad-seed',quantity:2},{type:'message',text:'The corer fits perfectly. This is not comforting.'}]},{id:'leave',label:'Leave it',outcomes:[{type:'message',text:'The core remains behind the crate.'}]}]},
  'porkscrew-impression':{id:'porkscrew-impression',title:'A Corkscrew-Shaped Scuff',type:'Discovery',minDepth:2,weight:2,weirdness:.45,rooms:['ordinary','storage'],description:'A spiral groove crosses the floor and stops at a normal-looking wall.',repeatable:true,cooldown:10,choices:[{id:'measure',label:'Measure the groove',outcomes:[{type:'unlockQuest',quest:'pip-inventory'},{type:'item',item:'curly-tail',quantity:1},{type:'message',text:'The measurements suggest a pig-shaped source. Your notes disagree.'}]},{id:'unspiral',label:'Apply the Pork Unspiraler',requiresItem:{item:'pork-unspiraler',quantity:1},outcomes:[{type:'flag',flag:'porkscrew-unspiraled'},{type:'message',text:'The groove straightens by a few centimeters, then turns left.'}]},{id:'leave',label:'Leave',outcomes:[{type:'message',text:'The groove remains technically measurable.'}]}]}
};

export const innEvents={
  'well-rested':{id:'well-rested',name:'Well Rested',weight:5,description:'The room was quiet, the blankets were level, and the ceiling stayed where it belonged.',effect:{type:'xp-bonus',percent:10,battles:3}},
  'good-breakfast':{id:'good-breakfast',name:'Good Breakfast',weight:3,description:'Sal finds a second piece of toast that is not technically part of the room rate.',effect:{type:'temporary',name:'defense',value:1,encounters:2}},
  'quiet-night':{id:'quiet-night',name:'Quiet Night',weight:3,description:'No pipes spoke to you. Your guard feels steadier for a while.',effect:{type:'temporary',name:'defense',value:1,encounters:2}},
  'surprising-mattress':{id:'surprising-mattress',name:'Surprisingly Good Mattress',weight:2,description:'You wake up prepared to leave a room quickly.',effect:{type:'temporary',name:'retreatBonus',value:5,encounters:2}},
  'terrible-pillow':{id:'terrible-pillow',name:'Terrible Pillow',weight:3,description:'The pillow was filled with something that has a case number.',effect:{type:'flavor'}},
  'quiet-floor':{id:'quiet-floor',name:'Quiet Floor',weight:3,description:'Nobody in the next room made a sound. You feel less likely to be surprised by minor ailments.',effect:{type:'temporary',name:'statusResistance',value:.15,encounters:2}},
  'squeaky-bed':{id:'squeaky-bed',name:'Squeaky Bed',weight:3,description:'The bed squeaks whenever you consider changing sides.',effect:{type:'flavor'}},
  'mystery-snack':{id:'mystery-snack',name:'Mystery Snack',weight:2,description:'A wrapped snack is left beside the lamp. The label says “probably food.”',effect:{type:'item',item:'healing-tonic',quantity:1}},
  'free-coffee':{id:'free-coffee',name:'Free Coffee',weight:2,description:'Sal pours a small coffee. You feel ready to move briskly for a while.',effect:{type:'temporary',name:'agility',value:1,encounters:2}},
  'wrong-room':{id:'wrong-room',name:'Wrong Room',weight:2,description:'You wake in the correct room. The key was for a different room.',effect:{type:'flavor'}},
  'bed-coin':{id:'bed-coin',name:'Coin Under the Bed',weight:2,description:'You find one gold piece under the bed. The innkeeper says it was not included.',effect:{type:'gold',amount:1}},
  'clean-towels':{id:'clean-towels',name:'Unexpectedly Clean Towels',weight:2,description:'The towels are clean and dry. Your guard feels a little steadier.',effect:{type:'temporary',name:'defense',value:1,encounters:2}},
  'pipes-knock':{id:'pipes-knock',name:'Pipes Knock Twice',weight:2,description:'The pipes knock twice, then stop when you knock back.',effect:{type:'flavor'}},
  'breakfast-stamp':{id:'breakfast-stamp',name:'Breakfast Loyalty Stamp',weight:2,description:'Sal stamps a card for a breakfast you have already eaten.',effect:{type:'temporary',name:'retreatBonus',value:3,encounters:2}}
};
