// The normal-game cap and the QA preview range are intentionally separate.
export const CURRENT_PLAYABLE_MAX_FLOOR=3;
export const QA_PREVIEW_MAX_FLOOR=7;

export const depthBands=Object.freeze([
  {id:'upper-works',minFloor:1,maxFloor:3,range:'1–3',name:'Upper Works',monster:'Familiar creatures, early Porkscrew and Rotten Apple; Poo Gas remains uncommon',loot:'Common materials, occasional Uncommon tools; Strange remains rare',events:'Municipal surveys, spoons, camp and first impossible objects',content:{npc:'Pip and Nell at normal rates',rooms:'Ordinary stone with occasional named rooms',rareLootMultiplier:1,eventWeirdness:1}},
  {id:'old-foundations',minFloor:4,maxFloor:7,range:'4–7',name:'Old Foundations',monster:'More Heart-Attacks, trained variants and status attacks',loot:'Uncommon equipment appears more often; Rare remains possible but not routine; Strange stays uncommon',events:'More environmental risk and recurring visitor follow-ups',content:{npc:'Pip and Nell at normal rates; deeper follow-ups still need authored dialogue',rooms:'Storage, flooded, camp, records and library rooms weighted upward',rareLootMultiplier:1.15,eventWeirdness:1.15,enemyWeights:{'paper-mimic':1.55,'poo-gas':1.25,'heart-attack':1.2,skeleton:1.12,'fire-worm':1.08},roomWeights:{storage:1.55,'flooded-chamber':1.5,records:1.55,library:1.35,camp:1.3,ordinary:1.05,'mushroom-room':.85,market:.9,shrine:.95,spoons:.9},rarityWeights:{uncommon:1.35,rare:1.1,strange:1}}},
  {id:'forgotten-works',minFloor:8,maxFloor:12,range:'8–12',name:'Forgotten Works',monster:'Established families gain deeper attack pools; gas and mimic remain notable',loot:'Rare tools become plausible; Strange items remain sidegrades',events:'Landmarks and unusual room combinations',content:{npc:'Unusual traders are less scarce',rooms:'Library, shrine, market and spoon rooms weighted upward',rareLootMultiplier:1.3,eventWeirdness:1.3}},
  {id:'things-stop-making-sense',minFloor:13,maxFloor:20,range:'13–20',name:'Things Stop Making Sense',monster:'Higher threat with soft-capped stats and richer attack selection',loot:'More specialized choices rather than only larger numbers',events:'Civic and spatial anomalies carry more state hooks',content:{npc:'Rare visits, better emergency stock',rooms:'Nonordinary rooms favored; ordinary passages remain possible',rareLootMultiplier:1.45,eventWeirdness:1.5}},
  {id:'deep-hole',minFloor:21,maxFloor:Infinity,range:'21+',name:'Deep Hole',monster:'Diminishing stat growth; attack identity and status pressure matter',loot:'Specialized tools and contextual gear; Strange is not strictly stronger',events:'High weirdness; return decisions stay relevant',content:{npc:'Rare encounters',rooms:'Impossible combinations are more likely',rareLootMultiplier:1.6,eventWeirdness:1.7}}
]);

export function depthBandFor(floor){const value=Math.max(1,Math.floor(Number(floor)||1));return depthBands.find(band=>value>=band.minFloor&&value<=band.maxFloor)||depthBands.at(-1)}
export function roomWeightForDepth(room,floor){return Math.max(0,Number(room?.weight)||0)*(depthBandFor(floor).content.roomWeights?.[room?.id]??1)}
export function encounterWeightForDepth(row,monster,floor){return Math.max(0,Number(row?.weight)||0)*(depthBandFor(floor).content.enemyWeights?.[monster?.id]??1)}
export function lootRarityWeightForDepth(rarity,floor){return depthBandFor(floor).content.rarityWeights?.[rarity]??1}
