import {freshState,saveState,wallAt,INVENTORY_CAPACITY,EQUIPMENT_SLOTS,createFloorMap} from './state.js';
import {quests,items,monsters,lootTables,floorEncounterTable,dungeonNpcs,npcEncounterIds,trades,shopStock,rarities,dungeonEvents,roomTypes} from './data.js';

export let state=freshState();
export function setState(next){state=next;if(state?.player)recalculateStats()}
export function persist(){if(state?.meta)saveState(state)}
function random(){const d=state.dungeon;d.seed=(d.seed*48271)%2147483647;return d.seed/2147483647}
function owned(id){return state.inventory.filter(entry=>entry.id===id).reduce((n,entry)=>n+entry.quantity,0)}
export function countItem(id){return owned(id)}
export function inventoryUsed(){let total=0;for(const id of new Set(state.inventory.filter(x=>x.quantity>0).map(x=>x.id))){const def=items[id];total+=def?.stackable?Math.ceil(owned(id)/10):owned(id)}return total}
export function inventoryCapacity(){return state.settings?.inventoryCapacity||INVENTORY_CAPACITY}
export function canAddItem(id,quantity=1){if(!items[id])return false;const def=items[id],before=def.stackable?Math.ceil(owned(id)/10):owned(id),after=def.stackable?Math.ceil((owned(id)+quantity)/10):owned(id)+quantity;return inventoryUsed()+after-before<=inventoryCapacity()}
export function addItem(id,quantity=1){if(!canAddItem(id,quantity))return false;const def=items[id];if(def.stackable){let left=quantity;for(const entry of state.inventory.filter(x=>x.id===id)){const n=Math.min(10-entry.quantity,left);entry.quantity+=n;left-=n;if(!left)break}while(left>0){const n=Math.min(10,left);state.inventory.push({id,quantity:n});left-=n}}else for(let n=0;n<quantity;n++)state.inventory.push({id,quantity:1});persist();return true}
export function removeItem(id,quantity=1){if(owned(id)<quantity)return false;let left=quantity;for(const entry of [...state.inventory].filter(x=>x.id===id)){const take=Math.min(entry.quantity,left);entry.quantity-=take;left-=take;if(entry.quantity<=0)state.inventory=state.inventory.filter(x=>x!==entry);if(!left)break}persist();return true}
function equippedIds(){return Object.values(state.equipment||{}).filter(Boolean)}
function equipmentEffects(){const sum={};for(const id of equippedIds()){const def=items[id];if(!def)continue;for(const [key,value] of Object.entries(def.modifiers||{}))sum[key]=(sum[key]||0)+value}return sum}
export function temporaryEffect(name){return state.player?.temporaryEffects?.[name]?.value||0}
export function equippedEffect(name){return equippedIds().reduce((sum,id)=>sum+(items[id]?.effects?.[name]||0),0)+temporaryEffect(name)}
export function addTemporaryEffect(name,value,encounters=1){if(!state.player.temporaryEffects)state.player.temporaryEffects={};state.player.temporaryEffects[name]={value,remaining:Math.max(1,encounters)};persist()}
function tickTemporaryEffects(){for(const [name,effect] of Object.entries(state.player.temporaryEffects||{})){effect.remaining--;if(effect.remaining<=0)delete state.player.temporaryEffects[name]}}
export function recalculateStats(){const p=state.player;if(!p)return;const mod=equipmentEffects();p.str=(p.baseStr??p.str??1)+(mod.str||0);p.agi=(p.baseAgi??p.agi??1)+(mod.agility||0);p.mind=(p.baseMind??p.mind??1)+(mod.mind||0);p.vit=(p.baseVit??p.vit??1)+(mod.vitality||0);p.maxHp=Math.max(1,(p.baseMaxHp??p.maxHp??20)+(mod.hp||0));p.maxMp=Math.max(0,(p.baseMaxMp??p.maxMp??0)+(mod.mp||0));p.attack=Math.max(1,2+p.str+(mod.attack||0));p.defense=Math.max(0,Math.floor(p.vit/2)+(mod.defense||0));p.hp=Math.min(p.hp??p.maxHp,p.maxHp);p.mp=Math.min(p.mp??p.maxMp,p.maxMp)}
export function compareEquipment(id){const item=items[id];if(!item?.slot)return null;const currentId=state.equipment[item.slot],current=items[currentId];const keys=['attack','defense','hp','mp','str','agility','mind','vitality'];return {slot:item.slot,currentId,current,deltas:Object.fromEntries(keys.map(k=>[k,(item.modifiers?.[k]||0)-(current?.modifiers?.[k]||0)]).filter(([,v])=>v!==0))}}
export function startGame(name,cls){const s=freshState();const bases={Fighter:[4,2,1,4,24,4],Wizard:[1,2,4,2,17,12],Rogue:[2,4,2,2,19,6],Cleric:[2,1,3,4,22,9]};const [str,agi,mind,vit,hp,mp]=bases[cls]||bases.Fighter;s.player={name:name.trim()||'Delver',class:cls,level:1,xp:0,hp,mp,baseMaxHp:hp,baseMaxMp:mp,baseStr:str,baseAgi:agi,baseMind:mind,baseVit:vit,effects:{},temporaryEffects:{},turns:0};s.inventory=[{id:'rusty-sword',quantity:1},{id:'patched-coat',quantity:1},{id:'healing-tonic',quantity:2}];s.equipment={mainHand:'rusty-sword',body:'patched-coat'};state=s;recalculateStats();ensureFloorNpcs(1);persist()}
export function acceptQuest(id){if(state.quests.active.length>=5||!state.quests.available.includes(id))return false;state.quests.available=state.quests.available.filter(x=>x!==id);state.quests.active.push({id,progress:0});const q=quests[id],alreadyFound=q?.type==='loot'?owned(q.target)>=q.count:q?.type==='discover'?state.dungeon.landmarks.some(l=>l.id===q.target):false;if(alreadyFound)completeQuest(q);persist();return true}
export function completeQuest(q){if(state.quests.completed.includes(q.id))return;state.quests.active=state.quests.active.filter(x=>x.id!==q.id);state.quests.completed.push(q.id);state.town.gold+=q.reward.gold;grantXp(q.reward.xp)}
export function progress(type,target){for(const p of [...state.quests.active]){const q=quests[p.id];if(q?.type===type&&(q.target===target||q.target==='any')){p.progress++;if(p.progress>=q.count)completeQuest(q)}}persist()}
function ensureFloorNpcs(floor){const d=state.dungeon;if(d.npcs.some(n=>n.floor===floor))return;const map=d.map,spots=[];for(let y=1;y<map.height-1;y++)for(let x=1;x<map.width-1;x++){if(wallAt(d,x,y)||[1,5].includes(x)&&y===5||x===3&&y===4||x===4&&y===3||x===map.upStairs[0]&&y===map.upStairs[1]||x===map.downStairs[0]&&y===map.downStairs[1])continue;spots.push([x,y])}for(let i=spots.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[spots[i],spots[j]]=[spots[j],spots[i]]}npcEncounterIds.forEach((id,i)=>{const [x,y]=spots[i];d.npcs.push({id,floor,x,y,resolved:false})})}
function floorKey(floor=state.dungeon.floor){return String(floor)}
function cellKey(floor,x,y){return `${floor}:${x},${y}`}
function assignRoom(floor,x,y){const eligible=Object.values(roomTypes).filter(r=>(r.minDepth||1)<=floor),total=eligible.reduce((sum,r)=>sum+r.weight,0);let pick=random()*total,room=eligible.at(-1);for(const row of eligible){pick-=row.weight;if(pick<0){room=row;break}}state.dungeon.rooms[cellKey(floor,x,y)]=room.id;return room}
function selectEvent(floor,x,y){const d=state.dungeon,room=roomTypes[d.rooms[cellKey(floor,x,y)]],eligible=Object.values(dungeonEvents).filter(e=>floor>=(e.minDepth||1)&&floor<=(e.maxDepth||99)).filter(e=>{const previous=d.eventState[e.id];return !previous?.resolved&&(e.repeatable||!previous?.count)&&(!e.cooldown||!previous||d.encounterStep-previous.lastStep>=e.cooldown)});if(!eligible.length)return null;const rows=eligible.map(e=>({...e,rollWeight:e.weight*((e.rooms||[]).includes(room?.id)?2.5:1)*(1+(floor-1)*(e.weirdness??.1))})),total=rows.reduce((n,e)=>n+e.rollWeight,0);let pick=random()*total;for(const e of rows){pick-=e.rollWeight;if(pick<0)return e}return rows.at(-1)}
function openRandomEvent(floor,x,y){const event=selectEvent(floor,x,y);if(!event)return null;const d=state.dungeon;d.currentEventId=event.id;d.eventedCells.push(cellKey(floor,x,y));d.eventState[event.id]=d.eventState[event.id]||{count:0,lastStep:0,resolved:false};d.eventState[event.id].lastStep=d.encounterStep;persist();return event}
export function reveal(){const d=state.dungeon,k=`${d.x},${d.y}`,floor=floorKey();if(!d.explored.includes(`${floor}:${k}`))d.explored.push(`${floor}:${k}`);if(!d.visited[floor])d.visited[floor]=[];if(!d.visited[floor].includes(k))d.visited[floor].push(k);if(d.x===d.map.upStairs[0]&&d.y===d.map.upStairs[1])d.discoveredStairs=[...new Set([...(d.discoveredStairs||[]),`${floor}:up`])];if(d.x===d.map.downStairs[0]&&d.y===d.map.downStairs[1])d.discoveredStairs=[...new Set([...(d.discoveredStairs||[]),`${floor}:down`])]}
export function enterDungeon(){const d=state.dungeon;d.inDungeon=true;if(d.floor<1)d.floor=1;d.map=createFloorMap();d.x=1;d.y=5;d.facing=0;ensureFloorNpcs(d.floor);reveal();persist()}
export function returnTown(){const d=state.dungeon,deepest=d.deepestFloor||d.floor;d.inDungeon=false;d.currentNpcId=null;d.currentEventId=null;state.combat=null;d.floor=1;d.map=createFloorMap();d.x=1;d.y=5;if(deepest>=3)progress('return','3');persist()}
export function move(direction){const d=state.dungeon;if(state.combat)return 'Choose an action before moving.';if(d.currentNpcId||d.currentEventId)return 'Finish the encounter first.';const targetFacing=(d.facing+({forward:0,right:1,back:2,left:3}[direction]??0))%4,[dx,dy]=[[0,-1],[1,0],[0,1],[-1,0]][targetFacing],nx=d.x+dx,ny=d.y+dy,origin={x:d.x,y:d.y};if(wallAt(d,nx,ny)){d.lastMovement={direction,result:'blocked',from:origin,to:{x:nx,y:ny},facing:d.facing};persist();return "There's a wall there."}d.x=nx;d.y=ny;d.facing=targetFacing;d.lastMovement={direction,result:'moved',from:origin,to:{x:nx,y:ny},facing:d.facing};state.player.turns++;d.encounterStep=(d.encounterStep||0)+1;const floor=d.floor,key=cellKey(floor,nx,ny),newCell=!d.explored.includes(`${floor}:${nx},${ny}`)&&!d.explored.includes(`${nx},${ny}`);reveal();if(newCell&&!d.rooms[key])assignRoom(floor,nx,ny);const cacheId=`cache-${d.floor}-first`;if(floor===1&&nx===3&&ny===4&&!d.finds.includes(cacheId)){persist();return 'You spot a blue lunchbox and a suspiciously useful salt deposit.'}const visitor=d.npcs.find(n=>n.floor===floor&&!n.resolved&&n.x===nx&&n.y===ny);if(visitor){d.currentNpcId=visitor.id;persist();return `${dungeonNpcs[visitor.id].name} is waiting beside the wall.`}if(floor===1&&d.rat?.alive&&nx===d.rat.x&&ny===d.rat.y){beginCombat('rat',nx,ny);persist();return monsters.rat.encounterText}if(newCell&&!d.eventedCells.includes(key)){const eventChance=({1:.09,2:.13,3:.18})[floor]||.2,combatChance=({1:.13,2:.19,3:.25})[floor]||.27,roll=random();if(roll<eventChance){const event=openRandomEvent(floor,nx,ny);if(event)return event.description}else if(roll<eventChance+combatChance){const monsterId=selectMonster();beginCombat(monsterId,nx,ny);persist();return monsters[monsterId].encounterText}}persist();const room=roomTypes[d.rooms[key]];return room&&room.id!=='ordinary'?room.description:(floor>=2?'The stone groans somewhere below.':'Your boots disturb the dust.')}
function selectMonster(){const rows=(floorEncounterTable[state.dungeon.floor]||floorEncounterTable[3]).filter(row=>monsters[row.id]?.minDepth<=state.dungeon.floor);const total=rows.reduce((n,r)=>n+r.weight,0);let pick=random()*total;for(const row of rows){pick-=row.weight;if(pick<0)return row.id}return rows.at(-1).id}
function beginCombat(monsterId,x,y){const m=monsters[monsterId];state.combat={monsterId,hp:m.hp,maxHp:m.hp,x,y,guard:false,burnTurns:0};state.dungeon.encounters.push({id:`${state.dungeon.floor}:${x},${y}:${state.dungeon.encounterStep}`,monsterId,cleared:false})}
function grantXp(amount){const p=state.player;p.xp+=amount;while(p.xp>=p.level*25){p.xp-=p.level*25;p.level++;p.baseMaxHp+=2;p.baseMaxMp+=1;p.baseVit+=1;p.hp+=2;p.mp+=1}recalculateStats()}
function rollLoot(monster){const table=lootTables[monster.lootTable]||[];if(!table.length)return 'It leaves nothing worth carrying.';const rarityMult=1+equippedEffect('lootBonus')+(state.dungeon.floor-1)*.12;const rows=table.map(e=>{const rarity=items[e.item]?.rarity||'common',rarityFactor=(rarities[rarity]?.weight||62)/62;return {...e,weight:e.weight*rarityFactor*(rarity==='rare'||rarity==='strange'?rarityMult:1)}});const total=rows.reduce((n,e)=>n+e.weight,0);let pick=random()*total;let chosen=rows.at(-1);for(const row of rows){pick-=row.weight;if(pick<0){chosen=row;break}}const qty=chosen.min||1;if(!addItem(chosen.item,qty)){state.dungeon.groundLoot.push({floor:state.dungeon.floor,x:state.dungeon.x,y:state.dungeon.y,item:chosen.item,quantity:qty});return ` Your pack is full; ${items[chosen.item].name} stays on the floor.`}progress('loot',chosen.item);return ` Loot: ${items[chosen.item].name}.`}
function enemyTurn(){const c=state.combat;if(!c)return '';const m=monsters[c.monsterId];let strikes=m.behavior?.multiStrike||1,damage=0;for(let i=0;i<strikes;i++){let hit=Math.max(1,m.attack-state.player.defense-temporaryEffect('defense')-(c.guard?2:0));if(m.behavior?.criticalChance&&random()<m.behavior.criticalChance)hit+=m.attack;damage+=hit}c.guard=false;state.player.hp=Math.max(0,state.player.hp-damage);let text=` ${m.name} hits for ${damage}.`;if(m.behavior?.burnChance&&random()<m.behavior.burnChance){const resistance=equippedEffect('fireResistance');const turns=Math.max(0,(m.behavior.burnTurns||1)-resistance);if(turns){state.player.effects.burn={turns,damage:2};text+=' You are singed.'}}if(state.player.hp<=0){state.player.hp=1;returnTown();text+=' The delvers’ office brings you back with one HP and a new form.'}return text}
function lootReward(monster){const d=state.dungeon,p=state.player;const gold=Math.floor(monster.gold[0]+random()*(monster.gold[1]-monster.gold[0]+1)+(d.floor-1)*2);state.town.gold+=gold;grantXp(monster.xp+(d.floor-1)*3);progress('kill',monster.id);progress('kill','any');const drop=rollLoot(monster);return ` ${gold} gold.${drop}`}
export function attack(){const c=state.combat;if(!c)return '';const m=monsters[c.monsterId];let message='';if(m.behavior?.evadeChance&&random()<m.behavior.evadeChance)message=`${m.name} evades.`;else{const vsGoose=c.monsterId==='kungFuGoose'?equippedEffect('vsGoose'):0;const damage=Math.max(1,state.player.attack+temporaryEffect('attack')+vsGoose-m.defense);c.hp-=damage;message=`You hit the ${m.name} for ${damage}.`;if(c.hp<=0){state.combat=null;const encounter=state.dungeon.encounters.at(-1);if(encounter)encounter.cleared=true;message+=` ${m.name} is defeated.`+lootReward(m);tickTemporaryEffects();persist();return message}}message+=enemyTurn()+tickBurn();persist();return message}
export function defend(){if(!state.combat)return 'There is nothing to defend against.';state.combat.guard=true;const message=`You brace against ${monsters[state.combat.monsterId].name}.`+enemyTurn()+tickBurn();persist();return message}
function tickBurn(){const burn=state.player.effects?.burn;if(!burn)return '';state.player.hp=Math.max(0,state.player.hp-burn.damage);burn.turns--;if(burn.turns<=0)delete state.player.effects.burn;if(state.player.hp<=0){state.player.hp=1;returnTown();return ' The burn sends you back to town at one HP.'}return ` Burn damage: ${burn.damage}.`}
export function useItem(id){const item=items[id];if(!item?.effect||!owned(id))return 'You do not have that usable item.';if(item.effect.type==='heal'){state.player.hp=Math.min(state.player.maxHp,state.player.hp+item.effect.amount);removeItem(id,1);const enemy=state.combat?enemyTurn():'';const burn=tickBurn();persist();return `You use ${item.name}.${enemy}${burn}`}if(item.effect.type==='buff'){removeItem(id,1);addTemporaryEffect(item.effect.name,item.effect.value,item.effect.encounters);const enemy=state.combat?enemyTurn():'';const burn=tickBurn();persist();return `You use ${item.name}. ${item.effect.name} improves for ${item.effect.encounters} encounters.${enemy}${burn}`}return 'Nothing happens.'}
export function useTonic(){return useItem('healing-tonic')}
export function equipItem(id){const item=items[id];if(!item?.slot||!owned(id))return {ok:false,message:'That item cannot be equipped.'};if(item.classes&&!item.classes.includes(state.player.class))return {ok:false,message:`${item.name} is limited to ${item.classes.join(' or ')}.`};state.equipment[item.slot]=id;recalculateStats();persist();return {ok:true,message:`Equipped ${item.name}.`}}
export function unequipSlot(slot){if(!EQUIPMENT_SLOTS.includes(slot)||!state.equipment[slot])return false;delete state.equipment[slot];recalculateStats();persist();return true}
export function buyItem(id,priceOverride=null){const item=items[id];if(!item||!shopStock.includes(id))return {ok:false,message:'That item is not on Juniper’s shelf.'};if(item.classes&&!item.classes.includes(state.player.class))return {ok:false,message:`${item.name} is limited to ${item.classes.join(' or ')}.`};const price=priceOverride??item.buyValue;if(state.town.gold<price)return {ok:false,message:'Not enough gold.'};if(!canAddItem(id,1))return {ok:false,message:'Your pack is full. Sell something or clear a slot first.'};state.town.gold-=price;addItem(id,1);return {ok:true,message:`Bought ${item.name} for ${price} gold.`}}
export function salePrice(id){const item=items[id];return Math.max(1,Math.floor((item?.sellValue||0)*(1+equippedEffect('sellBonus'))))}
export function sellItem(id){const item=items[id];if(!item||!owned(id)||item.questItem)return {ok:false,message:'That item cannot be sold.'};if(equippedIds().includes(id))return {ok:false,message:'Unequip it before selling.'};const price=salePrice(id);removeItem(id,1);state.town.gold+=price;persist();return {ok:true,message:`Sold ${item.name} for ${price} gold.`}}
export function canTrade(trade){return trade.requires.every(req=>owned(req.item)>=req.quantity)&&state.town.gold>=trade.gold&&trade.gives.every(g=>canAddItem(g.item,g.quantity))}
export function completeTrade(tradeId){const trade=trades[tradeId];if(!trade||!canTrade(trade))return {ok:false,message:'The offer is not ready. Check the goods, gold, and pack space.'};for(const req of trade.requires)removeItem(req.item,req.quantity);state.town.gold-=trade.gold;for(const g of trade.gives)addItem(g.item,g.quantity);persist();return {ok:true,message:`Trade complete: ${trade.title}.`}}
export function buyNpcStock(npcId,itemId){const npc=dungeonNpcs[npcId],item=items[itemId];if(!npc?.stock?.includes(itemId)||!item)return {ok:false,message:'That item is not offered.'};const price=item.buyValue*npc.priceMultiplier;if(state.town.gold<price)return {ok:false,message:'Not enough gold.'};if(!canAddItem(itemId,1))return {ok:false,message:'Your pack is full.'};state.town.gold-=price;addItem(itemId,1);return {ok:true,message:`Bought ${item.name} for ${price} gold.`}}
export function closeNpc(){const npc=state.dungeon.npcs.find(n=>n.floor===state.dungeon.floor&&n.id===state.dungeon.currentNpcId&&n.x===state.dungeon.x&&n.y===state.dungeon.y);if(npc)npc.resolved=true;state.dungeon.currentNpcId=null;persist()}
export function descend(){const d=state.dungeon;if(d.x!==d.map.downStairs[0]||d.y!==d.map.downStairs[1])return 'Find the lower stair first.';if(d.floor>=3)return 'The stairs end at a sealed municipal door. For now.';d.floor++;d.deepestFloor=Math.max(d.deepestFloor||1,d.floor);d.map=createFloorMap();d.x=d.map.upStairs[0];d.y=d.map.upStairs[1];d.facing=2;ensureFloorNpcs(d.floor);reveal();persist();return `You descend to level ${d.floor}. The air is warmer and the prices, presumably, are worse.`}
export function ascend(){const d=state.dungeon;if(d.x!==d.map.upStairs[0]||d.y!==d.map.upStairs[1])return 'Find the upper stair first.';if(d.floor===1){returnTown();return 'You climb back to town.'}d.floor--;d.map=createFloorMap();d.x=d.map.downStairs[0];d.y=d.map.downStairs[1];d.facing=0;reveal();persist();return `You climb to level ${d.floor}.`}
function retreatChance(enemySpeed=0){return Math.max(.2,Math.min(.9,.62+state.player.agi*.035+equippedEffect('retreatBonus')/100-enemySpeed*.045-(state.dungeon.floor-1)*.05))}
export function retreatChancePercent(){const c=state.combat,enemySpeed=c?monsters[c.monsterId].speed:0;return Math.round(retreatChance(enemySpeed)*100)}
export function retreat(){const c=state.combat,enemySpeed=c?monsters[c.monsterId].speed:0,chance=retreatChance(enemySpeed);state.player.turns++;if(random()<chance){if(c){const name=monsters[c.monsterId].name;state.combat=null;tickTemporaryEffects();persist();return {ok:true,message:`You escape ${name}.`}}returnTown();return {ok:true,message:'You make it back to town with your pack intact.'}}if(c){const msg=`Retreat failed (${Math.round(chance*100)}% chance).`+enemyTurn()+tickBurn();persist();return {ok:false,message:msg}}const threshold=({1:.12,2:.2,3:.28})[state.dungeon.floor]||.3;if(random()<threshold){const id=selectMonster();beginCombat(id,state.dungeon.x,state.dungeon.y);persist();return {ok:false,message:`Retreat failed (${Math.round(chance*100)}% chance). Your delay draws ${monsters[id].name}.`}}persist();return {ok:false,message:`Retreat failed (${Math.round(chance*100)}% chance). The passage echoes behind you.`}}
export function collectFind(){const d=state.dungeon,cacheId=`cache-${d.floor}-first`;if(d.floor!==1||d.x!==3||d.y!==4||d.finds.includes(cacheId))return {ok:false,message:'Nothing else is here.'};const awards=[['blue-lunchbox',1],['stone-chip',1],['cave-salt',1]];const full=awards.filter(([id,q])=>!canAddItem(id,q));if(full.length)return {ok:false,message:'Your pack is full. Make room before collecting this cache.'};for(const [id,q] of awards)addItem(id,q);d.finds.push(cacheId);d.lootTaken=true;progress('loot','lunchbox');progress('loot','stone');persist();return {ok:true,message:'You recover Mara’s lunchbox, a stone chip, and some cave salt.'}}
export function collectGroundLoot(index){const d=state.dungeon,drop=d.groundLoot[index];if(!drop||drop.floor!==d.floor||drop.x!==d.x||drop.y!==d.y)return {ok:false,message:'There is no loose loot here.'};if(!canAddItem(drop.item,drop.quantity))return {ok:false,message:'Your pack is full. Make room before collecting it.'};addItem(drop.item,drop.quantity);progress('loot',drop.item);d.groundLoot.splice(index,1);persist();return {ok:true,message:`Collected ${items[drop.item].name}.`}}
function applyOutcome(outcome,messages){const d=state.dungeon;switch(outcome.type){case 'message':messages.push(outcome.text);break;case 'gold':d && (state.town.gold=Math.max(0,state.town.gold+outcome.amount));break;case 'item':if(!addItem(outcome.item,outcome.quantity||1))d.groundLoot.push({floor:d.floor,x:d.x,y:d.y,item:outcome.item,quantity:outcome.quantity||1});else progress('loot',outcome.item);break;case 'removeItem':removeItem(outcome.item,outcome.quantity||1);break;case 'heal':state.player.hp=Math.min(state.player.maxHp,state.player.hp+outcome.amount);break;case 'damage':state.player.hp=Math.max(1,state.player.hp-outcome.amount);break;case 'effect':addTemporaryEffect(outcome.name,outcome.value,outcome.encounters);break;case 'flag':d.eventFlags[outcome.flag]=true;break;case 'townReaction':state.town.reactions=[...(state.town.reactions||[]),outcome.text].slice(-6);break;case 'unlockQuest':{const q=outcome.quest,known=[...state.quests.available,...state.quests.completed,...state.quests.active.map(x=>x.id)];if(quests[q]&&!known.includes(q))state.quests.available.push(q);break}case 'questProgress':progress(outcome.questType,outcome.target);break;case 'discover':if(!d.landmarks.some(l=>l.id===outcome.landmark&&l.floor===d.floor)){d.landmarks.push({id:outcome.landmark,label:outcome.label,icon:outcome.icon,floor:d.floor,x:d.x,y:d.y});d.eventFlags[`landmark:${outcome.landmark}`]=true}break;case 'room':d.rooms[cellKey(d.floor,d.x,d.y)]=outcome.room;break;case 'encounter':{const key=monsters[outcome.monster]?outcome.monster:Object.keys(monsters).find(id=>monsters[id].id===outcome.monster);if(key){d.currentEventId=null;beginCombat(key,d.x,d.y)}break}case 'random':{const rows=outcome.outcomes||[],total=rows.reduce((n,r)=>n+r.weight,0);let pick=random()*total;for(const row of rows){pick-=row.weight;if(pick<0){applyOutcomes(row.outcomes,messages);break}}break}case 'skillCheck':{const success=(state.player[outcome.stat]||0)>=(outcome.threshold||0);applyOutcomes(success?outcome.success:outcome.failure,messages);break}}}
function applyOutcomes(outcomes,messages){for(const outcome of outcomes||[])applyOutcome(outcome,messages)}
export function resolveDungeonEvent(eventId,choiceId){const d=state.dungeon,event=dungeonEvents[eventId];if(!event||d.currentEventId!==eventId)return {ok:false,message:'That event is no longer here.'};const choice=event.choices.find(c=>c.id===choiceId);if(!choice)return {ok:false,message:'That choice is not available.'};if(choice.requiresGold&&state.town.gold<choice.requiresGold)return {ok:false,message:'You do not have enough gold.'};if(choice.requiresItem&&owned(choice.requiresItem.item)<choice.requiresItem.quantity)return {ok:false,message:`You need ${choice.requiresItem.quantity} ${items[choice.requiresItem.item].name}.`};if(choice.requiresFlag&&!d.eventFlags[choice.requiresFlag])return {ok:false,message:'You have not discovered what this choice needs.'};if(choice.requiresQuest&&!state.quests.active.some(q=>q.id===choice.requiresQuest))return {ok:false,message:'That choice requires an active quest.'};const messages=[];applyOutcomes(choice.outcomes,messages);d.currentEventId=null;const record=d.eventState[eventId]||(d.eventState[eventId]={count:0,lastStep:d.encounterStep,resolved:false});record.count++;record.resolved=!event.repeatable;d.eventHistory.push({id:eventId,choice:choiceId,floor:d.floor,step:d.encounterStep});persist();return {ok:true,message:messages.join(' ')||'You continue on.'}}
export function triggerEvent(id){if(!dungeonEvents[id])return false;state.dungeon.currentEventId=id;state.dungeon.inDungeon=true;persist();return true}
export function triggerRandomEvent(){state.dungeon.inDungeon=true;const event=openRandomEvent(state.dungeon.floor,state.dungeon.x,state.dungeon.y);return event?.id||null}
export function revealLandmark(id){const event=Object.values(dungeonEvents).find(e=>e.choices.some(c=>c.outcomes?.some(o=>o.type==='discover'&&o.landmark===id)));if(!event)return false;state.dungeon.inDungeon=true;state.dungeon.currentEventId=event.id;return resolveDungeonEvent(event.id,event.choices.find(c=>c.outcomes?.some(o=>o.type==='discover'&&o.landmark===id)).id).ok}
export function qaSetTemporaryEffect(name,value=1,encounters=2){if(value===0){delete state.player.temporaryEffects?.[name];persist();return true}addTemporaryEffect(name,value,encounters);return true}
export function qaResetEventState(){state.dungeon.currentEventId=null;state.dungeon.eventState={};state.dungeon.eventFlags={};state.dungeon.eventHistory=[];state.dungeon.eventedCells=[];state.dungeon.rooms={};state.dungeon.landmarks=[];persist()}
export function qaSetRoom(roomId){if(!roomTypes[roomId])return false;state.dungeon.inDungeon=true;state.dungeon.rooms[cellKey(state.dungeon.floor,state.dungeon.x,state.dungeon.y)]=roomId;persist();return true}
export function talkNpc(id){const npc=dungeonNpcs[id];return npc?.line||'The visitor gives an unhelpful nod.'}
export function storeStock(){return shopStock.map(id=>items[id])}
export function xpToNext(){return state.player.level*25-state.player.xp}

// Development-only actions are also kept out of the regular game action paths.
export function qaGiveItem(id,qty=1){return addItem(id,qty)}
export function qaGiveGold(amount){state.town.gold=Math.max(0,state.town.gold+amount);persist()}
export function qaSpawnMonster(id){const key=monsters[id]?id:Object.keys(monsters).find(monsterId=>monsters[monsterId].id===id);if(!key)return false;state.dungeon.inDungeon=true;state.combat=null;beginCombat(key,state.dungeon.x,state.dungeon.y);persist();return true}
export function qaSpawnNpc(id){if(!dungeonNpcs[id])return false;state.dungeon.inDungeon=true;state.dungeon.currentNpcId=id;let visitor=state.dungeon.npcs.find(n=>n.id===id&&n.floor===state.dungeon.floor);if(visitor){visitor.x=state.dungeon.x;visitor.y=state.dungeon.y;visitor.resolved=false}else state.dungeon.npcs.push({id,floor:state.dungeon.floor,x:state.dungeon.x,y:state.dungeon.y,resolved:false});persist();return true}
export function qaAdvanceFloor(){state.dungeon.floor=Math.min(3,state.dungeon.floor+1);state.dungeon.deepestFloor=Math.max(state.dungeon.deepestFloor||1,state.dungeon.floor);state.dungeon.map=createFloorMap();state.dungeon.inDungeon=true;state.dungeon.x=state.dungeon.map.upStairs[0];state.dungeon.y=state.dungeon.map.upStairs[1];ensureFloorNpcs(state.dungeon.floor);reveal();persist()}
export function qaSetStat(name,value){if(!['baseStr','baseAgi','baseMind','baseVit','baseMaxHp','baseMaxMp'].includes(name))return false;state.player[name]=Math.max(0,Math.min(99,Number(value)||0));recalculateStats();persist();return true}
export function qaClearInventory(){state.inventory=[];state.equipment={};recalculateStats();persist()}
