import {freshState,saveState,wallAt} from './state.js';
import {quests,items} from './data.js';
export let state= freshState();
export function setState(s){state=s}
export function persist(){saveState(state)}
export function startGame(name,cls){const s=freshState();const bases={Fighter:[4,2,1,4,24,4],Wizard:[1,2,4,2,17,12],Rogue:[2,4,2,2,19,6],Cleric:[2,1,3,4,22,9]};const [str,agi,mind,vit,hp,mp]=bases[cls]||bases.Fighter;s.player={name:name.trim()||'Delver',class:cls,level:1,xp:0,hp,maxHp:hp,mp,maxMp:mp,str,agi,mind,vit,attack:2+str,defense:Math.floor(vit/2),turns:0};s.inventory=[{id:'rusty-sword',quantity:1},{id:'patched-coat',quantity:1},{id:'healing-tonic',quantity:2}];state=s;persist()}
export function acceptQuest(id){if(state.quests.active.length>=5||!state.quests.available.includes(id))return false;state.quests.available=state.quests.available.filter(x=>x!==id);state.quests.active.push({id,progress:0});persist();return true}
export function addItem(id,n=1){let e=state.inventory.find(x=>x.id===id);if(e)e.quantity+=n;else state.inventory.push({id,quantity:n});persist()}
export function countItem(id){return state.inventory.find(x=>x.id===id)?.quantity||0}
export function completeQuest(q){if(state.quests.completed.includes(q.id))return;state.quests.active=state.quests.active.filter(x=>x.id!==q.id);state.quests.completed.push(q.id);state.town.gold+=q.reward.gold;state.player.xp+=q.reward.xp}
export function progress(type,target){for(const p of [...state.quests.active]){const q=quests[p.id];if(q.type===type&&q.target===target){p.progress++;if(p.progress>=q.count)completeQuest(q)}}persist()}
export function enterDungeon(){state.dungeon.inDungeon=true;state.dungeon.x=1;state.dungeon.y=5;state.dungeon.facing=0;reveal();persist()}
export function returnTown(){state.dungeon.inDungeon=false;state.combat=null;persist()}
export function reveal(){const k=`${state.dungeon.x},${state.dungeon.y}`;if(!state.dungeon.explored.includes(k))state.dungeon.explored.push(k);const floor=state.dungeon.floor;state.dungeon.visited[floor]=[...new Set([...(state.dungeon.visited[floor]||[]),k])];}
export function move(dir){const d=state.dungeon;let [dx,dy]=[[0,-1],[1,0],[0,1],[-1,0]][d.facing];if(dir==='back'){dx=-dx;dy=-dy}const nx=d.x+dx,ny=d.y+dy;if(wallAt(d,nx,ny))return 'The stone wall does not negotiate.';d.x=nx;d.y=ny;state.player.turns++;reveal();if(nx===d.map.stairs[0]&&ny===d.map.stairs[1])return 'A stair leads back to daylight.';if(d.rat.alive&&nx===d.rat.x&&ny===d.rat.y){state.combat={enemy:'Dungeon Rat',hp:d.rat.hp,maxHp:8};persist();return 'Something small and fast bares its teeth.'}if(!d.lootTaken&&nx===3&&ny===4)return 'You spot a blue lunchbox and a suspiciously useful salt deposit.';persist();return 'Your boots disturb the dust.'}
export function turn(n){state.dungeon.facing=(state.dungeon.facing+n+4)%4;persist()}
export function attack(){const c=state.combat;if(!c)return '';const dmg=Math.max(1,state.player.attack+1);c.hp-=dmg;let msg=`You hit the ${c.enemy} for ${dmg}.`;if(c.hp<=0){state.dungeon.rat.alive=false;state.dungeon.rat.hp=0;state.combat=null;state.player.xp+=4;state.town.gold+=3;addItem('cave-salt');progress('kill','rat');msg+=' The rat drops cave salt and three coins.'}else{const hit=Math.max(1,4-state.player.defense);state.player.hp=Math.max(0,state.player.hp-hit);msg+=` It bites for ${hit}.`;if(!state.player.hp){state.player.hp=1;returnTown();msg+=' You are escorted back to town with one HP.'}}persist();return msg}
export function defend(){const c=state.combat;if(!c)return '';const hit=Math.max(0,2-state.player.defense);state.player.hp=Math.max(1,state.player.hp-hit);persist();return `You brace. The rat scratches for ${hit}.`}
export function useTonic(){if(!countItem('healing-tonic'))return 'No tonic left.';const e=state.inventory.find(i=>i.id==='healing-tonic');e.quantity--;state.player.hp=Math.min(state.player.maxHp,state.player.hp+items['healing-tonic'].effect.amount);if(!e.quantity)state.inventory=state.inventory.filter(i=>i.id!==e.id);persist();return 'The tonic tastes mostly of herbs.'}
export function collectFind(){if(state.dungeon.lootTaken)return;state.dungeon.lootTaken=true;addItem('blue-lunchbox');addItem('stone-chip');progress('loot','lunchbox');progress('loot','stone');}
