import {freshState,saveState,wallAt,INVENTORY_CAPACITY,EQUIPMENT_SLOTS,createFloorMap,generateFloorMap} from './state.js?v=enemy-pools-20261003a';
import {quests,items,monsters,lootTables,floorEncounterTable,dungeonNpcs,npcEncounterIds,trades,shopStock,merchantProfiles,rarities,dungeonEvents,roomTypes,enemyVariants,monsterForId} from './data.js?v=enemy-pools-20261003a';
import {scaleEnemy,threatAssessment} from './enemy-scaling.js?v=enemy-depth-20261003a';
import {classAbilities,achievements} from './progression.js?v=major-systems-20261002i';
import {chooseEnemyAttack,chooseEncounterCategory,paceEncounterChance,recordEncounter,selectWithHistory} from './encounter-director.js?v=systems-20261003a';
import {applyStatus,statusModifier,tickStatuses} from './status-effects.js?v=systems-20261002a';
import {weightedChoice} from './random-utils.js?v=systems-20261002a';
export {threatAssessment};
export function currentThreatAssessment(){return state.combat&&state.player?threatAssessment(state.combat,{...state.player,fireResistance:equippedEffect('fireResistance'),temporaryDefense:temporaryEffect('defense'),specialAttack:state.combat.monsterId==='kung-fu-goose'?equippedEffect('vsGoose'):0}):null}
function applyPhysicalResistance(enemy,damage,magical=false){const resistance=enemy?.physicalResistanceReductionTurns>0?Math.max(0,(enemy?.physicalResistance||0)-.45):enemy?.physicalResistance||0;return Math.max(1,magical?Math.round(damage):Math.round(damage*(1-Math.max(0,Math.min(.9,resistance)))))}
function tickCombatEffects(){if(state.combat?.physicalResistanceReductionTurns>0)state.combat.physicalResistanceReductionTurns--}
function statusEffectLabel(id){return ({poison:'poisoned',weakened:'shaken',guarded:'guarded',blessed:'blessed',slowed:'slowed',confused:'confused'})[id]||id}

export let state=freshState();
const eventHooks=new Map();
export function onGameEvent(type,handler){if(typeof handler!=='function')return()=>{};const listeners=eventHooks.get(type)||new Set();listeners.add(handler);eventHooks.set(type,listeners);return()=>listeners.delete(handler)}
function emitGameEvent(type,payload){for(const handler of eventHooks.get(type)||[])try{handler(payload)}catch(error){console.warn(`Game event hook failed: ${type}`,error)}}
function townFlag(id,value=true){state.town.flags=state.town.flags||{};state.town.flags[id]=value}
export const STARTING_CLASSES={Fighter:{str:4,agi:2,mind:1,vit:4,hp:24,mp:4},Wizard:{str:1,agi:2,mind:4,vit:2,hp:17,mp:12},Rogue:{str:2,agi:4,mind:2,vit:3,hp:19,mp:6},Cleric:{str:3,agi:2,mind:4,vit:4,hp:22,mp:9}};
export const STARTING_STAT_RANGES={Fighter:{str:[3,5],agi:[1,3],mind:[1,2],vit:[3,5]},Wizard:{str:[1,2],agi:[1,3],mind:[3,5],vit:[1,3]},Rogue:{str:[1,3],agi:[3,5],mind:[1,3],vit:[2,4]},Cleric:{str:[2,4],agi:[1,3],mind:[3,5],vit:[3,5]}};
export function rollStartingStats(cls,randomFn=Math.random){const range=STARTING_STAT_RANGES[cls]||STARTING_STAT_RANGES.Fighter;return Object.fromEntries(Object.entries(range).map(([stat,[min,max]])=>[stat,min+Math.floor(Math.max(0,Math.min(.999999999,Number(randomFn())||0))*(max-min+1))]))}
export function deriveStartingResources(cls,stats){const baseline=STARTING_CLASSES[cls]||STARTING_CLASSES.Fighter;return {hp:Math.max(12,baseline.hp+(stats.vit-baseline.vit)*2),mp:Math.max(2,baseline.mp+(stats.mind-baseline.mind)*2)}}
export function setState(next){state=next;if(state?.player)recalculateStats()}
export function persist(){if(state?.meta)saveState(state)}
export function unlockAchievement(id){const def=achievements.find(a=>a.id===id);if(!def||state.achievements?.unlocked?.[id])return false;state.achievements=state.achievements||{unlocked:{}};state.achievements.unlocked=state.achievements.unlocked||{};state.achievements.unlocked[id]=Date.now();state.dungeon.achievementNotices=state.dungeon.achievementNotices||[];state.dungeon.achievementNotices.push(def.name);persist();return true}
export function bumpCareer(key,amount=1){state.career=state.career||{};state.career[key]=(state.career[key]||0)+amount;if(key==='questsCompleted'&&state.career.questsCompleted>=5)unlockAchievement('paper-trail');if(key==='ducksEncountered'&&state.career.ducksEncountered)unlockAchievement('duck-report');if(key==='spoonsCollected'&&state.career.spoonsCollected>=5)unlockAchievement('spoon-collection');if(key==='mushroomsCollected'&&state.career.mushroomsCollected>=5)unlockAchievement('mushroom-collection');if((key==='goldEarned'||key==='goldSpent')&&state.town.gold>=100)unlockAchievement('wealthy-on-paper');persist()}
function random(){const d=state.dungeon;d.seed=(d.seed*48271)%2147483647;return d.seed/2147483647}
function owned(id){return state.inventory.filter(entry=>entry.id===id).reduce((n,entry)=>n+entry.quantity,0)}
export function countItem(id){return owned(id)}
export function inventoryUsed(){let total=0;for(const id of new Set(state.inventory.filter(x=>x.quantity>0).map(x=>x.id))){const def=items[id];total+=def?.stackable?Math.ceil(owned(id)/10):owned(id)}return total}
export function inventoryCapacity(){return state.settings?.inventoryCapacity||INVENTORY_CAPACITY}
export function canAddItem(id,quantity=1){if(!items[id])return false;const def=items[id],before=def.stackable?Math.ceil(owned(id)/10):owned(id),after=def.stackable?Math.ceil((owned(id)+quantity)/10):owned(id)+quantity;return inventoryUsed()+after-before<=inventoryCapacity()}
export function addItem(id,quantity=1,provenance=null){if(!canAddItem(id,quantity))return false;const def=items[id];if(def.stackable){let left=quantity;for(const entry of state.inventory.filter(x=>x.id===id)){const n=Math.min(10-entry.quantity,left);entry.quantity+=n;left-=n;if(!left)break}while(left>0){const n=Math.min(10,left);state.inventory.push({id,quantity:n});left-=n}}else for(let n=0;n<quantity;n++)state.inventory.push({id,quantity:1,...(provenance&& (def.slot||['rare','strange'].includes(def.rarity))?{provenance:{...provenance}}:{})});if(state.player){bumpCareer('itemsFound',quantity);if(def.rarity==='strange'){bumpCareer('strangeItemsFound',quantity);unlockAchievement('strange-find')}if(id==='bent-spoon'||id==='heavy-spoon')bumpCareer('spoonsCollected',quantity);if(id==='suspicious-mushroom')bumpCareer('mushroomsCollected',quantity)}emitGameEvent('itemAcquired',{id,quantity,provenance});persist();return true}
export function removeItem(id,quantity=1){if(owned(id)<quantity)return false;let left=quantity;for(const entry of [...state.inventory].filter(x=>x.id===id)){const take=Math.min(entry.quantity,left);entry.quantity-=take;left-=take;if(entry.quantity<=0)state.inventory=state.inventory.filter(x=>x!==entry);if(!left)break}persist();return true}
function equippedIds(){return Object.values(state.equipment||{}).filter(Boolean)}
function equipmentEffects(){const sum={};for(const id of equippedIds()){const def=items[id];if(!def)continue;for(const [key,value] of Object.entries(def.modifiers||{}))sum[key]=(sum[key]||0)+value}return sum}
export function temporaryEffect(name){return state.player?.temporaryEffects?.[name]?.value||0}
export function equippedEffect(name){return equippedIds().reduce((sum,id)=>sum+(items[id]?.effects?.[name]||0),0)+temporaryEffect(name)}
export function addTemporaryEffect(name,value,encounters=1){if(!state.player.temporaryEffects)state.player.temporaryEffects={};state.player.temporaryEffects[name]={value,remaining:Math.max(1,encounters)};persist()}
function tickTemporaryEffects(){for(const [name,effect] of Object.entries(state.player.temporaryEffects||{})){effect.remaining--;if(effect.remaining<=0)delete state.player.temporaryEffects[name]}}
export function recalculateStats(){const p=state.player;if(!p)return;const mod=equipmentEffects();p.str=(p.baseStr??p.str??1)+(mod.str||0);p.agi=(p.baseAgi??p.agi??1)+(mod.agility||0);p.mind=(p.baseMind??p.mind??1)+(mod.mind||0);p.vit=(p.baseVit??p.vit??1)+(mod.vitality||0);p.maxHp=Math.max(1,(p.baseMaxHp??p.maxHp??20)+(mod.hp||0));p.maxMp=Math.max(0,(p.baseMaxMp??p.maxMp??0)+(mod.mp||0));p.attack=Math.max(1,2+p.str+(mod.attack||0));const armorSlots=['head','body','offHand'].filter(slot=>state.equipment[slot]&&items[state.equipment[slot]]?.slot);p.defense=Math.max(0,Math.floor(p.vit/2)+(mod.defense||0)+(p.class==='Fighter'&&armorSlots.length?1:0));p.hp=Math.min(p.hp??p.maxHp,p.maxHp);p.mp=Math.min(p.mp??p.maxMp,p.maxMp)}
export function compareEquipment(id){const item=items[id];if(!item?.slot)return null;const currentId=state.equipment[item.slot],current=items[currentId];const keys=['attack','defense','hp','mp','str','agility','mind','vitality'];return {slot:item.slot,currentId,current,deltas:Object.fromEntries(keys.map(k=>[k,(item.modifiers?.[k]||0)-(current?.modifiers?.[k]||0)]).filter(([,v])=>v!==0))}}
export function startGame(name,cls,rolledStats=null){const settings={...(state.settings||{})},s=freshState(),className=STARTING_CLASSES[cls]?cls:'Fighter',base=STARTING_CLASSES[className],stats=rolledStats&&Object.keys(STARTING_STAT_RANGES[className]).every(k=>Number.isInteger(rolledStats[k])&&rolledStats[k]>=STARTING_STAT_RANGES[className][k][0]&&rolledStats[k]<=STARTING_STAT_RANGES[className][k][1])?rolledStats:rollStartingStats(className),resources=deriveStartingResources(className,stats);s.settings={...s.settings,...settings};s.player={name:name.trim()||'Delver',class:className,level:1,xp:0,hp:resources.hp,mp:resources.mp,baseMaxHp:resources.hp,baseMaxMp:resources.mp,baseStr:stats.str,baseAgi:stats.agi,baseMind:stats.mind,baseVit:stats.vit,effects:{},temporaryEffects:{},statusEffects:{},turns:0};s.inventory=[{id:'rusty-sword',quantity:1},{id:'patched-coat',quantity:1},{id:'healing-tonic',quantity:2}];s.equipment={mainHand:'rusty-sword',body:'patched-coat'};state=s;recalculateStats();state.player.hp=state.player.maxHp;state.player.mp=state.player.maxMp;ensureFloorNpcs(1);persist()}
function questObjectiveProgress(q,active){
  if(q.type==='loot'&&q.turnInItems?.length)return Math.min(q.count,...q.turnInItems.map(item=>Math.floor(owned(item.id)/item.quantity)));
  if(q.type==='discover'&&state.dungeon.landmarks.some(landmark=>landmark.id===q.target))return q.count;
  if(q.type==='return'&&q.target==='3'&&state.dungeon.deepestFloor>=3&&!state.dungeon.inDungeon)return q.count;
  if(q.type==='return'&&q.target==='any'&&(active.progress>=q.count||state.dungeon.eventFlags['crew-report-return']))return q.count;
  if(q.type==='flag'&&state.dungeon.eventFlags[q.target])return q.count;
  return Math.min(q.count,Math.max(0,active.progress||0));
}
export function questStatus(id){
  if(state.quests.completed.includes(id))return {status:'completed',progress:quests[id]?.count||0,count:quests[id]?.count||1};
  if(state.quests.available.includes(id))return {status:'available',progress:0,count:quests[id]?.count||1};
  const active=state.quests.active.find(entry=>entry.id===id),q=quests[id];
  if(!active||!q)return {status:'unavailable',progress:0,count:q?.count||1};
  const progress=questObjectiveProgress(q,active);
  return {status:progress>=q.count?'ready':'active',progress,count:q.count};
}
export function questReservedQuantity(itemId){return state.quests.active.reduce((total,active)=>total+(quests[active.id]?.turnInItems||[]).filter(item=>item.id===itemId&&item.consume!==false).reduce((sum,item)=>sum+item.quantity,0),0)}
export function canRemoveItem(itemId,quantity=1){return owned(itemId)>=quantity&&owned(itemId)-quantity>=questReservedQuantity(itemId)}
export function acceptQuest(id){if(state.quests.active.length>=5||!state.quests.available.includes(id))return false;state.quests.available=state.quests.available.filter(x=>x!==id);state.quests.active.push({id,progress:0});persist();return true}
export function turnInQuest(id){
  const quest=quests[id],active=state.quests.active.find(entry=>entry.id===id);
  if(!quest||!active)return {ok:false,message:'That quest is not active.'};
  if(questStatus(id).status!=='ready')return {ok:false,message:'The objective is not ready to turn in.'};
  const missing=(quest.turnInItems||[]).find(item=>item.consume!==false&&owned(item.id)<item.quantity);
  if(missing)return {ok:false,message:`You need ${missing.quantity} ${items[missing.id]?.name||'required item'} to turn this in.`};
  const consumed=[];
  for(const item of quest.turnInItems||[]){
    if(item.consume!==false){if(!removeItem(item.id,item.quantity))return {ok:false,message:`You need ${item.quantity} ${items[item.id]?.name||'required item'} to turn this in.`};consumed.push(items[item.id].name)}
  }
  if(id==='rat-problem')state.dungeon.eventFlags['rat-marker-report']=true;
  state.quests.active=state.quests.active.filter(entry=>entry.id!==id);
  state.quests.completed.push(id);bumpCareer('questsCompleted');emitGameEvent('questCompleted',{id,quest});townFlag('unusualArtifactDelivered',!!quest.turnInItems?.length);
  if(quest.next){const known=[...state.quests.available,...state.quests.completed,...state.quests.active.map(x=>x.id)];if(!known.includes(quest.next))state.quests.available.push(quest.next)}
  state.town.gold+=quest.reward.gold;
  bumpCareer('goldEarned',quest.reward.gold);const levelMessage=grantXp(quest.reward.xp);
  persist();
  const returned=consumed.length?`Returned ${consumed.join(', ')}. `:'';
  return {ok:true,message:`${returned}Received ${quest.reward.gold} gold and ${quest.reward.xp} XP.${levelMessage?` ${levelMessage}`:''}`};
}
export function progress(type,target){for(const active of state.quests.active){const quest=quests[active.id];if(quest?.type===type&&(quest.target===target||quest.target==='any'))active.progress=Math.min(quest.count,(active.progress||0)+1)}emitGameEvent('questProgress',{type,target});persist()}
function floorMap(floor=state.dungeon.floor){const d=state.dungeon,key=String(floor);if(!d.maps)d.maps={};if(!d.maps[key])d.maps[key]=d.legacyMaps?createFloorMap():generateFloorMap(d.seed,floor);d.map=d.maps[key];return d.map}
function openCells(map){const cells=[];for(let y=1;y<map.height-1;y++)for(let x=1;x<map.width-1;x++)if(!map.walls.some(([wx,wy])=>wx===x&&wy===y))cells.push([x,y]);return cells}
function placeNewFloorMarkers(floor){const d=state.dungeon,map=d.map,open=openCells(map).filter(([x,y])=>!(x===map.upStairs[0]&&y===map.upStairs[1])&&!(x===map.downStairs[0]&&y===map.downStairs[1]));if(d.legacyMaps){if(floor===1)d.lunchboxCell=d.lunchboxCell||[3,4];if(floor===1&&d.rat)d.rat.position=true;return}if(floor===1&&!d.lunchboxCell){const p=open.find(([x,y])=>x>map.width/2&&y>map.height/2)||open[0];d.lunchboxCell=p}if(floor===1&&d.rat&&!d.rat.position){const p=open.find(([x,y])=>x>map.width/2&&y<map.height/2)||open.at(-1);d.rat.x=p[0];d.rat.y=p[1];d.rat.position=true}}
function ensureFloorNpcs(floor){const d=state.dungeon,map=floorMap(floor);placeNewFloorMarkers(floor);if(d.npcs.some(n=>n.floor===floor))return;const blocked=new Set([map.upStairs,map.downStairs,d.lunchboxCell,[d.rat?.x,d.rat?.y]].filter(Boolean).map(([x,y])=>`${x},${y}`));const spots=openCells(map).filter(([x,y])=>!blocked.has(`${x},${y}`)&&!d.npcs.some(n=>n.floor===floor&&n.x===x&&n.y===y));for(let i=spots.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[spots[i],spots[j]]=[spots[j],spots[i]]}npcEncounterIds.forEach((id,i)=>{if(spots[i]){const [x,y]=spots[i];d.npcs.push({id,floor,x,y,resolved:false})}})}
function floorKey(floor=state.dungeon.floor){return String(floor)}
function cellKey(floor,x,y){return `${floor}:${x},${y}`}
function assignRoom(floor,x,y){const eligible=Object.values(roomTypes).filter(r=>(r.minDepth||1)<=floor),room=weightedChoice(eligible,random);if(!room)return null;state.dungeon.rooms[cellKey(floor,x,y)]=room.id;return room}
function selectEvent(floor,x,y){const d=state.dungeon,room=roomTypes[d.rooms[cellKey(floor,x,y)]],eligible=Object.values(dungeonEvents).filter(e=>floor>=(e.minDepth||1)&&floor<=(e.maxDepth||99)).filter(e=>{const previous=d.eventState[e.id];return !previous?.resolved&&(e.repeatable||!previous?.count)&&(!e.cooldown||!previous||d.encounterStep-previous.lastStep>=e.cooldown)});if(!eligible.length)return null;const history=(d.encounterHistory||[]).filter(e=>e.type==='event');const rows=eligible.map(e=>({...e,weight:e.weight*((e.rooms||[]).includes(room?.id)?2.5:1)*(1+(floor-1)*(e.weirdness??.1))}));return selectWithHistory(rows,history,e=>e.id,random,.62)}
function openRandomEvent(floor,x,y){const event=selectEvent(floor,x,y);if(!event)return null;const d=state.dungeon;d.currentEventId=event.id;d.eventedCells.push(cellKey(floor,x,y));d.eventState[event.id]=d.eventState[event.id]||{count:0,lastStep:0,resolved:false};d.eventState[event.id].lastStep=d.encounterStep;d.encounterHistory=recordEncounter(d.encounterHistory,'event',event.id);d.encounterStreak=(d.encounterStreak||0)+1;d.emptySteps=0;persist();return event}
export function reveal(){const d=state.dungeon,k=`${d.x},${d.y}`,floor=floorKey();if(!d.explored.includes(`${floor}:${k}`))d.explored.push(`${floor}:${k}`);if(!d.visited[floor])d.visited[floor]=[];if(!d.visited[floor].includes(k))d.visited[floor].push(k);if(d.x===d.map.upStairs[0]&&d.y===d.map.upStairs[1])d.discoveredStairs=[...new Set([...(d.discoveredStairs||[]),`${floor}:up`])];if(d.x===d.map.downStairs[0]&&d.y===d.map.downStairs[1])d.discoveredStairs=[...new Set([...(d.discoveredStairs||[]),`${floor}:down`])]}
export function enterDungeon(){const d=state.dungeon;d.inDungeon=true;if(d.floor<1)d.floor=1;d.floor=1;const map=floorMap(1);ensureFloorNpcs(1);d.x=map.upStairs[0];d.y=map.upStairs[1];d.facing=0;reveal();unlockAchievement('first-descent');persist()}
export function returnTown(count=true){const d=state.dungeon,deepest=d.deepestFloor||d.floor;d.inDungeon=false;d.currentNpcId=null;d.currentEventId=null;state.combat=null;d.floor=1;const map=floorMap(1);d.x=map.upStairs[0];d.y=map.upStairs[1];if(count){state.town.deepestReportedFloor=Math.max(state.town.deepestReportedFloor||1,deepest);townFlag(`reachedFloor${deepest}`);emitGameEvent('townReturned',{floor:deepest});restockShop();if(d.eventFlags['met-nell-deeper'])d.eventFlags['crew-report-return']=true;bumpCareer('successfulReturns');unlockAchievement('made-it-back');if(d.eventFlags['duck-greeted']){d.eventFlags['duck-returned']=true;if(d.eventFlags['duck-receipt'])d.eventFlags['duck-receipt-returned']=true}if(deepest>=3)progress('return','3');progress('return','any');if(d.eventFlags['warm-wall-seen']&&deepest>=3)d.eventFlags['deep-warm-wall-return']=true}persist()}
function resolveDefeat(){const p=state.player,d=state.dungeon,lost=Math.min(state.town.gold,Math.ceil(state.town.gold*.1));state.town.gold-=lost;p.hp=1;p.mp=0;delete p.effects?.burn;if(p.statusEffects)for(const [id,effect] of Object.entries(p.statusEffects))if(['burn','poison'].includes(id))delete p.statusEffects[id];state.combat=null;d.currentNpcId=null;d.currentEventId=null;d.inDungeon=false;d.floor=1;const map=floorMap(1);d.map=map;d.x=map.upStairs[0];d.y=map.upStairs[1];d.lastDefeat={pending:true,lostGold:lost,retainedGear:Object.values(state.equipment).filter(Boolean).map(id=>items[id]?.name).filter(Boolean),floor:d.deepestFloor||1};bumpCareer('deaths');bumpCareer('rescues');unlockAchievement('rescued');returnTown(false);return ` Defeated. The Delvers’ Office recovered you near the stairs; you lost ${lost} gold, kept your gear and discoveries, and returned with 1 HP.`}
const knownCell=(floor,x,y)=>{const d=state.dungeon;return (floor===d.floor&&x===d.x&&y===d.y)||d.explored.includes(`${floor}:${x},${y}`)||(floor===d.floor&&d.explored.includes(`${x},${y}`))};
export function returnPlan(){const d=state.dungeon,currentMap=d.map,start={floor:d.floor,x:d.x,y:d.y},first=floorMap(1),target={floor:1,x:first.upStairs[0],y:first.upStairs[1]},key=n=>`${n.floor}:${n.x},${n.y}`,queue=[start],prev=new Map([[key(start),null]]);while(queue.length){const n=queue.shift();if(key(n)===key(target))break;const map=floorMap(n.floor),candidates=[];for(const [dx,dy] of [[0,-1],[1,0],[0,1],[-1,0]]){const x=n.x+dx,y=n.y+dy;if(!wallAt({...d,map},x,y)&&knownCell(n.floor,x,y))candidates.push({floor:n.floor,x,y})}if(n.x===map.downStairs[0]&&n.y===map.downStairs[1]&&n.floor<Math.min(3,d.deepestFloor||d.floor)){const next=floorMap(n.floor+1);candidates.push({floor:n.floor+1,x:next.upStairs[0],y:next.upStairs[1]})}if(n.x===map.upStairs[0]&&n.y===map.upStairs[1]&&n.floor>1){const previous=floorMap(n.floor-1);candidates.push({floor:n.floor-1,x:previous.downStairs[0],y:previous.downStairs[1]})}for(const v of candidates){if(v.floor!==n.floor&&!knownCell(v.floor,v.x,v.y))continue;const k=key(v);if(!prev.has(k)){prev.set(k,key(n));queue.push(v)}}}if(!prev.has(key(target))){d.map=currentMap;return {ok:false,route:[],steps:0,chancePercent:0}}const route=[];let at=key(target);while(at){const [floor,coordinates]=at.split(':'),[x,y]=coordinates.split(',').map(Number);route.unshift({floor:Number(floor),x,y});at=prev.get(at)}d.map=currentMap;const steps=Math.max(0,route.length-1),hazard=d.rooms[`${d.floor}:${d.x},${d.y}`]==='flooded-chamber'?.08:0;/* Known-route return chance: 96% base, minus 12 points per extra floor and 2.5 per route step, plus 1 per AGI above 5 and equipped retreat bonus; current flooded room costs 8 points. Clamp to 20–95%. */const chance=Math.max(.2,Math.min(.95,.96-Math.max(0,d.floor-1)*.12-steps*.025+((state.player.agi||5)-5)*.01+equippedEffect('retreatBonus')/100-hazard));return {ok:true,route,steps,chancePercent:Math.round(chance*100)}}
export function attemptReturn(force=''){const plan=returnPlan();if(!plan.ok)return {ok:false,message:'No known safe route to the town stairs. Find your way back manually.'};const d=state.dungeon,success=force==='safe'||(force!=='interrupt'&&random()<plan.chancePercent/100);if(success){d.eventFlags['crew-report-return']=true;returnTown();return {ok:true,message:`You retrace ${plan.steps} known steps and reach town safely.`}}bumpCareer('interruptedReturns');unlockAchievement('not-a-shortcut');const max=plan.route.length-1,index=max>1?1+Math.floor(random()*(max-1)):max,spot=plan.route[index]||plan.route[0];d.floor=spot.floor;d.map=floorMap(spot.floor);d.x=spot.x;d.y=spot.y;const previous=plan.route[Math.max(0,index-1)];if(previous.floor===spot.floor){const dx=spot.x-previous.x,dy=spot.y-previous.y;d.facing=dx===1?1:dx===-1?3:dy===1?2:0}const id=selectMonster();beginCombat(id,d.x,d.y);persist();return {ok:false,interrupted:true,message:`The return is interrupted near ${d.x}, ${d.y}. ${monsters[id].name} blocks the route.`}}
export function move(direction){const d=state.dungeon;if(state.combat)return 'Choose an action before moving.';if(d.currentNpcId||d.currentEventId)return 'Finish the encounter first.';const vectors={up:[0,-1,0],right:[1,0,1],down:[0,1,2],left:[-1,0,3]},vector=vectors[direction];if(!vector)return 'Choose a direction.';const [dx,dy,targetFacing]=vector,nx=d.x+dx,ny=d.y+dy,origin={x:d.x,y:d.y};if(wallAt(d,nx,ny)){d.lastMovement={direction,result:'blocked',from:origin,to:{x:nx,y:ny},facing:d.facing};persist();return "There's a wall there."}d.x=nx;d.y=ny;d.facing=targetFacing;d.lastMovement={direction,result:'moved',from:origin,to:{x:nx,y:ny},facing:d.facing};state.player.turns++;d.encounterStep=(d.encounterStep||0)+1;const floor=d.floor,key=cellKey(floor,nx,ny),newCell=!d.explored.includes(`${floor}:${nx},${ny}`)&&!d.explored.includes(`${nx},${ny}`);reveal();if(newCell&&!d.rooms[key])assignRoom(floor,nx,ny);const cache=d.lunchboxCell||[3,4],cacheId=`cache-${d.floor}-first`;if(floor===1&&nx===cache[0]&&ny===cache[1]&&!d.finds.includes(cacheId)){persist();return 'You spot a blue lunchbox and a suspiciously useful salt deposit.'}const visitor=d.npcs.find(n=>n.floor===floor&&!n.resolved&&n.x===nx&&n.y===ny);if(visitor){d.currentNpcId=visitor.id;d.encounterHistory=recordEncounter(d.encounterHistory,'npc',visitor.id);persist();return `${dungeonNpcs[visitor.id].name} is waiting beside the wall.`}if(floor===1&&d.rat?.alive&&nx===d.rat.x&&ny===d.rat.y){beginCombat('rat',nx,ny);persist();return monsters.rat.encounterText}if(newCell&&!d.eventedCells.includes(key)){d.emptySteps=(d.emptySteps||0)+1;const chances=paceEncounterChance({event:({1:.09,2:.13,3:.18})[floor]||.2,combat:({1:.13,2:.19,3:.25})[floor]||.27,emptySteps:d.emptySteps,encounterStreak:d.encounterStreak||0}),category=chooseEncounterCategory(chances,random);if(category==='event'){const event=openRandomEvent(floor,nx,ny);if(event){persist();return event.description}}else if(category==='combat'){const monsterId=selectMonster();beginCombat(monsterId,nx,ny);persist();return monsterForId(monsterId).encounterText}else d.encounterStreak=0}persist();const room=roomTypes[d.rooms[key]];return room&&room.id!=='ordinary'?room.description:(floor>=2?'The stone groans somewhere below.':'Your boots disturb the dust.')}
function selectMonster(){const d=state.dungeon,rows=(floorEncounterTable[d.floor]||floorEncounterTable[3]).filter(row=>monsters[row.id]?.minDepth<=d.floor),history=(d.encounterHistory||[]).filter(e=>e.type==='monster');return selectWithHistory(rows,history,row=>monsters[row.id]?.id||row.id,random,.55)?.id||rows[0]?.id||'rat'}
function beginCombat(monsterId,x,y,options={}){const m=monsters[monsterId]||monsterForId(monsterId),floor=Math.max(1,Math.floor(options.floor??state.dungeon.floor));if(!m)return;let variant=null;if(options.variantId!==undefined)variant=enemyVariants.find(v=>v.id===options.variantId)||null;else variant=weightedChoice(enemyVariants.map(candidate=>({...candidate,weight:candidate.spawnChance})),random)||null;state.combat={...scaleEnemy(m,floor,variant,options.encounterLevel),x,y,guard:false,burnTurns:0,aiState:{turns:0}};const d=state.dungeon;d.encounters.push({id:`${d.floor}:${x},${y}:${d.encounterStep}`,monsterId:m.id,encounterLevel:state.combat.encounterLevel,variantId:state.combat.variantId,cleared:false});d.encounterHistory=recordEncounter(d.encounterHistory,'monster',m.id);if(m.id==='kung-fu-goose')townFlag('firstGooseConfirmed');emitGameEvent('monsterEncountered',{id:m.id,floor,variantId:state.combat.variantId});d.encounterStreak=(d.encounterStreak||0)+1;d.emptySteps=0}
function grantXp(amount){const p=state.player,lines=[];p.xp+=amount;while(p.xp>=p.level*25){p.xp-=p.level*25;p.level++;p.baseMaxHp+=2;p.baseMaxMp+=1;p.baseVit+=1;p.hp+=2;p.mp+=1;recalculateStats();const gained=classAbilities[p.class]?.find(a=>a.level===p.level);lines.push(`Level ${p.level}! +2 max HP, +1 max MP, +1 Vitality.${gained?` Unlocked ${gained.name}.`:''}`)}recalculateStats();return lines.join(' ')}
export function availableAbilities(){return (classAbilities[state.player?.class]||[]).filter(a=>a.level<=state.player.level)}
export function useAbility(id){const c=state.combat,p=state.player,ability=availableAbilities().find(a=>a.id===id);if(!c||!ability)return {ok:false,message:'That ability is not available.'};if(p.mp<ability.cost)return {ok:false,message:`${ability.name} needs ${ability.cost} MP.`};p.mp-=ability.cost;let text='';if(ability.kind==='brace'){c.guard=true;c.guardBonus=3;text=`You brace with ${ability.name}.`}
  else if(ability.kind==='ward'||ability.kind==='blessing'){c.wardHits=2;c.wardAmount=2;if(ability.kind==='blessing')c.blockNextBurn=true;text=ability.kind==='blessing'?'Blessing protects against the next two hits and one burn.':`${ability.name} is ready for the next two hits.`}
  else if(ability.kind==='heal'){const amount=Math.max(3,Math.round(p.maxHp*ability.scale));const restored=Math.min(amount,p.maxHp-p.hp);p.hp+=restored;text=`${ability.name} restores ${restored} HP.`}
  else if(ability.kind==='slip'){const chance=Math.min(.95,retreatChance(c.speed)+.18);if(random()<chance){state.combat=null;tickTemporaryEffects();persist();bumpCareer('combatRetreats');return {ok:true,message:`You slip away from ${c.displayName||monsterForId(c.monsterId).name}.`}}text=`Slip Away fails (${Math.round(chance*100)}%).`}
  else {const magical=['magic','fire','holy'].includes(ability.kind),base=magical?p.mind:Math.max(1,p.attack-statusModifier(p,'weakened')),scale=ability.scale||1,extra=ability.kind==='cheap'&&c.hp<=c.maxHp*.5?1:0,fire=ability.kind==='fire'?(c.fireResistance||0):0,raw=Math.max(1,Math.round(base*scale)+extra-fire-(c.defense||0)),damage=applyPhysicalResistance(c,raw,magical);c.hp-=damage;bumpCareer('damageDealt',damage);text=`${ability.name} hits for ${damage}.${c.physicalResistance&&!magical?' The blow passes through most of the cloud.':''}`;if(ability.kind==='quick'&&random()<.25){const bonusRaw=Math.max(1,Math.round(base*.6)),bonus=applyPhysicalResistance(c,bonusRaw,magical);c.hp-=bonus;bumpCareer('damageDealt',bonus);text+=` Critical follow-up for ${bonus}.`}if(c.hp<=0){const defeated={...c};state.combat=null;const encounter=state.dungeon.encounters.at(-1);if(encounter)encounter.cleared=true;if(c.monsterId==='rat')unlockAchievement('rat-problem');text+=` ${c.displayName||monsterForId(c.monsterId).name} is defeated.`+lootReward(monsterForId(c.monsterId),defeated);tickTemporaryEffects();persist();return {ok:true,message:text}}}
  text+=enemyTurn()+tickBurn();tickCombatEffects();persist();return {ok:true,message:text}}
function rollLoot(monster,instance=state.combat){const table=lootTables[monster.lootTable]||[];if(!table.length)return 'It leaves nothing worth carrying.';const rarityMult=1+equippedEffect('lootBonus')+(state.player.class==='Rogue'?.05:0)+(instance?.lootMultiplier||Math.min(2,1+((instance?.floor??state.dungeon.floor)-1)*.06))-1;const rows=table.map(e=>{const rarity=items[e.item]?.rarity||'common',rarityFactor=(rarities[rarity]?.weight||62)/62;return {...e,weight:e.weight*rarityFactor*(rarity==='rare'||rarity==='strange'?rarityMult:1)}}),chosen=weightedChoice(rows,random);if(!chosen)return 'It leaves nothing worth carrying.';const qty=chosen.min||1;if(!addItem(chosen.item,qty,{sourceType:'monster',sourceName:instance?.displayName||monster.name,acquiredFloor:instance?.floor||state.dungeon.floor})){state.dungeon.groundLoot.push({floor:state.dungeon.floor,x:state.dungeon.x,y:state.dungeon.y,item:chosen.item,quantity:qty});return ` Your pack is full; ${items[chosen.item].name} stays on the floor.`}progress('loot',chosen.item);const item=items[chosen.item];return item.slot?` Found: ${item.name}. ${item.rarity} · ${item.slot}. Open Inventory / Gear to equip it.`:` Loot: ${item.name}.`}
function enemyTurn(){const c=state.combat;if(!c)return '';const m=monsterForId(c.monsterId),name=c.displayName||m.name,behavior=c.behavior||m.behavior,attacks=c.attacks?.length?c.attacks:[{id:'attack',name:'Attack',minDamage:c.attack,maxDamage:c.attack,accuracy:1,weight:1}];let attack=chooseEnemyAttack(c.aiProfile||m.aiProfile,attacks,state.player,random)||attacks[0];c.aiState=c.aiState||{turns:0};c.aiState.turns++;if(c.forcedAttackId){attack=attacks.find(a=>a.id===c.forcedAttackId)||attack;c.forcedAttackId=null}const strikes=Math.max(1,Math.min(3,Math.floor(attack.multiStrike||1)));let roll=0,hitCount=0;for(let i=0;i<strikes;i++)if(random()<(attack.accuracy??.95)){roll+=Math.floor(random()*(attack.maxDamage-attack.minDamage+1))+attack.minDamage;hitCount++}const hit=hitCount>0,critical=hit&&(random()<(attack.criticalChance||behavior?.criticalChance||0));if(critical)roll=Math.ceil(roll*1.5);const ward=c.wardHits>0?c.wardAmount||0:0,damage=hit?Math.max(1,roll-state.player.defense-temporaryEffect('defense')-statusModifier(state.player,'guarded')-statusModifier(state.player,'blessed')-(c.guard?c.guardBonus||2:0)-ward):0;if(c.wardHits>0)c.wardHits--;c.lastAttack={id:attack.id,name:attack.name,roll,damage,hit,hitCount,critical,minDamage:attack.minDamage*strikes,maxDamage:attack.maxDamage*strikes};c.guard=false;c.guardBonus=0;state.player.hp=Math.max(0,state.player.hp-damage);if(damage)bumpCareer('damageTaken',damage);if(c.monsterId==='kung-fu-goose')bumpCareer('gooseAttacks');let text=hit?` ${attack.flavor||`${name} uses ${attack.name}.`} ${damage} damage${critical?' (critical)':''}.`:` ${name} misses with ${attack.name}.`;if(attack.effect&&hit&&random()<(attack.effectChance??(attack.effect==='burn'?behavior?.burnChance:.25)??.25)){if(attack.effect==='burn'&&c.blockNextBurn){c.blockNextBurn=false;text+=' Your blessing turns aside the flame.'}else{const turns=Math.max(0,(attack.effectTurns||behavior?.burnTurns||2)-(attack.effect==='burn'?equippedEffect('fireResistance')+(state.player.class==='Cleric'?1:0):0));if(turns){applyStatus(state.player,attack.effect,turns,attack.effectMagnitude??(attack.effect==='burn'?2:1),name);text+=` You are ${attack.effect==='burn'?'singed':statusEffectLabel(attack.effect)}.`}}}if(state.player.hp<=0){text+=resolveDefeat()}return text}
function lootReward(monster,instance){emitGameEvent('monsterDefeated',{id:monster.id,floor:instance?.floor||state.dungeon.floor,variantId:instance?.variantId||null});const gold=Math.floor((monster.gold[0]+random()*(monster.gold[1]-monster.gold[0]+1))*(instance?.rewardMultipliers?.gold||1));state.town.gold+=gold;bumpCareer('goldEarned',gold);bumpCareer('enemiesDefeated');if(monster.id==='kung-fu-goose')unlockAchievement('goose-problem');if(monster.id==='pocket-slime')unlockAchievement('pocket-inspector');if(monster.id==='fire-worm')unlockAchievement('earthworm-proof');const levelMessage=grantXp(instance?.xp??monster.xp);progress('kill',monster.id);progress('kill','any');if(monster.id==='rat'&&state.dungeon.eventFlags['rat-marker-report'])state.dungeon.eventFlags['rat-marker-report']=true;const drop=rollLoot(monster,instance);for(const id of equippedIds())if(items[id]?.effects?.postCombatHeal&&random()<items[id].effects.postCombatHeal)state.player.hp=Math.min(state.player.maxHp,state.player.hp+1);return ` ${gold} gold.${drop}${levelMessage?` ${levelMessage}`:''}`}
export function attack(){const c=state.combat;if(!c)return '';const m=monsterForId(c.monsterId),name=c.displayName||m.name;let message='';if(c.behavior?.evadeChance&&random()<c.behavior.evadeChance)message=`${name} evades.`;else{const vsGoose=c.monsterId==='kung-fu-goose'?equippedEffect('vsGoose'):0,raw=Math.max(1,state.player.attack+temporaryEffect('attack')-statusModifier(state.player,'weakened')+vsGoose-c.defense),damage=applyPhysicalResistance(c,raw);c.hp-=damage;bumpCareer('damageDealt',damage);message=`${c.physicalResistance?'The blade passes through most of the cloud. ':''}You hit the ${name} for ${damage}.`;if(c.hp<=0){const defeated={...c};state.combat=null;const encounter=state.dungeon.encounters.at(-1);if(encounter)encounter.cleared=true;if(m.id==='rat')unlockAchievement('rat-problem');message+=` ${name} is defeated.`+lootReward(m,defeated);tickTemporaryEffects();persist();return message}}message+=enemyTurn()+tickBurn();tickCombatEffects();persist();return message}
export function defend(){if(!state.combat)return 'There is nothing to defend against.';state.combat.guard=true;const message=`You brace against ${state.combat.displayName||monsterForId(state.combat.monsterId).name}.`+enemyTurn()+tickBurn();tickCombatEffects();persist();return message}
function tickBurn(){const ticks=tickStatuses(state.player);if(!ticks.length)return '';for(const tick of ticks)bumpCareer('damageTaken',tick.damage);const message=ticks.map(tick=>`${tick.name} damage: ${tick.damage}.`).join(' ');if(state.player.hp<=0)return ` ${message}`+resolveDefeat();return ` ${message}`}
export function useItem(id){const item=items[id];if(!item?.effect||!owned(id))return 'You do not have that usable item.';if(item.effect.type==='combat-tool'){const c=state.combat;if(!c)return 'That item is useful during combat.';const monster=monsterForId(c.monsterId);if(!item.effect.targetTags.some(tag=>monster.tags?.includes(tag)))return `${item.name} has no special effect on ${monster.name}; it is not consumed.`;removeItem(id,1);const damage=Math.max(1,item.effect.damage-Math.floor(c.defense/2));c.hp-=damage;c.physicalResistanceReductionTurns=Math.max(c.physicalResistanceReductionTurns||0,item.effect.resistanceReductionTurns||0)+1;bumpCareer('damageDealt',damage);let text=`${item.name} deals ${damage} damage and thins the gas cloud; its physical resistance is reduced for your next hit.`;if(c.hp<=0){const defeated={...c};state.combat=null;const encounter=state.dungeon.encounters.at(-1);if(encounter)encounter.cleared=true;text+=` ${c.displayName} disperses.`+lootReward(monster,defeated);tickTemporaryEffects();persist();return text}text+=enemyTurn()+tickBurn();tickCombatEffects();persist();return text}if(item.effect.type==='heal'){state.player.hp=Math.min(state.player.maxHp,state.player.hp+item.effect.amount);removeItem(id,1);const enemy=state.combat?enemyTurn():'';const burn=tickBurn();tickCombatEffects();persist();return `You use ${item.name}.${enemy}${burn}`}if(item.effect.type==='buff'){removeItem(id,1);addTemporaryEffect(item.effect.name,item.effect.value,item.effect.encounters);const enemy=state.combat?enemyTurn():'';const burn=tickBurn();tickCombatEffects();persist();return `You use ${item.name}. ${item.effect.name} improves for ${item.effect.encounters} encounters.${enemy}${burn}`}return 'Nothing happens.'}
export function useTonic(){return useItem('healing-tonic')}
export function equipItem(id){const item=items[id];if(state.combat)return {ok:false,message:'You cannot change equipment during combat.'};if(!item?.slot||!owned(id))return {ok:false,message:'That item cannot be equipped.'};if(item.classes&&!item.classes.includes(state.player.class))return {ok:false,message:`${item.name} is limited to ${item.classes.join(' or ')}.`};state.equipment[item.slot]=id;recalculateStats();persist();return {ok:true,message:`Equipped ${item.name}.`}}
export function unequipSlot(slot){if(state.combat||!EQUIPMENT_SLOTS.includes(slot)||!state.equipment[slot])return false;delete state.equipment[slot];recalculateStats();persist();return true}
const coreShopStock=['healing-tonic','rusty-sword','leather-armor'];
function rotateShopIds(rotation=0){const candidates=shopStock.filter(id=>!coreShopStock.includes(id)),seededValue=((state.dungeon.seed>>>0)^Math.imul(rotation+1,0x9e3779b1))>>>0;let seed=seededValue||1;const roll=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};for(let i=candidates.length-1;i>0;i--){const j=Math.floor(roll()*(i+1));[candidates[i],candidates[j]]=[candidates[j],candidates[i]]}return candidates.slice(0,3)}
function currentShopIds(){state.town.shop=state.town.shop||{rotation:0,rotatingIds:[]};const shop=state.town.shop;if(!Array.isArray(shop.rotatingIds)||shop.rotatingIds.length!==3||shop.rotatingIds.some(id=>!shopStock.includes(id)||coreShopStock.includes(id))){shop.rotatingIds=rotateShopIds(shop.rotation||0);persist()}return [...coreShopStock,...shop.rotatingIds]}
function restockShop(){state.town.shop=state.town.shop||{rotation:0,rotatingIds:[]};state.town.shop.rotation=(state.town.shop.rotation||0)+1;state.town.shop.rotatingIds=rotateShopIds(state.town.shop.rotation);townFlag('storeRestocked');persist()}
export function buyPrice(id,merchantId='juniper'){const item=items[id],profile=merchantProfiles[merchantId]||merchantProfiles.juniper,multiplier=profile?.buyMultiplier||1;return Math.max(1,Math.floor((item?.buyValue||0)*multiplier*(1-equippedEffect('buyDiscount'))))}
export function buyItem(id,priceOverride=null){const item=items[id];if(!item||!currentShopIds().includes(id))return {ok:false,message:'That item is not on Juniper’s shelf.'};if(item.classes&&!item.classes.includes(state.player.class))return {ok:false,message:`${item.name} is limited to ${item.classes.join(' or ')}.`};const price=priceOverride??buyPrice(id);if(state.town.gold<price)return {ok:false,message:'Not enough gold.'};if(!canAddItem(id,1))return {ok:false,message:'Your pack is full. Sell something or clear a slot first.'};state.town.gold-=price;bumpCareer('goldSpent',price);addItem(id,1,{sourceType:'purchase',sourceName:'Juniper Dunn',acquiredFloor:0});persist();return {ok:true,message:`Bought ${item.name} for ${price} gold.`}}
export function salePrice(id){const item=items[id];return Math.max(1,Math.floor((item?.sellValue||0)*(1+equippedEffect('sellBonus'))))}
export function sellItem(id){const item=items[id];if(!item||!owned(id)||item.questItem)return {ok:false,message:'That item cannot be sold.'};if(!canRemoveItem(id,1))return {ok:false,message:`Keep ${questReservedQuantity(id)} ${item.name} for an active quest.`};if(equippedIds().includes(id))return {ok:false,message:'Unequip it before selling.'};const price=salePrice(id);removeItem(id,1);state.town.gold+=price;bumpCareer('goldEarned',price);emitGameEvent('itemSold',{id,price});persist();return {ok:true,message:`Sold ${item.name} for ${price} gold.`}}
export function canTrade(trade){return trade.requires.every(req=>owned(req.item)>=req.quantity&&canRemoveItem(req.item,req.quantity))&&state.town.gold>=trade.gold&&trade.gives.every(g=>canAddItem(g.item,g.quantity))}
export function completeTrade(tradeId){const trade=trades[tradeId];if(!trade||!canTrade(trade))return {ok:false,message:'The offer is not ready. Check the goods, gold, and pack space.'};for(const req of trade.requires)removeItem(req.item,req.quantity);state.town.gold-=trade.gold;bumpCareer('goldSpent',trade.gold);for(const g of trade.gives)addItem(g.item,g.quantity,{sourceType:'trade',sourceName:dungeonNpcs[trade.npcId]?.name||trade.npcId,acquiredFloor:state.dungeon.floor});emitGameEvent('tradeCompleted',{tradeId,npcId:trade.npcId});if(trade.npcId==='kobold-trader')townFlag('pipKnown');persist();return {ok:true,message:`Trade complete: ${trade.title}.`}}
export function buyNpcStock(npcId,itemId){const npc=dungeonNpcs[npcId],item=items[itemId];if(!npc?.stock?.includes(itemId)||!item)return {ok:false,message:'That item is not offered.'};const price=buyPrice(itemId,npcId);if(state.town.gold<price)return {ok:false,message:'Not enough gold.'};if(!canAddItem(itemId,1))return {ok:false,message:'Your pack is full.'};state.town.gold-=price;bumpCareer('goldSpent',price);addItem(itemId,1,{sourceType:'purchase',sourceName:npc.name,acquiredFloor:state.dungeon.floor});persist();return {ok:true,message:`Bought ${item.name} for ${price} gold.`}}
export function closeNpc(){const id=state.dungeon.currentNpcId,npc=state.dungeon.npcs.find(n=>n.floor===state.dungeon.floor&&n.id===id&&n.x===state.dungeon.x&&n.y===state.dungeon.y);if(npc)npc.resolved=true;if(id){const memory=state.town.npcProgress||(state.town.npcProgress={});memory[id]=(memory[id]||0)+1;if(id==='lost-surveyor'&&state.dungeon.floor>=2)state.dungeon.eventFlags['met-nell-deeper']=true}state.dungeon.currentNpcId=null;persist()}
export function descend(){const d=state.dungeon;if(d.x!==d.map.downStairs[0]||d.y!==d.map.downStairs[1])return 'Find the lower stair first.';if(d.floor>=3)return 'The stairs end at a sealed municipal door. For now.';d.floor++;d.deepestFloor=Math.max(d.deepestFloor||1,d.floor);state.career.deepestFloor=Math.max(state.career.deepestFloor||1,d.floor);if(d.floor>=3)unlockAchievement('deep-works');d.eventFlags['depth-marker-reached']=true;const map=floorMap(d.floor);d.x=map.upStairs[0];d.y=map.upStairs[1];d.facing=2;ensureFloorNpcs(d.floor);reveal();persist();return `You descend to level ${d.floor}. The air is warmer and the prices, presumably, are worse.`}
export function ascend(){const d=state.dungeon;if(d.x!==d.map.upStairs[0]||d.y!==d.map.upStairs[1])return 'Find the upper stair first.';if(d.floor===1){returnTown();return 'You climb back to town.'}d.floor--;const map=floorMap(d.floor);d.x=map.downStairs[0];d.y=map.downStairs[1];d.facing=0;reveal();persist();return `You climb to level ${d.floor}.`}
function retreatChance(enemySpeed=0){return Math.max(.2,Math.min(.9,.62+state.player.agi*.035+(state.player.class==='Rogue'?.08:0)+equippedEffect('retreatBonus')/100-enemySpeed*.045-(state.dungeon.floor-1)*.05-statusModifier(state.player,'slowed')*.05))}
export function retreatChancePercent(){const c=state.combat,enemySpeed=c?.speed??0;return Math.round(retreatChance(enemySpeed)*100)}
export function retreat(){const c=state.combat;if(!c)return {ok:false,message:'Use Return to Town to retrace a known route.'};const enemySpeed=c.speed??monsterForId(c.monsterId).speed,chance=retreatChance(enemySpeed);state.player.turns++;if(random()<chance){const name=c.displayName||monsterForId(c.monsterId).name;state.combat=null;tickTemporaryEffects();bumpCareer('combatRetreats');persist();return {ok:true,message:`You escape ${name}.`}}const msg=`Retreat failed (${Math.round(chance*100)}% chance).`+enemyTurn()+tickBurn();persist();return {ok:false,message:msg}}
export function collectFind(){const d=state.dungeon,cacheId=`cache-${d.floor}-first`,cell=d.lunchboxCell||[3,4];if(d.floor!==1||d.x!==cell[0]||d.y!==cell[1]||d.finds.includes(cacheId))return {ok:false,message:'Nothing else is here.'};const awards=[['blue-lunchbox',1],['stone-chip',1],['cave-salt',1]];const full=awards.filter(([id,q])=>!canAddItem(id,q));if(full.length)return {ok:false,message:'Your pack is full. Make room before collecting this cache.'};for(const [id,q] of awards)addItem(id,q);d.finds.push(cacheId);d.lootTaken=true;progress('loot','lunchbox');progress('loot','stone');persist();return {ok:true,message:'You recover Mara’s lunchbox, a stone chip, and some cave salt.'}}
export function collectGroundLoot(index){const d=state.dungeon,drop=d.groundLoot[index];if(!drop||drop.floor!==d.floor||drop.x!==d.x||drop.y!==d.y)return {ok:false,message:'There is no loose loot here.'};if(!canAddItem(drop.item,drop.quantity))return {ok:false,message:'Your pack is full. Make room before collecting it.'};addItem(drop.item,drop.quantity);progress('loot',drop.item);d.groundLoot.splice(index,1);persist();const item=items[drop.item];return {ok:true,message:item.slot?`Found: ${item.name}. ${item.rarity} · ${item.slot}. Open Inventory / Gear to equip it.`:`Collected ${item.name}.`}}
function applyOutcome(outcome,messages){const d=state.dungeon;switch(outcome.type){case 'message':messages.push(outcome.text);break;case 'gold':d&&(state.town.gold=Math.max(0,state.town.gold+outcome.amount));if(outcome.amount>0)bumpCareer('goldEarned',outcome.amount);else if(outcome.amount<0)bumpCareer('goldSpent',-outcome.amount);break;case 'item':if(!addItem(outcome.item,outcome.quantity||1,{sourceType:'event',sourceName:d.currentEventId||'dungeon discovery',acquiredFloor:d.floor}))d.groundLoot.push({floor:d.floor,x:d.x,y:d.y,item:outcome.item,quantity:outcome.quantity||1});else{progress('loot',outcome.item);if(items[outcome.item]?.slot)messages.push(`Found: ${items[outcome.item].name}. Open Inventory / Gear to equip it.`)}break;case 'removeItem':removeItem(outcome.item,outcome.quantity||1);break;case 'heal':state.player.hp=Math.min(state.player.maxHp,state.player.hp+outcome.amount);break;case 'damage':state.player.hp=Math.max(1,state.player.hp-outcome.amount);bumpCareer('damageTaken',outcome.amount);break;case 'effect':addTemporaryEffect(outcome.name,outcome.value,outcome.encounters);break;case 'flag':d.eventFlags[outcome.flag]=true;break;case 'townReaction':state.town.reactions=[...(state.town.reactions||[]),outcome.text].slice(-6);break;case 'unlockQuest':{const q=outcome.quest,known=[...state.quests.available,...state.quests.completed,...state.quests.active.map(x=>x.id)];if(quests[q]&&!known.includes(q))state.quests.available.push(q);break}case 'questProgress':progress(outcome.questType,outcome.target);break;case 'discover':if(!d.landmarks.some(l=>l.id===outcome.landmark&&l.floor===d.floor)){d.landmarks.push({id:outcome.landmark,label:outcome.label,icon:outcome.icon,floor:d.floor,x:d.x,y:d.y});d.eventFlags[`landmark:${outcome.landmark}`]=true;if(outcome.landmark==='warm-wall'){d.eventFlags['warm-wall-seen']=true;townFlag('warmWallDocumented')}if(outcome.landmark==='giant-stone-face')townFlag('stoneFaceReported')}break;case 'room':d.rooms[cellKey(d.floor,d.x,d.y)]=outcome.room;break;case 'encounter':{const key=monsters[outcome.monster]?outcome.monster:Object.keys(monsters).find(id=>monsters[id].id===outcome.monster);if(key){d.currentEventId=null;beginCombat(key,d.x,d.y)}break}case 'random':{const row=weightedChoice(outcome.outcomes||[],random);if(row)applyOutcomes(row.outcomes,messages);break}case 'skillCheck':{const classBonus=state.player.class==='Rogue'&&outcome.stat==='agi'||state.player.class==='Wizard'&&outcome.stat==='mind'||state.player.class==='Cleric'&&outcome.stat==='mind'||state.player.class==='Fighter'&&outcome.stat==='str'?1:0,success=(state.player[outcome.stat]||0)+classBonus>=(outcome.threshold||0);applyOutcomes(success?outcome.success:outcome.failure,messages);break}}}
function applyOutcomes(outcomes,messages){for(const outcome of outcomes||[])applyOutcome(outcome,messages)}
export function resolveDungeonEvent(eventId,choiceId){const d=state.dungeon,event=dungeonEvents[eventId];if(!event||d.currentEventId!==eventId)return {ok:false,message:'That event is no longer here.'};const choice=event.choices.find(c=>c.id===choiceId);if(!choice||choice.requiresEffect&&!equippedEffect(choice.requiresEffect))return {ok:false,message:'That choice is not available.'};if(choice.requiresGold&&state.town.gold<choice.requiresGold)return {ok:false,message:'You do not have enough gold.'};if(choice.requiresItem&&owned(choice.requiresItem.item)<choice.requiresItem.quantity)return {ok:false,message:`You need ${choice.requiresItem.quantity} ${items[choice.requiresItem.item].name}.`};if(choice.requiresFlag&&!d.eventFlags[choice.requiresFlag])return {ok:false,message:'You have not discovered what this choice needs.'};if(choice.requiresQuest&&!state.quests.active.some(q=>q.id===choice.requiresQuest))return {ok:false,message:'That choice requires an active quest.'};const messages=[];applyOutcomes(choice.outcomes,messages);if(eventId==='the-duck'){bumpCareer('ducksEncountered');unlockAchievement('duck-report')}if(eventId==='vending-machine'){townFlag('vendingMachineReported');if(choiceId==='shake')bumpCareer('vendingShakes')}if(eventId==='very-small-door')townFlag('smallDoorDiscovered');if(eventId==='abandoned-camp')townFlag('surveyCrewStatus','camp-found');if(state.player.class==='Cleric'&&d.rooms[`${d.floor}:${d.x},${d.y}`]==='shrine'){const hp=Math.min(2,state.player.maxHp-state.player.hp),mp=Math.min(1,state.player.maxMp-state.player.mp);state.player.hp+=hp;state.player.mp+=mp;if(hp||mp)messages.push('Your cleric’s blessing steadies you at the shrine.')}d.currentEventId=null;const record=d.eventState[eventId]||(d.eventState[eventId]={count:0,lastStep:d.encounterStep,resolved:false});record.count++;record.resolved=!event.repeatable;d.eventHistory.push({id:eventId,choice:choiceId,floor:d.floor,step:d.encounterStep});emitGameEvent('eventResolved',{id:eventId,choice:choiceId,floor:d.floor});persist();return {ok:true,message:messages.join(' ')||'You continue on.'}}
export function triggerEvent(id){if(!dungeonEvents[id])return false;state.dungeon.currentEventId=id;state.dungeon.inDungeon=true;persist();return true}
export function triggerRandomEvent(){state.dungeon.inDungeon=true;const event=openRandomEvent(state.dungeon.floor,state.dungeon.x,state.dungeon.y);return event?.id||null}
export function revealLandmark(id){const event=Object.values(dungeonEvents).find(e=>e.choices.some(c=>c.outcomes?.some(o=>o.type==='discover'&&o.landmark===id)));if(!event)return false;state.dungeon.inDungeon=true;state.dungeon.currentEventId=event.id;return resolveDungeonEvent(event.id,event.choices.find(c=>c.outcomes?.some(o=>o.type==='discover'&&o.landmark===id)).id).ok}
export function qaSetTemporaryEffect(name,value=1,encounters=2){if(value===0){delete state.player.temporaryEffects?.[name];persist();return true}addTemporaryEffect(name,value,encounters);return true}
export function qaResetEventState(){state.dungeon.currentEventId=null;state.dungeon.eventState={};state.dungeon.eventFlags={};state.dungeon.eventHistory=[];state.dungeon.eventedCells=[];state.dungeon.rooms={};state.dungeon.landmarks=[];persist()}
export function qaSetRoom(roomId){if(!roomTypes[roomId])return false;state.dungeon.inDungeon=true;state.dungeon.rooms[cellKey(state.dungeon.floor,state.dungeon.x,state.dungeon.y)]=roomId;persist();return true}
export function talkNpc(id){const npc=dungeonNpcs[id];if(!npc)return 'The visitor gives an unhelpful nod.';if(id==='kobold-trader')townFlag('pipKnown');if(id==='lost-surveyor')townFlag('nellKnown');const visits=state.town.npcProgress?.[id]||0;if(id==='kobold-trader'){if(state.dungeon.floor>=3)return visits?`Pip flips to a new page. “The deeper floor has better merchandise and worse liability.”`:'“Floor three prices are final. I have checked with myself.”';if(visits)return 'Pip recognizes you and updates the ledger. The prices remain emotionally flexible.'}if(id==='lost-surveyor'){if(state.dungeon.floor>=2){state.dungeon.eventFlags['met-nell-deeper']=true;persist();return visits?'Nell has marked the impossible geometry as “expected variance.”':'Nell is relieved to see another person. She gives you her deeper-floor survey note.'}if(visits)return 'Nell has walked in a circle and insists it was a planned calibration.'}return npc.line}
export function storeStock(){return currentShopIds().map(id=>items[id])}
export function xpToNext(){return state.player.level*25-state.player.xp}

// Development-only actions are also kept out of the regular game action paths.
export function qaGiveItem(id,qty=1){return addItem(id,qty)}
export function qaRemoveItem(id,qty=1){return removeItem(id,qty)}
export function qaGiveGold(amount){state.town.gold=Math.max(0,state.town.gold+amount);persist()}
export function qaSpawnMonster(id,floor=state.dungeon.floor,variantId=null,encounterLevel=null){const key=monsters[id]?id:Object.keys(monsters).find(monsterId=>monsters[monsterId].id===id);if(!key)return false;state.dungeon.inDungeon=true;state.combat=null;beginCombat(key,state.dungeon.x,state.dungeon.y,{floor:Number(floor)||1,variantId,encounterLevel:Number.isFinite(Number(encounterLevel))?Number(encounterLevel):null});persist();return true}
export function qaEnemyScalingMatrix(){return ['rat','pocketSlime','kungFuGoose','fireWorm','paperMimic'].flatMap(id=>[1,3,5,10].filter(floor=>floor>=monsters[id].minDepth).map(floor=>{const instance=scaleEnemy(monsters[id],floor,null),threat=state.player?threatAssessment(instance,{...state.player,fireResistance:equippedEffect('fireResistance')}):null;return {monster:monsters[id].name,floor,tier:monsters[id].baseTier,level:instance.encounterLevel,baseHp:monsters[id].hp,scaledHp:instance.maxHp,baseDefense:monsters[id].defense,scaledDefense:instance.defense,baseAttackRanges:monsters[id].attacks.map(a=>`${a.name} ${a.minDamage}-${a.maxDamage}`),scaledAttackRanges:instance.attacks.map(a=>`${a.name} ${a.minDamage}-${a.maxDamage} (w ${a.weight.toFixed(2)})`),baseXp:monsters[id].xp,scaledXp:instance.xp,goldMultiplier:Number(instance.goldMultiplier.toFixed(2)),threat:threat?.label,score:threat?.score}}))}
export function qaSpawnNpc(id){if(!dungeonNpcs[id])return false;state.dungeon.inDungeon=true;state.dungeon.currentNpcId=id;let visitor=state.dungeon.npcs.find(n=>n.id===id&&n.floor===state.dungeon.floor);if(visitor){visitor.x=state.dungeon.x;visitor.y=state.dungeon.y;visitor.resolved=false}else state.dungeon.npcs.push({id,floor:state.dungeon.floor,x:state.dungeon.x,y:state.dungeon.y,resolved:false});persist();return true}
export function qaAdvanceFloor(){const d=state.dungeon;d.floor=Math.min(3,d.floor+1);d.deepestFloor=Math.max(d.deepestFloor||1,d.floor);const map=floorMap(d.floor);d.inDungeon=true;d.x=map.upStairs[0];d.y=map.upStairs[1];ensureFloorNpcs(d.floor);reveal();persist()}
export function qaRegenerateFloor(){const d=state.dungeon;d.maps[String(d.floor)]=generateFloorMap((d.seed+Math.floor(Math.random()*2147483646)+1)>>>0,d.floor);d.map=d.maps[String(d.floor)];d.explored=d.explored.filter(cell=>!cell.startsWith(`${d.floor}:`));d.rooms=Object.fromEntries(Object.entries(d.rooms).filter(([cell])=>!cell.startsWith(`${d.floor}:`)));d.eventedCells=d.eventedCells.filter(cell=>!cell.startsWith(`${d.floor}:`));d.npcs=d.npcs.filter(n=>n.floor!==d.floor);if(d.floor===1){d.lunchboxCell=null;if(d.rat)d.rat.position=false}d.x=d.map.upStairs[0];d.y=d.map.upStairs[1];state.combat=null;ensureFloorNpcs(d.floor);reveal();persist();return d.map}
export function qaTeleportEdge(edge){const d=state.dungeon,map=d.map,candidates=edge==='north'?openCells(map).filter(([x,y])=>y===1):edge==='south'?openCells(map).filter(([x,y])=>y===map.height-2):edge==='west'?openCells(map).filter(([x,y])=>x===1):openCells(map).filter(([x,y])=>x===map.width-2);const cell=candidates[0];return cell?qaTeleport(cell[0],cell[1]):false}
export function qaRevealFloor(){const d=state.dungeon;for(const [x,y] of openCells(d.map)){const k=`${x},${y}`;if(!d.explored.includes(`${d.floor}:${k}`))d.explored.push(`${d.floor}:${k}`)}persist();return true}
export function qaFloorValidation(){const d=state.dungeon,map=d.map,start=map.upStairs,found=new Set([`${start[0]},${start[1]}`]),queue=[start];for(let i=0;i<queue.length;i++){const [x,y]=queue[i];for(const [dx,dy] of [[0,-1],[1,0],[0,1],[-1,0]]){const nx=x+dx,ny=y+dy,k=`${nx},${ny}`;if(nx>0&&ny>0&&nx<map.width-1&&ny<map.height-1&&!wallAt(d,nx,ny)&&!found.has(k)){found.add(k);queue.push([nx,ny])}}}return {valid:found.has(`${map.downStairs[0]},${map.downStairs[1]}`)&&!wallAt(d,d.x,d.y),seed:map.seed||null,width:map.width,height:map.height,walkable:openCells(map).length,connected:found.size,stairsConnected:found.has(`${map.downStairs[0]},${map.downStairs[1]}`),generationAttempts:map.generationAttempts||1}}
export function qaTeleport(x,y){const d=state.dungeon;x=Math.max(1,Math.min(d.map.width-2,Number(x)||1));y=Math.max(1,Math.min(d.map.height-2,Number(y)||1));if(wallAt(d,x,y))return false;d.inDungeon=true;d.currentEventId=null;d.currentNpcId=null;state.combat=null;d.x=x;d.y=y;reveal();persist();return true}
export function qaForceAttack(id){if(!state.combat)return false;if(!state.combat.attacks?.some(a=>a.id===id))return false;state.combat.forcedAttackId=id;persist();return true}
export function qaAttackPoolReport(monsterId,levels=[1,3,5,8,12],runs=1000){const monster=monsterForId(monsterId)||monsters[monsterId];if(!monster)return {error:`Unknown monster: ${monsterId}`};runs=Math.max(1,Math.min(5000,Math.floor(runs)));let seed=0x51f15e;const randomFn=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};return levels.map(requestedLevel=>{const instance=scaleEnemy(monster,monster.minDepth,null,requestedLevel),counts=Object.fromEntries(instance.attacks.map(a=>[a.id,0]));for(let i=0;i<runs;i++){const chosen=chooseEnemyAttack(instance.aiProfile,instance.attacks,{hp:14,maxHp:24},randomFn);if(chosen)counts[chosen.id]++}return {requestedLevel,encounterLevel:instance.encounterLevel,aiProfile:instance.aiProfile,eligible:instance.attacks.map(a=>({id:a.id,name:a.name,weight:Number(a.weight.toFixed(3)),damage:[a.minDamage,a.maxDamage],effect:a.effect||null,effectChance:a.effectChance??null})),locked:(monster.attacks||[]).filter(a=>(a.unlockLevel||1)>instance.encounterLevel).map(a=>({id:a.id,name:a.name,unlockLevel:a.unlockLevel})),simulations:runs,selected:Object.fromEntries(Object.entries(counts).map(([id,count])=>[id,`${(100*count/runs).toFixed(1)}%`]))}})}
export function qaSetResources(gold,hp,mp){state.town.gold=Math.max(0,Number(gold)||0);state.player.hp=Math.max(1,Math.min(state.player.maxHp,Number(hp)||1));state.player.mp=Math.max(0,Math.min(state.player.maxMp,Number(mp)||0));persist()}
export function qaSetClass(cls){if(!STARTING_CLASSES[cls]||!state.player)return false;const base=STARTING_CLASSES[cls],hpRatio=state.player.hp/state.player.maxHp,mpRatio=state.player.maxMp?state.player.mp/state.player.maxMp:1;state.player.class=cls;state.player.baseStr=base.str;state.player.baseAgi=base.agi;state.player.baseMind=base.mind;state.player.baseVit=base.vit;state.player.baseMaxHp=base.hp+(state.player.level-1)*2;state.player.baseMaxMp=base.mp+(state.player.level-1);recalculateStats();state.player.hp=Math.round(state.player.maxHp*hpRatio);state.player.mp=Math.round(state.player.maxMp*mpRatio);persist();return true}
export function qaSetLevel(level){const p=state.player;if(!p)return false;const n=Math.max(1,Math.min(30,Math.floor(Number(level)||1))),base=STARTING_CLASSES[p.class];p.level=n;p.xp=0;p.baseMaxHp=base.hp+(n-1)*2;p.baseMaxMp=base.mp+(n-1);p.baseVit=base.vit+(n-1);recalculateStats();p.hp=p.maxHp;p.mp=p.maxMp;persist();return true}
export function qaStartQuest(id){if(!quests[id]||state.quests.completed.includes(id)||state.quests.active.some(q=>q.id===id))return false;state.quests.available=state.quests.available.filter(q=>q!==id);state.quests.available.push(id);return acceptQuest(id)}
export function qaResetCareer(){state.career={deepestFloor:state.dungeon.deepestFloor||1};state.achievements={unlocked:{}};persist()}
export function qaUnlockAchievement(id){return unlockAchievement(id)}
export function qaEconomySimulation(runs=100,floor=1){runs=Math.max(1,Math.min(1000,Math.floor(runs)));floor=Math.max(1,Math.floor(floor));const rows=(floorEncounterTable[floor]||floorEncounterTable[3]).filter(row=>monsters[row.id]&&monsters[row.id].minDepth<=floor),total=rows.reduce((n,r)=>n+r.weight,0);let gold=0,xp=0,incoming=0;const rarityCounts={common:0,uncommon:0,rare:0,strange:0};let seed=123456789;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296},weighted=(list,key)=>{let n=rand()*list.reduce((sum,row)=>sum+row[key],0);for(const row of list){n-=row[key];if(n<0)return row}return list.at(-1)};for(let i=0;i<runs;i++){const row=weighted(rows,'weight'),m=monsters[row.id];let variant=null,variantRoll=rand();for(const candidate of enemyVariants){variantRoll-=candidate.spawnChance;if(variantRoll<0){variant=candidate;break}}const instance=scaleEnemy(m,floor,variant),[lo,hi]=m.gold;gold+=Math.floor((lo+rand()*(hi-lo+1))*instance.rewardMultipliers.gold);xp+=instance.xp;const attack=weighted(instance.attacks,'weight');if(rand()<(attack.accuracy??.95))incoming+=Math.max(1,Math.floor(rand()*(attack.maxDamage-attack.minDamage+1))+attack.minDamage-2);const table=lootTables[m.lootTable]||[];if(table.length){const adjusted=table.map(item=>{const rarity=items[item.item]?.rarity||'common',factor=(rarities[rarity]?.weight||62)/62,mult=rarity==='rare'||rarity==='strange'?instance.lootMultiplier||1:1;return {...item,rarity,weight:item.weight*factor*mult}});rarityCounts[weighted(adjusted,'weight').rarity]++}}return {runs,floor,assumedPlayerDefense:2,averageGold:Number((gold/runs).toFixed(2)),averageXp:Number((xp/runs).toFixed(2)),averageIncomingDamagePerEnemyAction:Number((incoming/runs).toFixed(2)),averageLootRarity:Object.fromEntries(Object.entries(rarityCounts).map(([key,value])=>[key,`${(100*value/runs).toFixed(1)}%`]))}}
export function qaRevealNearby(){const d=state.dungeon;for(const [dx,dy] of [[0,0],[0,-1],[1,0],[0,1],[-1,0]]){const x=d.x+dx,y=d.y+dy;if(!wallAt(d,x,y)){const k=`${d.floor}:${x},${y}`;if(!d.explored.includes(k))d.explored.push(k)}}persist()}
export function qaRevealReturnRoute(){const d=state.dungeon,target={x:d.map.upStairs[0],y:d.map.upStairs[1]},key=p=>`${p.x},${p.y}`,queue=[{x:d.x,y:d.y}],prev=new Map([[key(queue[0]),null]]);while(queue.length){const p=queue.shift();if(key(p)===key(target))break;for(const [dx,dy] of [[0,-1],[1,0],[0,1],[-1,0]]){const next={x:p.x+dx,y:p.y+dy},k=key(next);if(!wallAt(d,next.x,next.y)&&!prev.has(k)){prev.set(k,key(p));queue.push(next)}}}if(!prev.has(key(target)))return false;let at=key(target);while(at){const [x,y]=at.split(',').map(Number),cell=`${d.floor}:${x},${y}`;if(!d.explored.includes(cell))d.explored.push(cell);at=prev.get(at)}persist();return true}
export function qaSetStat(name,value){if(!['baseStr','baseAgi','baseMind','baseVit','baseMaxHp','baseMaxMp'].includes(name))return false;state.player[name]=Math.max(0,Math.min(99,Number(value)||0));recalculateStats();persist();return true}
export function qaClearInventory(){state.inventory=[];state.equipment={};recalculateStats();persist()}
