export const SAVE_KEY='mirpworks-hole-town-save';
export const SAVE_VERSION=5;
export const INVENTORY_CAPACITY=16;
export const EQUIPMENT_SLOTS=['head','body','mainHand','offHand','feet','accessory'];
import {monsters} from './data.js?v=room-visuals-20261002d';
import {scaleEnemy} from './enemy-scaling.js?v=enemy-depth-20261002';

// Legacy v3 saves used this fixed 7x7 floor. Keep that geometry when migrating
// existing characters so their coordinates, discoveries, and encounters survive.
const legacyWalls=[[0,0],[1,0],[2,0],[4,0],[5,0],[6,0],[0,1],[6,1],[0,2],[3,2],[6,2],[0,3],[6,3],[0,4],[2,4],[6,4],[0,5],[6,5],[0,6],[1,6],[2,6],[3,6],[4,6],[5,6],[6,6]];
export function createFloorMap(){return {width:7,height:7,walls:legacyWalls.map(([x,y])=>[x,y]),upStairs:[5,1],downStairs:[5,5],legacy:true}}
function seeded(seed){let n=(seed>>>0)||1;return ()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296}}
const key=(x,y)=>`${x},${y}`;
export function generateFloorMap(seed,floor=1,attempt=1){
  const width=11,height=11,random=seeded((seed^Math.imul(floor,0x9e3779b1))>>>0),walls=new Set();
  for(let y=0;y<height;y++)for(let x=0;x<width;x++)walls.add(key(x,y));
  const carve=(x,y)=>walls.delete(key(x,y));
  // Recursive backtracker on odd grid nodes makes a connected, branching maze.
  const start=[1,1],stack=[start];carve(...start);const seen=new Set([key(...start)]);
  while(stack.length){const [x,y]=stack.at(-1),options=[[0,-2],[2,0],[0,2],[-2,0]].map(([dx,dy])=>[x+dx,y+dy,dx,dy]).filter(([nx,ny])=>nx>0&&ny<height-1&&nx<width-1&&ny>0&&!seen.has(key(nx,ny)));
    if(!options.length){stack.pop();continue}const [nx,ny,dx,dy]=options[Math.floor(random()*options.length)];carve(x+dx/2,y+dy/2);carve(nx,ny);seen.add(key(nx,ny));stack.push([nx,ny]);
  }
  // Add loops and small chambers so routes have choices and rooms feel wider.
  for(let y=2;y<height-2;y++)for(let x=2;x<width-2;x++)if(walls.has(key(x,y))&&random()<.17){const around=[[x+1,y],[x-1,y],[x,y+1],[x,y-1]].filter(([ax,ay])=>!walls.has(key(ax,ay)));if(around.length>=2)carve(x,y)}
  const nodes=[...seen].map(v=>v.split(',').map(Number));for(let i=0;i<3;i++){const [x,y]=nodes[Math.floor(random()*nodes.length)],sx=x>=width-2?-1:1,sy=y>=height-2?-1:1;carve(x+sx,y);carve(x,y+sy);carve(x+sx,y+sy)}
  const reachable=(from)=>{const out=new Set([key(...from)]),queue=[from];for(let i=0;i<queue.length;i++){const [x,y]=queue[i];for(const [dx,dy] of [[0,-1],[1,0],[0,1],[-1,0]]){const nx=x+dx,ny=y+dy,k=key(nx,ny);if(nx>0&&ny>0&&nx<width-1&&ny<height-1&&!walls.has(k)&&!out.has(k)){out.add(k);queue.push([nx,ny])}}}return out};
  const up=[1,1],connected=reachable(up),candidates=[...connected].map(v=>v.split(',').map(Number)).filter(([x,y])=>Math.abs(x-up[0])+Math.abs(y-up[1])>=9);
  const down=candidates[Math.floor(random()*candidates.length)]||[9,9];
  if(!connected.has(key(...down))||walls.has(key(...up))||walls.has(key(...down))||connected.size<25)return generateFloorMap((seed+1)>>>0,floor,attempt+1);
  const map={width,height,walls:[...walls].map(v=>v.split(',').map(Number)),upStairs:up,downStairs:down,seed:seed>>>0,generationAttempts:attempt,legacy:false};
  map.walkableCount=width*height-map.walls.length;
  return map;
}
function mapSet(seed){return Object.fromEntries([1,2,3].map(f=>[f,generateFloorMap(seed,f)]))}
export function freshState(){const seed=Math.floor(Math.random()*2147483646)+1,maps=mapSet(seed),map=maps[1];return {saveVersion:SAVE_VERSION,player:null,inventory:[],equipment:{},town:{gold:25,reactions:[]},quests:{active:[],completed:[],available:['rat-problem','lost-lunchbox','stone-sample','goose-feather','earthworm-ember','depth-three']},dungeon:{floor:1,deepestFloor:1,x:map.upStairs[0],y:map.upStairs[1],facing:0,explored:[`1:${map.upStairs}`],visited:{'1':[key(...map.upStairs)]},map,maps,legacyMaps:false,seed,encounterStep:0,encounters:[],npcs:[],groundLoot:[],currentNpcId:null,currentEventId:null,eventState:{},eventFlags:{},eventHistory:[],eventedCells:[],rooms:{},landmarks:[],finds:[],lootTaken:false,lunchboxCell:null,rat:{x:4,y:3,hp:8,alive:true}},combat:null,settings:{inventoryCapacity:INVENTORY_CAPACITY,spriteStyle:'colored',enemyThreatDisplay:'descriptive',musicEnabled:true,musicVolume:.28},meta:{createdAt:Date.now(),updatedAt:Date.now()}}}

function migrateV1(s){const oldEquipment=s.equipment||{};s.equipment={mainHand:oldEquipment.mainHand||oldEquipment.weapon||'rusty-sword',body:oldEquipment.body||oldEquipment.armor||'patched-coat'};if(s.player){s.player.baseMaxHp=s.player.baseMaxHp??s.player.maxHp??s.player.hp??20;s.player.baseMaxMp=s.player.baseMaxMp??s.player.maxMp??s.player.mp??0;s.player.effects=s.player.effects||{};s.player.level=s.player.level||1;s.player.xp=s.player.xp||0;}s.dungeon=s.dungeon||{};s.dungeon.floor=Math.max(1,s.dungeon.floor||1);s.dungeon.deepestFloor=Math.max(s.dungeon.floor,s.dungeon.deepestFloor||1);s.dungeon.map={...createFloorMap(),...(s.dungeon.map||{}),upStairs:s.dungeon.map?.upStairs||s.dungeon.map?.stairs||[5,1],downStairs:s.dungeon.map?.downStairs||[5,5]};s.dungeon.explored=(s.dungeon.explored||[]).map(cell=>cell.includes(':')?cell:`${s.dungeon.floor}:${cell}`);s.dungeon.seed=s.dungeon.seed||Math.floor(Math.random()*2147483646)+1;s.dungeon.encounterStep=s.dungeon.encounterStep||0;s.dungeon.encounters=s.dungeon.encounters||[];s.dungeon.npcs=s.dungeon.npcs||[];s.dungeon.groundLoot=s.dungeon.groundLoot||[];s.dungeon.currentNpcId=null;s.dungeon.finds=s.dungeon.finds||[];if(s.dungeon.lootTaken&&!s.dungeon.finds.includes('cache-1-first'))s.dungeon.finds.push('cache-1-first');s.player&&(s.player.turns=s.player.turns||0);if(s.combat?.enemy)s.combat={monsterId:'rat',hp:s.combat.hp||4,maxHp:8,x:s.dungeon.x,y:s.dungeon.y,guard:false,burnTurns:0};else s.combat=null;s.settings=s.settings||{};s.town=s.town||{gold:0};s.quests=s.quests||{active:[],completed:[],available:[]};s.quests.active=s.quests.active||[];s.quests.completed=s.quests.completed||[];s.quests.available=s.quests.available||[];const known=[...s.quests.active.map(q=>q.id),...s.quests.completed,...s.quests.available];for(const id of ['goose-feather','earthworm-ember','depth-three'])if(!known.includes(id))s.quests.available.push(id);s.meta=s.meta||{createdAt:Date.now(),updatedAt:Date.now()};s.saveVersion=2;return s}
function migrateV2(s){s.town=s.town||{gold:0};s.town.reactions=s.town.reactions||[];s.player&&(s.player.temporaryEffects=s.player.temporaryEffects||{});s.dungeon=s.dungeon||{};s.dungeon.currentEventId=null;s.dungeon.eventState=s.dungeon.eventState||{};s.dungeon.eventFlags=s.dungeon.eventFlags||{};s.dungeon.eventHistory=s.dungeon.eventHistory||[];s.dungeon.eventedCells=s.dungeon.eventedCells||[];s.dungeon.rooms=s.dungeon.rooms||{};s.dungeon.landmarks=s.dungeon.landmarks||[];s.saveVersion=3;return s}
function migrateV3(s){const d=s.dungeon||{},legacy={...createFloorMap(),...(d.map||{})},deepest=Math.max(1,d.deepestFloor||d.floor||1),maps={};for(let floor=1;floor<=Math.min(3,deepest);floor++)maps[floor]=JSON.parse(JSON.stringify(legacy));d.maps=maps;d.map=maps[d.floor]||legacy;d.legacyMaps=true;d.lunchboxCell=[3,4];if(d.rat)d.rat.position=true;d.seed=d.seed||Math.floor(Math.random()*2147483646)+1;s.dungeon=d;s.saveVersion=4;return s}
function migrateV4(s){const c=s.combat,d=s.dungeon||{},id=c?.monsterId,monster=monsters[id];if(c&&monster){const snapshot=scaleEnemy(monster,Math.max(1,d.floor||1),null),ratio=Math.max(0,Math.min(1,(Number(c.hp)||0)/Math.max(1,Number(c.maxHp)||monster.hp)));s.combat={...c,...snapshot,hp:Math.max(0,Math.round(snapshot.maxHp*ratio)),maxHp:snapshot.maxHp,variantId:null,variantName:null,displayName:monster.name}}s.settings=s.settings||{};s.settings.enemyThreatDisplay=['descriptive','numeric','hidden'].includes(s.settings.enemyThreatDisplay)?s.settings.enemyThreatDisplay:'descriptive';s.saveVersion=5;return s}
function migrate(s){if(s.saveVersion===1)s=migrateV1(s);if(s?.saveVersion===2)s=migrateV2(s);if(s?.saveVersion===3)s=migrateV3(s);if(s?.saveVersion===4)s=migrateV4(s);if(s?.saveVersion!==SAVE_VERSION)return null;s.equipment=s.equipment||{};s.inventory=s.inventory||[];s.dungeon=s.dungeon||{};const d=s.dungeon;d.deepestFloor=Math.max(d.floor||1,d.deepestFloor||1);d.map={...createFloorMap(),...(d.map||{})};d.maps=d.maps||{[d.floor]:d.map};d.maps[d.floor]=d.map;d.legacyMaps=!!d.legacyMaps;d.seed=d.seed||Math.floor(Math.random()*2147483646)+1;d.encounters=d.encounters||[];d.npcs=d.npcs||[];d.groundLoot=d.groundLoot||[];d.finds=d.finds||[];d.currentEventId=d.currentEventId||null;d.eventState=d.eventState||{};d.eventFlags=d.eventFlags||{};d.eventHistory=d.eventHistory||[];d.eventedCells=d.eventedCells||[];d.rooms=d.rooms||{};d.landmarks=d.landmarks||[];s.town=s.town||{gold:0};s.town.reactions=s.town.reactions||[];s.player&&(s.player.temporaryEffects=s.player.temporaryEffects||{});s.settings=s.settings||{};if(!['colored','ink'].includes(s.settings.spriteStyle))s.settings.spriteStyle='colored';if(!['descriptive','numeric','hidden'].includes(s.settings.enemyThreatDisplay))s.settings.enemyThreatDisplay='descriptive';s.settings.musicEnabled=s.settings.musicEnabled!==false;const musicVolume=Number(s.settings.musicVolume);s.settings.musicVolume=Number.isFinite(musicVolume)?Math.max(0,Math.min(1,musicVolume)):.28;s.meta=s.meta||{createdAt:Date.now(),updatedAt:Date.now()};return s}
export function loadState(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return null;const parsed=JSON.parse(raw);if(!parsed||!parsed.saveVersion)return null;return migrate(parsed)}catch{return null}}
export function saveState(s){s.meta=s.meta||{};s.meta.updatedAt=Date.now();s.saveVersion=SAVE_VERSION;try{localStorage.setItem(SAVE_KEY,JSON.stringify(s));return true}catch{return false}}
export function hasSave(){return !!loadState()}
export function wallAt(d,x,y){return x<0||y<0||x>=d.map.width||y>=d.map.height||d.map.walls.some(([wx,wy])=>wx===x&&wy===y)}
