// Paired hand-drawn destination illustrations. Slots without assets keep their CSS emblem.
export const TOWN_ART_ASSETS={
  'the-hole':{
    ink:'assets/images/town/the-hole-ink.png',
    colored:'assets/images/town/the-hole-colored.png'
  },
  'inn':{
    ink:'assets/images/town/inn-sign-ink.png',
    colored:'assets/images/town/inn-sign-colored.png'
  },
  'general-store':{
    ink:'assets/images/town/store-sign-ink.png',
    colored:'assets/images/town/store-sign-colored.png'
  },
  'quest-board':{
    ink:'assets/images/town/quest-sign-ink.png',
    colored:'assets/images/town/quest-sign-colored.png'
  },
  'statistics':{
    ink:'assets/images/town/statistics-button-ink.png',
    colored:'assets/images/town/statistics-button-colored.png'
  },
  'achievements':{
    ink:'assets/images/town/achievements-button-ink.png',
    colored:'assets/images/town/achievements-button-colored.png'
  },
  'settings':{
    ink:'assets/images/town/settings-button-ink.png',
    colored:'assets/images/town/settings-button-colored.png'
  },
  'character':{
    ink:'assets/images/town/character-button-ink.png',
    colored:'assets/images/town/character-button-colored.png'
  }
};
