import {existsSync,readdirSync,readFileSync,writeFileSync} from 'node:fs';
import {resolve,relative,extname,join} from 'node:path';
import {LOCATION_MUSIC_POOLS} from '../js/location-music.js';
import {BATTLE_THEME,DUNGEON_TRACKS} from '../js/audio-catalog.js';
import {AUDIO_SOURCE_REGISTRY} from '../js/audio-sources.js';

const serviceRows=Object.entries(LOCATION_MUSIC_POOLS).map(([context,pool])=>'- '+context+': '+(pool.length?pool.map(t=>t.id+' ('+t.src+')').join(', '):'empty pool · silence is valid'));
const registered=[BATTLE_THEME,...DUNGEON_TRACKS.map(t=>t.src),...Object.values(LOCATION_MUSIC_POOLS).flat().map(t=>t.src)];
const allFiles=dir=>!existsSync(dir)?[]:readdirSync(dir,{withFileTypes:true}).flatMap(entry=>entry.isDirectory()?allFiles(join(dir,entry.name)):[join(dir,entry.name)]);
const runtimeFiles=allFiles(resolve('assets/audio/music')).filter(p=>['.mp3','.ogg','.wav','.m4a'].includes(extname(p).toLowerCase())).map(p=>relative(process.cwd(),p).replaceAll('\\','/')).sort();
const sourceFiles=allFiles(resolve('assets/audio/source')).filter(p=>['.flac','.m4a','.wav','.mp3'].includes(extname(p).toLowerCase())).map(p=>relative(process.cwd(),p).replaceAll('\\','/')).sort();
const registeredSourceSet=new Set(AUDIO_SOURCE_REGISTRY.map(row=>row.source));
const missingRuntime=registered.filter(path=>!existsSync(resolve(path)));
const unregisteredRuntime=runtimeFiles.filter(path=>!registered.includes(path));
const unmappedSources=sourceFiles.filter(path=>!registeredSourceSet.has(path));
const mappingErrors=AUDIO_SOURCE_REGISTRY.filter(row=>!existsSync(resolve(row.source))||!(Array.isArray(row.runtime)?row.runtime:[row.runtime]).every(path=>existsSync(resolve(path))));
const listOrNone=rows=>rows.length?rows.join(', '):'none';
const report=['# Audio registration inventory','',
  'Generated by node tools/audio-report.mjs --write. Refresh after audio registration changes. Source-to-runtime relationships are tracked in js/audio-sources.js; playback pools remain in js/location-music.js and js/audio.js.','',
  '## Registered playback','',
  '- Battle: '+BATTLE_THEME,
  '- Dungeon pool ('+DUNGEON_TRACKS.length+' tracks): '+DUNGEON_TRACKS.map(t=>t.id).join(', '),
  ...serviceRows,
  '- SFX: no runtime SFX tracks are currently registered.','',
  '## Asset audit','',
  '- Registered runtime tracks: '+registered.length+'; missing files: '+missingRuntime.length+'.',
  '- Runtime audio files: '+runtimeFiles.length+'; processed but unregistered: '+listOrNone(unregisteredRuntime)+'.',
  '- Source recordings/masters: '+sourceFiles.length+'; not mapped in the source registry: '+listOrNone(unmappedSources)+'.',
  '- Source-to-runtime mappings with missing files: '+listOrNone(mappingErrors.map(row=>row.source))+'.','',
  '## Source records','',
  ...AUDIO_SOURCE_REGISTRY.map(row=>'- '+row.source+' → '+(Array.isArray(row.runtime)?row.runtime:[row.runtime]).join(', ')),''
].join('\n');
const output=resolve('docs/AUDIO_INVENTORY.md');
if(process.argv.includes('--write'))writeFileSync(output,report);
else if(process.argv.includes('--check')){if(!existsSync(output)||readFileSync(output,'utf8')!==report){console.error('Audio inventory is stale. Run node tools/audio-report.mjs --write');process.exitCode=1}}
process.stdout.write(report);
if(missingRuntime.length||mappingErrors.length){console.error(`Audio inventory errors: ${missingRuntime.length} missing runtime registration(s), ${mappingErrors.length} broken source mapping(s).`);process.exitCode=1}
